// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs';

// Google TypeScript Style (https://google.github.io/styleguide/tsguide.html)
// essentials not already covered by the generated Nuxt/Vue/TS flat config's
// stylistic block (2-space indent, single quotes, semicolons, 1tbs braces,
// multiline trailing commas — configured in nuxt.config.ts `eslint.config`).
const googleStyleRules = {
  'curly': ['error', 'multi-line'],
  'eqeqeq': ['error', 'always'],
  'no-var': 'error',
  'prefer-const': ['error', { destructuring: 'all' }],
  'camelcase': ['error', { properties: 'never' }],
  'max-len': [
    'error',
    { code: 80, tabWidth: 2, ignoreUrls: true, ignoreComments: false },
  ],
};

export default withNuxt(
  {
    // Generated by `make api-gen` from docs/api/openapi.yaml — style rules
    // are meaningless on output nobody edits, and `--fix` would rewrite it
    // into permanent drift against the generator. `make api-check`, not
    // eslint, is what keeps this directory honest.
    ignores: ['app/api/generated/**'],
  },
  {
    rules: googleStyleRules,
  },
);
