// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs';

// Google TypeScript Style (https://google.github.io/styleguide/tsguide.html)
// essentials not already covered by the generated Nuxt/Vue/TS flat config's
// stylistic block (2-space indent, single quotes, semicolons, 1tbs braces,
// multiline trailing commas — configured in nuxt.config.ts `eslint.config`).
const googleStyleRules = {
  'curly': ['error', 'multi-line'],
  'eqeqeq': ['error', 'always'],
  'no-var': 'error',
  'prefer-const': ['error', { destructuring: 'all' }],
  'camelcase': ['error', { properties: 'never' }],
  'max-len': [
    'error',
    { code: 80, tabWidth: 2, ignoreUrls: true, ignoreComments: false },
  ],
};

const forbiddenRendererCalls = new Map([
  ['Date', new Set(['now'])],
  ['Math', new Set(['random'])],
  ['crypto', new Set(['getRandomValues', 'randomUUID'])],
  ['performance', new Set(['now'])],
]);

function staticPropertyName(node) {
  if (!node.computed && node.property.type === 'Identifier') {
    return node.property.name;
  }
  if (
    node.computed
    && node.property.type === 'Literal'
    && typeof node.property.value === 'string'
  ) {
    return node.property.value;
  }
  return null;
}

function rootIdentifier(node) {
  let current = node;
  while (current.type === 'MemberExpression') {
    current = current.object;
  }
  return current.type === 'Identifier' ? current : null;
}

function isGlobalIdentifier(sourceCode, identifier) {
  let scope = sourceCode.getScope(identifier);
  while (scope !== null) {
    const variable = scope.set.get(identifier.name);
    if (variable !== undefined) {
      return variable.defs.length === 0;
    }
    scope = scope.upper;
  }
  return true;
}

const noRendererNondeterminism = {
  meta: {
    type: 'problem',
    docs: {
      description: 'Disallow nondeterministic operations in resume renderers.',
    },
    schema: [],
    messages: {
      forbidden: 'Resume renderers cannot use {{dependency}}.',
    },
  },
  create(context) {
    const { sourceCode } = context;
    const report = (node, dependency) => context.report({
      node,
      messageId: 'forbidden',
      data: { dependency },
    });

    return {
      CallExpression(node) {
        if (node.callee.type !== 'MemberExpression') {
          return;
        }
        const property = staticPropertyName(node.callee);
        if (property?.startsWith('toLocale')) {
          report(node, `${property}()`);
          return;
        }

        const root = rootIdentifier(node.callee);
        if (root === null || !isGlobalIdentifier(sourceCode, root)) {
          return;
        }
        if (forbiddenRendererCalls.get(root.name)?.has(property)) {
          report(node, `${root.name}.${property}()`);
        }
      },
      NewExpression(node) {
        if (
          node.callee.type === 'Identifier'
          && node.callee.name === 'Date'
          && isGlobalIdentifier(sourceCode, node.callee)
        ) {
          report(node, 'new Date()');
        }
      },
      Identifier(node) {
        if (
          node.name !== 'Intl'
          || !isGlobalIdentifier(sourceCode, node)
          || (
            node.parent.type === 'MemberExpression'
            && node.parent.object === node
          )
          || (
            node.parent.type === 'Property'
            && node.parent.key === node
            && !node.parent.computed
            && !node.parent.shorthand
          )
        ) {
          return;
        }
        report(node, 'the Intl namespace');
      },
      MemberExpression(node) {
        const root = rootIdentifier(node);
        if (
          root?.name !== 'Intl'
          || !isGlobalIdentifier(sourceCode, root)
          || (
            node.parent.type === 'MemberExpression'
            && node.parent.object === node
          )
        ) {
          return;
        }
        report(node, 'the Intl namespace');
      },
    };
  },
};

const aboutmePlugin = {
  rules: {
    'no-renderer-nondeterminism': noRendererNondeterminism,
  },
};

export default withNuxt(
  {
    // Generated by `make api-gen` from docs/api/openapi.yaml — style rules
    // are meaningless on output nobody edits, and `--fix` would rewrite it
    // into permanent drift against the generator. `make api-check`, not
    // eslint, is what keeps this directory honest.
    ignores: ['app/api/generated/**'],
  },
  {
    rules: googleStyleRules,
  },
  {
    files: ['app/components/resume/**/*.{ts,vue,mts}'],
    plugins: {
      aboutme: aboutmePlugin,
    },
    rules: {
      'aboutme/no-renderer-nondeterminism': 'error',
      'no-restricted-globals': [
        'error',
        'fetch',
        '$fetch',
        'XMLHttpRequest',
        'WebSocket',
        'EventSource',
      ],
      'no-restricted-imports': [
        'error',
        {
          paths: ['pinia', '#app'],
          patterns: [
            {
              group: [
                '~/stores/**',
                '~/composables/**',
                '~/components/editor/**',
              ],
            },
          ],
        },
      ],
    },
  },
);
