// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_deletion.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteAccountUser = `-- name: DeleteAccountUser :execrows
DELETE FROM users WHERE id = $1::uuid
`

func (q *Queries) DeleteAccountUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccountUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountDeletedAuditEvent = `-- name: GetAccountDeletedAuditEvent :one
SELECT id, kind, occurred_at, media_job_id
FROM lifecycle_audit_events
WHERE id = $1::uuid
  AND kind = 'account_deleted'
  AND media_job_id IS NULL
`

func (q *Queries) GetAccountDeletedAuditEvent(ctx context.Context, id uuid.UUID) (LifecycleAuditEvent, error) {
	row := q.db.QueryRow(ctx, getAccountDeletedAuditEvent, id)
	var i LifecycleAuditEvent
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OccurredAt,
		&i.MediaJobID,
	)
	return i, err
}

const getAccountDeletionSessionForUpdate = `-- name: GetAccountDeletionSessionForUpdate :one
SELECT id, user_id, token_hash, csrf_secret, created_at, last_seen_at, reauthenticated_at, absolute_expires_at, rotation_grace_until, revoked_at, ua, ip, rotated_from
FROM sessions
WHERE id = $1::uuid
  AND user_id = $2::uuid
FOR UPDATE
`

type GetAccountDeletionSessionForUpdateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetAccountDeletionSessionForUpdate(ctx context.Context, arg GetAccountDeletionSessionForUpdateParams) (Session, error) {
	row := q.db.QueryRow(ctx, getAccountDeletionSessionForUpdate, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CSRFSecret,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ReauthenticatedAt,
		&i.AbsoluteExpiresAt,
		&i.RotationGraceUntil,
		&i.RevokedAt,
		&i.UA,
		&i.IP,
		&i.RotatedFrom,
	)
	return i, err
}

const insertAccountDeletedAuditEvent = `-- name: InsertAccountDeletedAuditEvent :one
INSERT INTO lifecycle_audit_events (id, kind, occurred_at, media_job_id)
VALUES ($1::uuid, 'account_deleted', $2::timestamptz, NULL)
RETURNING id, kind, occurred_at, media_job_id
`

type InsertAccountDeletedAuditEventParams struct {
	ID         uuid.UUID
	OccurredAt time.Time
}

func (q *Queries) InsertAccountDeletedAuditEvent(ctx context.Context, arg InsertAccountDeletedAuditEventParams) (LifecycleAuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAccountDeletedAuditEvent, arg.ID, arg.OccurredAt)
	var i LifecycleAuditEvent
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OccurredAt,
		&i.MediaJobID,
	)
	return i, err
}

const listAccountDeletionResumeSetForUpdate = `-- name: ListAccountDeletionResumeSetForUpdate :many
SELECT id, revision
FROM resumes
WHERE user_id = $1::uuid
ORDER BY id
FOR UPDATE
`

type ListAccountDeletionResumeSetForUpdateRow struct {
	ID       uuid.UUID
	Revision int64
}

func (q *Queries) ListAccountDeletionResumeSetForUpdate(ctx context.Context, userID uuid.UUID) ([]ListAccountDeletionResumeSetForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listAccountDeletionResumeSetForUpdate, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountDeletionResumeSetForUpdateRow
	for rows.Next() {
		var i ListAccountDeletionResumeSetForUpdateRow
		if err := rows.Scan(&i.ID, &i.Revision); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCanonicalAccountEmail = `-- name: LockCanonicalAccountEmail :exec

SELECT pg_advisory_xact_lock(
  hashtextextended('aboutme.email.v1:' || $1::text, 0)
)
`

// Account deletion owns the global lock order documented in
// docs/design/operations.md. The caller takes slug advisory locks and
// public_state before these account-scoped locks.
func (q *Queries) LockCanonicalAccountEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, lockCanonicalAccountEmail, email)
	return err
}
