// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_export.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAccountExportProfile = `-- name: GetAccountExportProfile :one

SELECT id, email, name, created_at, updated_at
FROM users
WHERE id = $1
`

type GetAccountExportProfileRow struct {
	ID        uuid.UUID
	Email     string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Account export deliberately reads only portable profile fields, provider
// names, and owner resume rows. Credentials, provider subjects, object keys,
// and lifecycle records do not cross the HTTP export boundary.
func (q *Queries) GetAccountExportProfile(ctx context.Context, id uuid.UUID) (GetAccountExportProfileRow, error) {
	row := q.db.QueryRow(ctx, getAccountExportProfile, id)
	var i GetAccountExportProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountExportProviders = `-- name: ListAccountExportProviders :many
SELECT provider
FROM identities
WHERE user_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListAccountExportProviders(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAccountExportProviders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountExportResumes = `-- name: ListAccountExportResumes :many
SELECT id, user_id, title, slug, live, download_enabled, seo_geo_enabled,
    schema_version, revision, lng, personal_details, content, customization,
    created_at, updated_at
FROM resumes
WHERE user_id = $1
ORDER BY created_at, id
LIMIT 4
`

func (q *Queries) ListAccountExportResumes(ctx context.Context, userID uuid.UUID) ([]Resume, error) {
	rows, err := q.db.Query(ctx, listAccountExportResumes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resume
	for rows.Next() {
		var i Resume
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Slug,
			&i.Live,
			&i.DownloadEnabled,
			&i.SEOGeoEnabled,
			&i.SchemaVersion,
			&i.Revision,
			&i.Lng,
			&i.PersonalDetails,
			&i.Content,
			&i.Customization,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
