// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_cleanup.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimMediaDeletionJobs = `-- name: ClaimMediaDeletionJobs :many

WITH candidates AS MATERIALIZED (
    SELECT job.id
    FROM media_deletion_jobs AS job
    WHERE job.completed_at IS NULL
      AND job.next_attempt_at <= $3::timestamptz
      AND (job.lease_id IS NULL OR job.lease_expires_at <= $4::timestamptz)
    ORDER BY job.next_attempt_at, job.id
    LIMIT LEAST($5::int, 200)
    FOR UPDATE SKIP LOCKED
)
UPDATE media_deletion_jobs AS job
SET lease_id = $1::uuid,
    lease_expires_at = $2::timestamptz,
    next_attempt_at = $2::timestamptz,
    attempt_count = job.attempt_count + 1
FROM candidates
WHERE job.id = candidates.id
RETURNING job.id, job.resume_id, job.object_key, job.enqueued_at, job.next_attempt_at, job.attempt_count, job.lease_id, job.lease_expires_at, job.completed_at, job.overdue_at, job.outcome
`

type ClaimMediaDeletionJobsParams struct {
	LeaseID        uuid.UUID
	LeaseExpiresAt time.Time
	DueAt          time.Time
	Now            time.Time
	MaxRows        int32
}

// Media deletion and orphan-reconciliation queries. The document photo key is
// the ownership authority; media_deletion_jobs is only durable cleanup work.
func (q *Queries) ClaimMediaDeletionJobs(ctx context.Context, arg ClaimMediaDeletionJobsParams) ([]MediaDeletionJob, error) {
	rows, err := q.db.Query(ctx, claimMediaDeletionJobs,
		arg.LeaseID,
		arg.LeaseExpiresAt,
		arg.DueAt,
		arg.Now,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaDeletionJob
	for rows.Next() {
		var i MediaDeletionJob
		if err := rows.Scan(
			&i.ID,
			&i.ResumeID,
			&i.ObjectKey,
			&i.EnqueuedAt,
			&i.NextAttemptAt,
			&i.AttemptCount,
			&i.LeaseID,
			&i.LeaseExpiresAt,
			&i.CompletedAt,
			&i.OverdueAt,
			&i.Outcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const classifyMediaObject = `-- name: ClassifyMediaObject :one
SELECT EXISTS (
           SELECT 1
           FROM resumes
           WHERE personal_details -> 'photo' ->> 'key' = $1::text
       ) AS live,
       EXISTS (
           SELECT 1
           FROM media_deletion_jobs
           WHERE object_key = $1::text
             AND completed_at IS NULL
       ) AS queued
`

type ClassifyMediaObjectRow struct {
	Live   bool
	Queued bool
}

func (q *Queries) ClassifyMediaObject(ctx context.Context, objectKey string) (ClassifyMediaObjectRow, error) {
	row := q.db.QueryRow(ctx, classifyMediaObject, objectKey)
	var i ClassifyMediaObjectRow
	err := row.Scan(&i.Live, &i.Queued)
	return i, err
}

const completeClaimedMediaDeletion = `-- name: CompleteClaimedMediaDeletion :one
WITH completed AS (
    UPDATE media_deletion_jobs AS job
    SET completed_at = $1::timestamptz,
        outcome = $2::text,
        lease_id = NULL,
        lease_expires_at = NULL
    WHERE job.id = $3::uuid
      AND job.lease_id = $4::uuid
      AND job.completed_at IS NULL
    RETURNING job.id
), audited AS (
    INSERT INTO lifecycle_audit_events (kind, occurred_at, media_job_id)
    SELECT 'media_deletion_completed', $1::timestamptz, completed.id
    FROM completed
    ON CONFLICT (media_job_id, kind) DO NOTHING
    RETURNING id
)
SELECT EXISTS (SELECT 1 FROM completed) AS completed
`

type CompleteClaimedMediaDeletionParams struct {
	Now     time.Time
	Outcome string
	ID      uuid.UUID
	LeaseID uuid.UUID
}

func (q *Queries) CompleteClaimedMediaDeletion(ctx context.Context, arg CompleteClaimedMediaDeletionParams) (bool, error) {
	row := q.db.QueryRow(ctx, completeClaimedMediaDeletion,
		arg.Now,
		arg.Outcome,
		arg.ID,
		arg.LeaseID,
	)
	var completed bool
	err := row.Scan(&completed)
	return completed, err
}

const createAndClaimOrphanMediaDeletion = `-- name: CreateAndClaimOrphanMediaDeletion :one
INSERT INTO media_deletion_jobs (
    resume_id, object_key, enqueued_at, next_attempt_at,
    attempt_count, lease_id, lease_expires_at
)
SELECT $1::uuid,
       $2::text,
       $3::timestamptz,
       $3::timestamptz,
       1,
       $4::uuid,
       $5::timestamptz
WHERE NOT EXISTS (
      SELECT 1
      FROM resumes
      WHERE personal_details -> 'photo' ->> 'key' = $2::text
  )
ON CONFLICT (object_key) DO NOTHING
RETURNING id, resume_id, object_key, enqueued_at, next_attempt_at, attempt_count, lease_id, lease_expires_at, completed_at, overdue_at, outcome
`

type CreateAndClaimOrphanMediaDeletionParams struct {
	ResumeID       uuid.UUID
	ObjectKey      string
	Now            time.Time
	LeaseID        uuid.UUID
	LeaseExpiresAt time.Time
}

func (q *Queries) CreateAndClaimOrphanMediaDeletion(ctx context.Context, arg CreateAndClaimOrphanMediaDeletionParams) (MediaDeletionJob, error) {
	row := q.db.QueryRow(ctx, createAndClaimOrphanMediaDeletion,
		arg.ResumeID,
		arg.ObjectKey,
		arg.Now,
		arg.LeaseID,
		arg.LeaseExpiresAt,
	)
	var i MediaDeletionJob
	err := row.Scan(
		&i.ID,
		&i.ResumeID,
		&i.ObjectKey,
		&i.EnqueuedAt,
		&i.NextAttemptAt,
		&i.AttemptCount,
		&i.LeaseID,
		&i.LeaseExpiresAt,
		&i.CompletedAt,
		&i.OverdueAt,
		&i.Outcome,
	)
	return i, err
}

const getMediaDeletionQueueState = `-- name: GetMediaDeletionQueueState :one
SELECT count(*) FILTER (WHERE completed_at IS NULL)::bigint AS pending,
       count(*) FILTER (
           WHERE completed_at IS NULL
             AND next_attempt_at <= $1::timestamptz
       )::bigint AS due,
       count(*) FILTER (
           WHERE completed_at IS NULL
             AND enqueued_at <= $2::timestamptz
       )::bigint AS overdue,
       COALESCE(
           min(enqueued_at) FILTER (WHERE completed_at IS NULL),
           $1::timestamptz
       ) AS oldest_enqueued_at
FROM media_deletion_jobs
`

type GetMediaDeletionQueueStateParams struct {
	Now           time.Time
	OverdueCutoff time.Time
}

type GetMediaDeletionQueueStateRow struct {
	Pending          int64
	Due              int64
	Overdue          int64
	OldestEnqueuedAt interface{}
}

func (q *Queries) GetMediaDeletionQueueState(ctx context.Context, arg GetMediaDeletionQueueStateParams) (GetMediaDeletionQueueStateRow, error) {
	row := q.db.QueryRow(ctx, getMediaDeletionQueueState, arg.Now, arg.OverdueCutoff)
	var i GetMediaDeletionQueueStateRow
	err := row.Scan(
		&i.Pending,
		&i.Due,
		&i.Overdue,
		&i.OldestEnqueuedAt,
	)
	return i, err
}

const getMediaOrphanSweepCursor = `-- name: GetMediaOrphanSweepCursor :one
SELECT cursor
FROM privacy_sweep_state
WHERE name = 'media-orphan-sweep'
`

func (q *Queries) GetMediaOrphanSweepCursor(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getMediaOrphanSweepCursor)
	var cursor string
	err := row.Scan(&cursor)
	return cursor, err
}

const markClaimedMediaDeletionOverdue = `-- name: MarkClaimedMediaDeletionOverdue :one
WITH marked AS (
    UPDATE media_deletion_jobs AS job
    SET overdue_at = $1::timestamptz
    WHERE job.id = $2::uuid
      AND job.lease_id = $3::uuid
      AND job.completed_at IS NULL
      AND job.overdue_at IS NULL
      AND job.enqueued_at <= $4::timestamptz
    RETURNING job.id
), audited AS (
    INSERT INTO lifecycle_audit_events (kind, occurred_at, media_job_id)
    SELECT 'media_deletion_overdue', $1::timestamptz, marked.id
    FROM marked
    ON CONFLICT (media_job_id, kind) DO NOTHING
    RETURNING id
)
SELECT EXISTS (SELECT 1 FROM marked) AS marked
`

type MarkClaimedMediaDeletionOverdueParams struct {
	Now     time.Time
	ID      uuid.UUID
	LeaseID uuid.UUID
	Cutoff  time.Time
}

func (q *Queries) MarkClaimedMediaDeletionOverdue(ctx context.Context, arg MarkClaimedMediaDeletionOverdueParams) (bool, error) {
	row := q.db.QueryRow(ctx, markClaimedMediaDeletionOverdue,
		arg.Now,
		arg.ID,
		arg.LeaseID,
		arg.Cutoff,
	)
	var marked bool
	err := row.Scan(&marked)
	return marked, err
}

const markMediaDeletionOverduePage = `-- name: MarkMediaDeletionOverduePage :one
WITH candidates AS MATERIALIZED (
    SELECT job.id
    FROM media_deletion_jobs AS job
    WHERE job.completed_at IS NULL
      AND job.overdue_at IS NULL
      AND job.enqueued_at <= $1::timestamptz
    ORDER BY job.enqueued_at, job.id
    LIMIT LEAST($2::int, 200)
    FOR UPDATE SKIP LOCKED
), marked AS (
    UPDATE media_deletion_jobs AS job
    SET overdue_at = $3::timestamptz
    FROM candidates
    WHERE job.id = candidates.id
    RETURNING job.id
), audited AS (
    INSERT INTO lifecycle_audit_events (kind, occurred_at, media_job_id)
    SELECT 'media_deletion_overdue', $3::timestamptz, marked.id
    FROM marked
    ON CONFLICT (media_job_id, kind) DO NOTHING
    RETURNING id
)
SELECT count(*)::bigint AS marked FROM marked
`

type MarkMediaDeletionOverduePageParams struct {
	Cutoff  time.Time
	MaxRows int32
	Now     time.Time
}

func (q *Queries) MarkMediaDeletionOverduePage(ctx context.Context, arg MarkMediaDeletionOverduePageParams) (int64, error) {
	row := q.db.QueryRow(ctx, markMediaDeletionOverduePage, arg.Cutoff, arg.MaxRows, arg.Now)
	var marked int64
	err := row.Scan(&marked)
	return marked, err
}

const mediaObjectHasLiveReference = `-- name: MediaObjectHasLiveReference :one
SELECT EXISTS (
    SELECT 1
    FROM resumes
    WHERE personal_details -> 'photo' ->> 'key' = $1::text
) AS live
`

func (q *Queries) MediaObjectHasLiveReference(ctx context.Context, objectKey string) (bool, error) {
	row := q.db.QueryRow(ctx, mediaObjectHasLiveReference, objectKey)
	var live bool
	err := row.Scan(&live)
	return live, err
}

const requeueClaimedMediaDeletion = `-- name: RequeueClaimedMediaDeletion :execrows
UPDATE media_deletion_jobs
SET next_attempt_at = $1::timestamptz,
    lease_id = NULL,
    lease_expires_at = NULL
WHERE id = $2::uuid
  AND lease_id = $3::uuid
  AND completed_at IS NULL
`

type RequeueClaimedMediaDeletionParams struct {
	NextAttemptAt time.Time
	ID            uuid.UUID
	LeaseID       uuid.UUID
}

func (q *Queries) RequeueClaimedMediaDeletion(ctx context.Context, arg RequeueClaimedMediaDeletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueClaimedMediaDeletion, arg.NextAttemptAt, arg.ID, arg.LeaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveMediaOrphanSweepCursor = `-- name: SaveMediaOrphanSweepCursor :execrows
UPDATE privacy_sweep_state
SET cursor = $1::text,
    updated_at = $2::timestamptz
WHERE name = 'media-orphan-sweep'
`

type SaveMediaOrphanSweepCursorParams struct {
	Cursor string
	Now    time.Time
}

func (q *Queries) SaveMediaOrphanSweepCursor(ctx context.Context, arg SaveMediaOrphanSweepCursorParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveMediaOrphanSweepCursor, arg.Cursor, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
