// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthEmailJob struct {
	ID             uuid.UUID
	Kind           string
	State          string
	RegistrationID *uuid.UUID
	ResetTokenID   *uuid.UUID
	UserID         *uuid.UUID
	TokenDigest    []byte
	KeyID          *string
	Nonce          []byte
	Ciphertext     []byte
	Attempts       int32
	CreatedAt      time.Time
	ExpiresAt      time.Time
	NextAttemptAt  *time.Time
	LeaseOwner     *string
	LeaseExpiresAt *time.Time
	SentAt         *time.Time
	TerminalAt     *time.Time
}

type IdempotencyRecord struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Route           string
	IdempotencyKey  uuid.UUID
	RequestHash     []byte
	ResponseStatus  int32
	ResponseBody    json.RawMessage
	CreatedAt       time.Time
	ExpiresAt       time.Time
	ResponseHeaders json.RawMessage
}

type IdempotencyUsage struct {
	UserID          uuid.UUID
	RetainedRecords int64
	StoredBytes     int64
}

type Identity struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	CreatedAt      time.Time
}

type LifecycleAuditEvent struct {
	ID         uuid.UUID
	Kind       string
	OccurredAt time.Time
	MediaJobID *uuid.UUID
}

type MediaDeletionJob struct {
	ID             uuid.UUID
	ResumeID       uuid.UUID
	ObjectKey      string
	EnqueuedAt     time.Time
	NextAttemptAt  time.Time
	AttemptCount   int32
	LeaseID        *uuid.UUID
	LeaseExpiresAt *time.Time
	CompletedAt    *time.Time
	OverdueAt      *time.Time
	Outcome        *string
}

type OAuthAuthorizationCode struct {
	ID             uuid.UUID
	CodeDigest     []byte
	ClientID       uuid.UUID
	UserID         uuid.UUID
	Scopes         string
	CodeChallenge  string
	RedirectURI    string
	CreatedAt      time.Time
	ExpiresAt      time.Time
	ConsumedAt     *time.Time
	IssuedFamilyID *uuid.UUID
}

type OAuthClient struct {
	ID           uuid.UUID
	ClientName   string
	RedirectURIs json.RawMessage
	CreatedAt    time.Time
	LastUsedAt   time.Time
}

type OAuthGrant struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ClientID  uuid.UUID
	Scopes    string
	CreatedAt time.Time
	RevokedAt *time.Time
}

type OAuthToken struct {
	ID              uuid.UUID
	TokenDigest     []byte
	Kind            string
	FamilyID        uuid.UUID
	RotatedFrom     *uuid.UUID
	ClientID        uuid.UUID
	UserID          uuid.UUID
	GrantID         uuid.UUID
	CreatedAt       time.Time
	ExpiresAt       time.Time
	FamilyExpiresAt time.Time
	RevokedAt       *time.Time
	SupersededAt    *time.Time
	LastUsedAt      *time.Time
}

type OAuthTransaction struct {
	ID            uuid.UUID
	HandleHash    []byte
	Provider      string
	Purpose       string
	LinkingUserID *uuid.UUID
	State         string
	PKCEVerifier  string
	Nonce         *string
	RedirectURI   string
	CreatedAt     time.Time
	ExpiresAt     time.Time
	ConsumedAt    *time.Time
	ReturnPath    string
}

type PasswordCredential struct {
	UserID      uuid.UUID
	EncodedHash []byte
	CreatedAt   time.Time
	ChangedAt   time.Time
}

type PasswordRegistration struct {
	ID          uuid.UUID
	Email       string
	Name        string
	EncodedHash []byte
	TokenDigest []byte
	CreatedAt   time.Time
	ExpiresAt   time.Time
}

type PasswordResetToken struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	TokenDigest []byte
	CreatedAt   time.Time
	ExpiresAt   time.Time
}

type PrivacySweepState struct {
	Name      string
	Cursor    string
	UpdatedAt time.Time
}

type PublicState struct {
	Singleton           bool
	DiscoveryGeneration int64
}

type PublicTransition struct {
	TransitionID              uuid.UUID
	InitiatorReplicaID        uuid.UUID
	InitiatorInstanceID       string
	InitiatorReleaseDigest    string
	Operation                 string
	State                     string
	CreatedAt                 time.Time
	DeadlineAt                time.Time
	TerminalAt                *time.Time
	TargetDigest              []byte
	TerminalErrorCode         *string
	RecoveryFencingEvidenceID *string
}

type PublicTransitionAck struct {
	TransitionID     uuid.UUID
	ReplicaID        uuid.UUID
	TargetDigest     []byte
	AckedAt          time.Time
	LocalResult      string
	RevokingCount    int32
	NonDrainingCount int32
}

type PublicTransitionReplica struct {
	TransitionID  uuid.UUID
	ReplicaID     uuid.UUID
	SnapshotState string
	InstanceID    string
	ReleaseDigest string
	TargetDigest  []byte
}

type PublicTransitionTarget struct {
	TransitionID       uuid.UUID
	Ordinal            int32
	Kind               string
	ResumeID           *uuid.UUID
	ExpectedGeneration int64
	Class              string
	ResultKind         *string
	ResultGeneration   *int64
	ResultRecordedAt   *time.Time
}

type Resume struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Title           string
	Slug            *string
	Live            bool
	DownloadEnabled bool
	SEOGeoEnabled   bool
	SchemaVersion   int32
	Revision        int64
	Lng             *string
	PersonalDetails json.RawMessage
	Content         json.RawMessage
	Customization   json.RawMessage
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type RuntimeCapacity struct {
	Singleton             bool
	DesiredReplicas       int16
	Generation            int64
	ControllerGeneration  int64
	ControllerOperationID string
	AdmissionEnabled      bool
	LifecyclePhase        string
	UpdatedAt             time.Time
	UpdatedBy             string
}

type RuntimeFencingProof struct {
	ReplicaID            uuid.UUID
	InstanceID           string
	ReleaseDigest        string
	Adapter              string
	EvidenceID           string
	RequestedAt          time.Time
	ObservedTerminatedAt time.Time
	RecordedAt           time.Time
	ObservedState        string
}

type RuntimeLeaveReceipt struct {
	ReplicaID             uuid.UUID
	InstanceID            string
	ReleaseDigest         string
	ControllerGeneration  int64
	OperationID           string
	JoinedTransitionCount int32
	JoinedClaimCount      int32
	RecordedAt            time.Time
}

type RuntimeLifecycleOperation struct {
	OperationID  string
	WorkflowKind string
	CreatedAt    time.Time
}

type RuntimeLifecycleOperationStep struct {
	OperationID               string
	Action                    string
	WorkflowKind              string
	ExpectedGeneration        int64
	ResultGeneration          int64
	ArgumentDigest            []byte
	ResultDigest              []byte
	ArgumentReplacedReplicaID *uuid.UUID
	ResultKind                string
	ReplicaID                 *uuid.UUID
	ReplicaKind               *string
	ReplicaState              *string
	DesiredReplicas           pgtype.Int2
	ActiveServingReplicas     pgtype.Int2
	ActiveMaintenanceReplicas pgtype.Int2
	Partition1Enabled         pgtype.Bool
	Partition2Enabled         pgtype.Bool
	CapacityGeneration        int64
	ControllerGeneration      int64
	ControllerOperationID     string
	AdmissionEnabled          bool
	LifecyclePhase            string
	WriteGate                 *string
	WriteGeneration           *int64
	RecordedAt                time.Time
}

type RuntimeReplica struct {
	ReplicaID              uuid.UUID
	ReplicaKind            string
	InstanceID             string
	ContainerInstanceArn   string
	CaddyTaskArn           string
	GoTaskArn              string
	NuxtTaskArn            string
	ReleaseDigest          string
	State                  string
	JoinedAt               time.Time
	JoinReadyAt            *time.Time
	ActivatedAt            *time.Time
	DrainingAt             *time.Time
	LeftAt                 *time.Time
	TerminationRequestedAt *time.Time
	FencedAt               *time.Time
}

type RuntimeReplicaTask struct {
	TaskArn   string
	ReplicaID uuid.UUID
	TaskRole  string
}

type RuntimeTerminationIntent struct {
	ReplicaID     uuid.UUID
	InstanceID    string
	ReleaseDigest string
	RequestID     string
	Reason        string
	RequestedAt   time.Time
}

type RuntimeWriteState struct {
	Singleton                  bool
	Generation                 int64
	WriteGate                  string
	LastWriteAt                time.Time
	LastAcceptedWriterAt       time.Time
	LastWriterKind             string
	LastWriterOperationID      string
	UpdatedAt                  time.Time
	MigratorEnforcementVersion int16
	MigrationHistoryOwner      string
}

type Session struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	TokenHash          []byte
	CSRFSecret         []byte
	CreatedAt          time.Time
	LastSeenAt         time.Time
	ReauthenticatedAt  time.Time
	AbsoluteExpiresAt  time.Time
	RotationGraceUntil *time.Time
	RevokedAt          *time.Time
	UA                 *string
	IP                 *netip.Addr
	RotatedFrom        *uuid.UUID
}

type SharedAdmissionAttempt struct {
	AttemptID       uuid.UUID
	PolicyID        string
	ClientID        uuid.UUID
	BucketKind      string
	Partition       pgtype.Int2
	KeyDigest       []byte
	WindowStartedAt time.Time
	ReservedAt      time.Time
	EffectiveUntil  time.Time
	State           string
	Outcome         *string
	TerminalReason  *string
	TerminalAt      *time.Time
}

type SharedClaimPolicy struct {
	PolicyID     string
	ScopeKind    string
	RunningLimit int32
	WaitingLimit int32
	QueueEnabled bool
	DeadlineMode string
}

type SharedClaimRequest struct {
	ClaimID       uuid.UUID
	PolicyID      string
	ReplicaID     uuid.UUID
	WorkID        *uuid.UUID
	State         string
	AdmittedAt    time.Time
	DeadlineAt    *time.Time
	ReleasedAt    *time.Time
	ReleaseReason *string
	ScopeCount    int16
	RequestDigest []byte
}

type SharedClaimScope struct {
	ClaimID           uuid.UUID
	RequestOrdinal    int16
	PolicyID          string
	ScopeKind         string
	ScopeDigest       []byte
	AllocationOrdinal int64
	State             string
}

type SharedClaimScopeSummary struct {
	PolicyID     string
	ScopeKind    string
	ScopeDigest  []byte
	RunningCount int32
	WaitingCount int32
	NextOrdinal  int64
	UpdatedAt    time.Time
}

type SharedPolicyClock struct {
	PolicyID     string
	HighWaterAt  time.Time
	LastRawAt    time.Time
	AnomalyCount int64
}

type SharedRateBucket struct {
	PolicyID        string
	KeyDigest       []byte
	Partition       int16
	Algorithm       string
	LastSeen        time.Time
	TokenNumerator  *int64
	RefillAt        *time.Time
	WindowStartedAt *time.Time
	Count           *int32
	RollingEvents   []time.Time
}

type SharedRateOverflow struct {
	PolicyID        string
	Algorithm       string
	LastSeen        time.Time
	TokenNumerator  *int64
	RefillAt        *time.Time
	WindowStartedAt *time.Time
	Count           *int32
	RollingEvents   []time.Time
}

type SharedRatePartition struct {
	PolicyID           string
	Partition          int16
	Enabled            bool
	CapacityGeneration int64
	OperationID        string
	ActiveKeys         int32
	UpdatedAt          time.Time
}

type SharedRatePolicy struct {
	PolicyID                 string
	Algorithm                string
	Capacity                 int32
	WindowMicroseconds       int64
	AllowSuccessClear        bool
	DeniedAttemptAddsDebt    bool
	OrdinaryIdleMicroseconds int64
	MaxKeysPerPartition      int32
}

type SharedRatePolicyKeyShape struct {
	PolicyID string
	KeyShape string
}

type SlugTombstone struct {
	ID               uuid.UUID
	Slug             string
	ReleasedByUserID *uuid.UUID
	ReleasedAt       time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Name      string
	AvatarKey *string
	CreatedAt time.Time
	UpdatedAt time.Time
}
