// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type IdempotencyRecord struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Route           string
	IdempotencyKey  uuid.UUID
	RequestHash     []byte
	ResponseStatus  int32
	ResponseBody    json.RawMessage
	CreatedAt       time.Time
	ExpiresAt       time.Time
	ResponseHeaders json.RawMessage
}

type IdempotencyUsage struct {
	UserID          uuid.UUID
	RetainedRecords int64
	StoredBytes     int64
}

type Identity struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	CreatedAt      time.Time
}

type MediaDeletionJob struct {
	ID            uuid.UUID
	ResumeID      uuid.UUID
	ObjectKey     string
	EnqueuedAt    time.Time
	NextAttemptAt time.Time
	AttemptCount  int32
}

type OAuthTransaction struct {
	ID            uuid.UUID
	HandleHash    []byte
	Provider      string
	Purpose       string
	LinkingUserID *uuid.UUID
	State         string
	PKCEVerifier  string
	Nonce         *string
	RedirectURI   string
	CreatedAt     time.Time
	ExpiresAt     time.Time
	ConsumedAt    *time.Time
}

type Resume struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Title           string
	Slug            *string
	Live            bool
	DownloadEnabled bool
	SEOGeoEnabled   bool
	SchemaVersion   int32
	Revision        int64
	Lng             *string
	PersonalDetails json.RawMessage
	Content         json.RawMessage
	Customization   json.RawMessage
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Session struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	TokenHash          []byte
	CSRFSecret         []byte
	CreatedAt          time.Time
	LastSeenAt         time.Time
	ReauthenticatedAt  time.Time
	AbsoluteExpiresAt  time.Time
	RotationGraceUntil *time.Time
	RevokedAt          *time.Time
	UA                 *string
	IP                 *netip.Addr
	RotatedFrom        *uuid.UUID
}

type SlugTombstone struct {
	ID               uuid.UUID
	Slug             string
	ReleasedByUserID *uuid.UUID
	ReleasedAt       time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Name      string
	AvatarKey *string
	CreatedAt time.Time
	UpdatedAt time.Time
}
