// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preview_cards.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLiveResumeByID = `-- name: GetLiveResumeByID :one
SELECT id, user_id, title, slug, live, download_enabled, seo_geo_enabled, schema_version, revision, lng, personal_details, content, customization, created_at, updated_at, public_title, favicon_emoji FROM resumes
WHERE id = $1 AND live = true
`

func (q *Queries) GetLiveResumeByID(ctx context.Context, id uuid.UUID) (Resume, error) {
	row := q.db.QueryRow(ctx, getLiveResumeByID, id)
	var i Resume
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.Live,
		&i.DownloadEnabled,
		&i.SEOGeoEnabled,
		&i.SchemaVersion,
		&i.Revision,
		&i.Lng,
		&i.PersonalDetails,
		&i.Content,
		&i.Customization,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicTitle,
		&i.FaviconEmoji,
	)
	return i, err
}

const getResumePreviewCard = `-- name: GetResumePreviewCard :one
SELECT version, png FROM resume_preview_cards
WHERE resume_id = $1
`

type GetResumePreviewCardRow struct {
	Version string
	PNG     []byte
}

// A stored card is derived data (ADR 0055); every public read passes the
// live-state gate before it reads one.
func (q *Queries) GetResumePreviewCard(ctx context.Context, resumeID uuid.UUID) (GetResumePreviewCardRow, error) {
	row := q.db.QueryRow(ctx, getResumePreviewCard, resumeID)
	var i GetResumePreviewCardRow
	err := row.Scan(&i.Version, &i.PNG)
	return i, err
}

const listLiveResumePreviewCardVersions = `-- name: ListLiveResumePreviewCardVersions :many
SELECT r.id, c.version AS card_version
FROM resumes r
LEFT JOIN resume_preview_cards c ON c.resume_id = r.id
WHERE r.live = true
ORDER BY r.id
`

type ListLiveResumePreviewCardVersionsRow struct {
	ID          uuid.UUID
	CardVersion *string
}

// Every live resume and the version of its stored card, NULL when none.
func (q *Queries) ListLiveResumePreviewCardVersions(ctx context.Context) ([]ListLiveResumePreviewCardVersionsRow, error) {
	rows, err := q.db.Query(ctx, listLiveResumePreviewCardVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveResumePreviewCardVersionsRow
	for rows.Next() {
		var i ListLiveResumePreviewCardVersionsRow
		if err := rows.Scan(&i.ID, &i.CardVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockResumeForPreviewCard = `-- name: LockResumeForPreviewCard :one
SELECT id, user_id, title, slug, live, download_enabled, seo_geo_enabled, schema_version, revision, lng, personal_details, content, customization, created_at, updated_at, public_title, favicon_emoji FROM resumes
WHERE id = $1
FOR SHARE
`

// FOR SHARE makes a card store wait for, or block, an unpublish, rename, or
// delete of the same resume, since those lock the row for update. The row
// returned is the latest committed one, so the caller recomputes the card
// version from it before it writes.
func (q *Queries) LockResumeForPreviewCard(ctx context.Context, id uuid.UUID) (Resume, error) {
	row := q.db.QueryRow(ctx, lockResumeForPreviewCard, id)
	var i Resume
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.Live,
		&i.DownloadEnabled,
		&i.SEOGeoEnabled,
		&i.SchemaVersion,
		&i.Revision,
		&i.Lng,
		&i.PersonalDetails,
		&i.Content,
		&i.Customization,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicTitle,
		&i.FaviconEmoji,
	)
	return i, err
}

const upsertResumePreviewCard = `-- name: UpsertResumePreviewCard :exec
INSERT INTO resume_preview_cards (resume_id, version, png, rendered_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (resume_id) DO UPDATE
SET version = EXCLUDED.version, png = EXCLUDED.png, rendered_at = EXCLUDED.rendered_at
`

type UpsertResumePreviewCardParams struct {
	ResumeID   uuid.UUID
	Version    string
	PNG        []byte
	RenderedAt time.Time
}

func (q *Queries) UpsertResumePreviewCard(ctx context.Context, arg UpsertResumePreviewCardParams) error {
	_, err := q.db.Exec(ctx, upsertResumePreviewCard,
		arg.ResumeID,
		arg.Version,
		arg.PNG,
		arg.RenderedAt,
	)
	return err
}
