// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: privacy_retention.sql

package store

import (
	"context"
	"time"
)

const deleteCompletedMediaJobsPage = `-- name: DeleteCompletedMediaJobsPage :execrows
WITH candidates AS MATERIALIZED (
    SELECT id
    FROM media_deletion_jobs
    WHERE completed_at IS NOT NULL
      AND completed_at <= $1::timestamptz
    ORDER BY completed_at, id
    LIMIT LEAST($2::int, 1000)
    FOR UPDATE SKIP LOCKED
)
DELETE FROM media_deletion_jobs AS job
USING candidates
WHERE job.id = candidates.id
`

type DeleteCompletedMediaJobsPageParams struct {
	Cutoff    time.Time
	LimitRows int32
}

func (q *Queries) DeleteCompletedMediaJobsPage(ctx context.Context, arg DeleteCompletedMediaJobsPageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompletedMediaJobsPage, arg.Cutoff, arg.LimitRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLifecycleAuditPage = `-- name: DeleteLifecycleAuditPage :execrows
WITH candidates AS MATERIALIZED (
    SELECT id
    FROM lifecycle_audit_events
    WHERE occurred_at <= $1::timestamptz
    ORDER BY occurred_at, id
    LIMIT LEAST($2::int, 1000)
    FOR UPDATE SKIP LOCKED
)
DELETE FROM lifecycle_audit_events AS event
USING candidates
WHERE event.id = candidates.id
`

type DeleteLifecycleAuditPageParams struct {
	Cutoff    time.Time
	LimitRows int32
}

func (q *Queries) DeleteLifecycleAuditPage(ctx context.Context, arg DeleteLifecycleAuditPageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLifecycleAuditPage, arg.Cutoff, arg.LimitRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireIdempotencyPage = `-- name: ExpireIdempotencyPage :one
WITH candidate_users AS MATERIALIZED (
    SELECT owner.id
    FROM users AS owner
    JOIN LATERAL (
        SELECT record.expires_at, record.id
        FROM idempotency_records AS record
        WHERE record.user_id = owner.id
          AND record.expires_at <= $1::timestamptz
        ORDER BY record.expires_at, record.id
        LIMIT 1
    ) AS oldest ON true
    ORDER BY oldest.expires_at, oldest.id, owner.id
    LIMIT LEAST($2::int, 1000)
    FOR UPDATE OF owner SKIP LOCKED
), doomed AS MATERIALIZED (
    SELECT record.id, record.user_id
    FROM idempotency_records AS record
    JOIN candidate_users AS owner ON owner.id = record.user_id
    WHERE record.expires_at <= $1::timestamptz
    ORDER BY record.expires_at, record.id
    LIMIT LEAST($2::int, 1000)
    FOR UPDATE OF record SKIP LOCKED
), deleted AS (
    DELETE FROM idempotency_records AS record
    USING doomed
    WHERE record.id = doomed.id
    RETURNING record.user_id, record.response_body, record.response_headers
), per_user AS MATERIALIZED (
    SELECT user_id,
           count(*)::bigint AS deleted_records,
           sum(octet_length(response_body::text) +
               octet_length(response_headers::text))::bigint AS deleted_bytes
    FROM deleted
    GROUP BY user_id
), released AS (
    UPDATE idempotency_usage AS usage
    SET retained_records = usage.retained_records - per_user.deleted_records,
        stored_bytes = usage.stored_bytes - per_user.deleted_bytes
    FROM per_user
    WHERE usage.user_id = per_user.user_id
    RETURNING usage.user_id
)
SELECT COALESCE((SELECT sum(deleted_records) FROM per_user), 0)::bigint AS deleted_records,
       COALESCE((SELECT sum(deleted_bytes) FROM per_user), 0)::bigint AS deleted_bytes,
       COALESCE((SELECT sum(per_user.deleted_records)
                 FROM per_user JOIN released USING (user_id)), 0)::bigint AS released_records,
       COALESCE((SELECT sum(per_user.deleted_bytes)
                 FROM per_user JOIN released USING (user_id)), 0)::bigint AS released_bytes
`

type ExpireIdempotencyPageParams struct {
	Cutoff    time.Time
	LimitRows int32
}

type ExpireIdempotencyPageRow struct {
	DeletedRecords  int64
	DeletedBytes    int64
	ReleasedRecords int64
	ReleasedBytes   int64
}

// Lock users before replay rows and usage counters, matching every resume
// writer. SKIP LOCKED lets inactive users progress past a busy account.
func (q *Queries) ExpireIdempotencyPage(ctx context.Context, arg ExpireIdempotencyPageParams) (ExpireIdempotencyPageRow, error) {
	row := q.db.QueryRow(ctx, expireIdempotencyPage, arg.Cutoff, arg.LimitRows)
	var i ExpireIdempotencyPageRow
	err := row.Scan(
		&i.DeletedRecords,
		&i.DeletedBytes,
		&i.ReleasedRecords,
		&i.ReleasedBytes,
	)
	return i, err
}

const getCompletedMediaJobsBacklog = `-- name: GetCompletedMediaJobsBacklog :one
SELECT count(*)::bigint AS backlog,
       (COALESCE(floor(extract(epoch FROM
           greatest($1::timestamptz - min(completed_at), interval '0 seconds'))), 0))::bigint
           AS oldest_age_seconds
FROM media_deletion_jobs
WHERE completed_at IS NOT NULL
  AND completed_at <= $2::timestamptz
`

type GetCompletedMediaJobsBacklogParams struct {
	Now    time.Time
	Cutoff time.Time
}

type GetCompletedMediaJobsBacklogRow struct {
	Backlog          int64
	OldestAgeSeconds int64
}

func (q *Queries) GetCompletedMediaJobsBacklog(ctx context.Context, arg GetCompletedMediaJobsBacklogParams) (GetCompletedMediaJobsBacklogRow, error) {
	row := q.db.QueryRow(ctx, getCompletedMediaJobsBacklog, arg.Now, arg.Cutoff)
	var i GetCompletedMediaJobsBacklogRow
	err := row.Scan(&i.Backlog, &i.OldestAgeSeconds)
	return i, err
}

const getIdempotencyExpiryBacklog = `-- name: GetIdempotencyExpiryBacklog :one
SELECT count(*)::bigint AS backlog,
       (COALESCE(floor(extract(epoch FROM
           greatest($1::timestamptz - min(expires_at), interval '0 seconds'))), 0))::bigint
           AS oldest_age_seconds
FROM idempotency_records
WHERE expires_at <= $1::timestamptz
`

type GetIdempotencyExpiryBacklogRow struct {
	Backlog          int64
	OldestAgeSeconds int64
}

func (q *Queries) GetIdempotencyExpiryBacklog(ctx context.Context, cutoff time.Time) (GetIdempotencyExpiryBacklogRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyExpiryBacklog, cutoff)
	var i GetIdempotencyExpiryBacklogRow
	err := row.Scan(&i.Backlog, &i.OldestAgeSeconds)
	return i, err
}

const getLifecycleAuditBacklog = `-- name: GetLifecycleAuditBacklog :one
SELECT count(*)::bigint AS backlog,
       (COALESCE(floor(extract(epoch FROM
           greatest($1::timestamptz - min(occurred_at), interval '0 seconds'))), 0))::bigint
           AS oldest_age_seconds
FROM lifecycle_audit_events
WHERE occurred_at <= $2::timestamptz
`

type GetLifecycleAuditBacklogParams struct {
	Now    time.Time
	Cutoff time.Time
}

type GetLifecycleAuditBacklogRow struct {
	Backlog          int64
	OldestAgeSeconds int64
}

func (q *Queries) GetLifecycleAuditBacklog(ctx context.Context, arg GetLifecycleAuditBacklogParams) (GetLifecycleAuditBacklogRow, error) {
	row := q.db.QueryRow(ctx, getLifecycleAuditBacklog, arg.Now, arg.Cutoff)
	var i GetLifecycleAuditBacklogRow
	err := row.Scan(&i.Backlog, &i.OldestAgeSeconds)
	return i, err
}

const getSessionMetadataBacklog = `-- name: GetSessionMetadataBacklog :one
SELECT count(*)::bigint AS backlog,
       (COALESCE(floor(extract(epoch FROM
           greatest($1::timestamptz - min(created_at), interval '0 seconds'))), 0))::bigint
           AS oldest_age_seconds
FROM sessions
WHERE created_at <= $2::timestamptz
  AND (ua IS NOT NULL OR ip IS NOT NULL)
`

type GetSessionMetadataBacklogParams struct {
	Now    time.Time
	Cutoff time.Time
}

type GetSessionMetadataBacklogRow struct {
	Backlog          int64
	OldestAgeSeconds int64
}

func (q *Queries) GetSessionMetadataBacklog(ctx context.Context, arg GetSessionMetadataBacklogParams) (GetSessionMetadataBacklogRow, error) {
	row := q.db.QueryRow(ctx, getSessionMetadataBacklog, arg.Now, arg.Cutoff)
	var i GetSessionMetadataBacklogRow
	err := row.Scan(&i.Backlog, &i.OldestAgeSeconds)
	return i, err
}

const redactSessionMetadataPage = `-- name: RedactSessionMetadataPage :execrows
WITH candidates AS MATERIALIZED (
    SELECT id
    FROM sessions
    WHERE created_at <= $1::timestamptz
      AND (ua IS NOT NULL OR ip IS NOT NULL)
    ORDER BY created_at, id
    LIMIT LEAST($2::int, 1000)
    FOR UPDATE SKIP LOCKED
)
UPDATE sessions AS session
SET ua = NULL, ip = NULL
FROM candidates
WHERE session.id = candidates.id
`

type RedactSessionMetadataPageParams struct {
	Cutoff    time.Time
	LimitRows int32
}

func (q *Queries) RedactSessionMetadataPage(ctx context.Context, arg RedactSessionMetadataPageParams) (int64, error) {
	result, err := q.db.Exec(ctx, redactSessionMetadataPage, arg.Cutoff, arg.LimitRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tryLockIdempotencyExpirySweep = `-- name: TryLockIdempotencyExpirySweep :one

SELECT pg_try_advisory_lock(hashtextextended('aboutme.idempotency-expiry-sweep.v1', 0))
`

// Phase 8 privacy retention queries. Every mutation is bounded and ordered;
// command-level advisory locks are session locks held on a dedicated pooled
// connection for the whole run.
func (q *Queries) TryLockIdempotencyExpirySweep(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, tryLockIdempotencyExpirySweep)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}

const tryLockPrivacyRetentionSweep = `-- name: TryLockPrivacyRetentionSweep :one
SELECT pg_try_advisory_lock(hashtextextended('aboutme.privacy-retention-sweep.v1', 0))
`

func (q *Queries) TryLockPrivacyRetentionSweep(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, tryLockPrivacyRetentionSweep)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}

const unlockIdempotencyExpirySweep = `-- name: UnlockIdempotencyExpirySweep :one
SELECT pg_advisory_unlock(hashtextextended('aboutme.idempotency-expiry-sweep.v1', 0))
`

func (q *Queries) UnlockIdempotencyExpirySweep(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, unlockIdempotencyExpirySweep)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}

const unlockPrivacyRetentionSweep = `-- name: UnlockPrivacyRetentionSweep :one
SELECT pg_advisory_unlock(hashtextextended('aboutme.privacy-retention-sweep.v1', 0))
`

func (q *Queries) UnlockPrivacyRetentionSweep(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, unlockPrivacyRetentionSweep)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}
