// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const beginSessionRotation = `-- name: BeginSessionRotation :one
UPDATE sessions SET rotation_grace_until = $2
WHERE id = $1 AND rotation_grace_until IS NULL AND revoked_at IS NULL
RETURNING id
`

type BeginSessionRotationParams struct {
	ID                 uuid.UUID
	RotationGraceUntil *time.Time
}

// Single-row conditional UPDATE that decides the >24h rotation winner: only
// a row that has neither already started rotating (rotation_grace_until
// still NULL) nor been revoked is claimed. Under concurrent callers racing
// the same session id, exactly one UPDATE affects a row (returns its id);
// every other caller's UPDATE affects zero rows and pgx reports
// pgx.ErrNoRows -- that caller lost the race and must not mint a second
// successor (see internal/auth.SessionManager.Authenticate).
func (q *Queries) BeginSessionRotation(ctx context.Context, arg BeginSessionRotationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, beginSessionRotation, arg.ID, arg.RotationGraceUntil)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const consumeOAuthTransaction = `-- name: ConsumeOAuthTransaction :one
UPDATE oauth_transactions
SET consumed_at = $2
WHERE handle_hash = $1 AND consumed_at IS NULL AND expires_at > $2
RETURNING id, handle_hash, provider, purpose, linking_user_id, state, pkce_verifier, nonce, redirect_uri, created_at, expires_at, consumed_at
`

type ConsumeOAuthTransactionParams struct {
	HandleHash []byte
	ConsumedAt *time.Time
}

// Atomically claims a transaction: only a row that is unexpired and not yet
// consumed (as of now, $2) is updated and returned. A handle that is
// unknown, expired, or already consumed matches no row, so the caller sees
// exactly one outcome (pgx.ErrNoRows) for all three cases -- see
// internal/auth.ErrTransactionInvalid's doc comment for why that collapse
// is deliberate. The provider-mismatch check (RFC 9700 mix-up defense)
// happens in Go, after this still consumes the row: an attacker replaying
// a valid handle against the wrong provider's callback burns the
// transaction just like any other outcome, so it can never be retried
// against the correct provider either.
func (q *Queries) ConsumeOAuthTransaction(ctx context.Context, arg ConsumeOAuthTransactionParams) (OAuthTransaction, error) {
	row := q.db.QueryRow(ctx, consumeOAuthTransaction, arg.HandleHash, arg.ConsumedAt)
	var i OAuthTransaction
	err := row.Scan(
		&i.ID,
		&i.HandleHash,
		&i.Provider,
		&i.Purpose,
		&i.LinkingUserID,
		&i.State,
		&i.PKCEVerifier,
		&i.Nonce,
		&i.RedirectURI,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO identities (user_id, provider, provider_user_id) VALUES ($1, $2, $3) RETURNING id, user_id, provider, provider_user_id, created_at
`

type CreateIdentityParams struct {
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
}

// internal/auth's login-resolution algorithm calls
// GetIdentityByProviderSubject first specifically to avoid racing
// identities_provider_subject_key's UNIQUE (provider, provider_user_id) in
// the common case; Task 10's link algorithm handles the
// already-claimed-by-another-user case explicitly instead of relying on
// this insert to fail.
func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity, arg.UserID, arg.Provider, arg.ProviderUserID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthTransaction = `-- name: CreateOAuthTransaction :one
INSERT INTO oauth_transactions (
    handle_hash, provider, purpose, linking_user_id, state, pkce_verifier, nonce, redirect_uri, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, handle_hash, provider, purpose, linking_user_id, state, pkce_verifier, nonce, redirect_uri, created_at, expires_at, consumed_at
`

type CreateOAuthTransactionParams struct {
	HandleHash    []byte
	Provider      string
	Purpose       string
	LinkingUserID *uuid.UUID
	State         string
	PKCEVerifier  string
	Nonce         *string
	RedirectURI   string
	ExpiresAt     time.Time
}

func (q *Queries) CreateOAuthTransaction(ctx context.Context, arg CreateOAuthTransactionParams) (OAuthTransaction, error) {
	row := q.db.QueryRow(ctx, createOAuthTransaction,
		arg.HandleHash,
		arg.Provider,
		arg.Purpose,
		arg.LinkingUserID,
		arg.State,
		arg.PKCEVerifier,
		arg.Nonce,
		arg.RedirectURI,
		arg.ExpiresAt,
	)
	var i OAuthTransaction
	err := row.Scan(
		&i.ID,
		&i.HandleHash,
		&i.Provider,
		&i.Purpose,
		&i.LinkingUserID,
		&i.State,
		&i.PKCEVerifier,
		&i.Nonce,
		&i.RedirectURI,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id, token_hash, csrf_secret, created_at, last_seen_at, reauthenticated_at, absolute_expires_at, ua, ip
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, token_hash, csrf_secret, created_at, last_seen_at, reauthenticated_at, absolute_expires_at, rotation_grace_until, revoked_at, ua, ip
`

type CreateSessionParams struct {
	UserID            uuid.UUID
	TokenHash         []byte
	CSRFSecret        []byte
	CreatedAt         time.Time
	LastSeenAt        time.Time
	ReauthenticatedAt time.Time
	AbsoluteExpiresAt time.Time
	UA                *string
	IP                *netip.Addr
}

// Always inserts a brand-new row -- used both by Issue (fixation defense: a
// login never reuses an existing session row) and by the >24h rotation
// winner's successor insert (internal/auth.SessionManager.Authenticate),
// which passes the predecessor's user_id, reauthenticated_at,
// absolute_expires_at, ua, and ip through unchanged so a rotation never
// extends absolute expiry or silently satisfies the recent-reauth gate.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.CSRFSecret,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ReauthenticatedAt,
		arg.AbsoluteExpiresAt,
		arg.UA,
		arg.IP,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CSRFSecret,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ReauthenticatedAt,
		&i.AbsoluteExpiresAt,
		&i.RotationGraceUntil,
		&i.RevokedAt,
		&i.UA,
		&i.IP,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, name, avatar_key) VALUES ($1, $2, $3) RETURNING id, email, name, avatar_key, created_at, updated_at
`

type CreateUserParams struct {
	Email     string
	Name      string
	AvatarKey *string
}

// Hand-written, sqlc-annotated queries (`-- name: X :one/:many/:exec`) that
// become type-safe Go methods in internal/store via `make generate`. See
// docs/specs/aboutme-design.md §3 "Schema management".
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.AvatarKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findImmediatePredecessorSession = `-- name: FindImmediatePredecessorSession :one
SELECT id, user_id, token_hash, csrf_secret, created_at, last_seen_at, reauthenticated_at, absolute_expires_at, rotation_grace_until, revoked_at, ua, ip FROM sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND rotation_grace_until = $2::timestamptz
`

type FindImmediatePredecessorSessionParams struct {
	UserID                uuid.UUID
	PredecessorGraceUntil time.Time
}

// Fix round 1, finding I2 / design owner ruling DD-C14: given a session
// that may itself be a rotation SUCCESSOR, finds the exact row it was
// rotated FROM, if that predecessor is still live (revoked_at IS NULL).
// Not a heuristic: session.go's tryRotate sets
// predecessor.rotation_grace_until = now + rotationGrace and
// successor.created_at = now from the SAME `now` value in the same
// function call, so predecessor.rotation_grace_until always equals
// successor.created_at + rotationGrace EXACTLY for a genuine
// predecessor/successor pair, and essentially never coincidentally for
// an unrelated row (rotation_grace_until is a random-offset instant, not
// a value any other write path in this schema ever produces). The caller
// computes successor.created_at + rotationGrace in Go (rotationGrace is
// session.go's own constant) and passes it as the single timestamp
// argument -- this exists specifically because RequireSession's
// context-based predecessor seam (ContextWithPredecessorSessionID) only
// covers the narrow case where the SAME request's own Authenticate call
// performs the rotation, which a CSRF-gated mutating endpoint can never
// observe in practice (RequireCSRF validates against the POST-rotation
// session, which a client cannot have a correct token for on its very
// first use) -- see task-9-report.md's fix-round-1 section for the full
// reasoning. user_id scopes the match to the caller's own lineage only,
// so a coincidental rotation_grace_until collision with a DIFFERENT
// user's session can never cross-match.
func (q *Queries) FindImmediatePredecessorSession(ctx context.Context, arg FindImmediatePredecessorSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, findImmediatePredecessorSession, arg.UserID, arg.PredecessorGraceUntil)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CSRFSecret,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ReauthenticatedAt,
		&i.AbsoluteExpiresAt,
		&i.RotationGraceUntil,
		&i.RevokedAt,
		&i.UA,
		&i.IP,
	)
	return i, err
}

const findImmediateSuccessorSession = `-- name: FindImmediateSuccessorSession :one
SELECT id, user_id, token_hash, csrf_secret, created_at, last_seen_at, reauthenticated_at, absolute_expires_at, rotation_grace_until, revoked_at, ua, ip FROM sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND created_at = $2::timestamptz
`

type FindImmediateSuccessorSessionParams struct {
	UserID             uuid.UUID
	SuccessorCreatedAt time.Time
}

// Fix round 2, finding DD-C14b (owner ruling, extends DD-C14): the exact
// mirror of FindImmediatePredecessorSession above, in the other
// direction. A rotation race-loser request (one that presents an old
// token still within ITS OWN grace window, after some OTHER request
// already won the rotation and minted a successor) authenticates AS THE
// PREDECESSOR -- Authenticate's `sess.RotationGraceUntil == nil` guard
// means it never re-attempts rotation for a row that's already rotating
// -- so a caller can hold a fully legitimate session (and its own,
// correct CSRF secret) for a row that is itself a predecessor with a
// live, unrevoked successor. Logging out (or revoking) that predecessor
// alone would leave the successor authenticating for its own full
// idle/absolute lifetime -- logout claiming success without actually
// ending the session. Given a session that may itself be a rotation
// PREDECESSOR (rotation_grace_until IS NOT NULL), finds the exact
// successor row it was rotated INTO, if that successor is still live
// (revoked_at IS NULL): the same exact (not heuristic) timing identity as
// the predecessor lookup, solved for the other variable --
// successor.created_at = predecessor.rotation_grace_until - rotationGrace
// -- computed in Go and passed as the single timestamp argument.
// user_id-scoped for the same cross-user-collision reasoning as
// FindImmediatePredecessorSession.
func (q *Queries) FindImmediateSuccessorSession(ctx context.Context, arg FindImmediateSuccessorSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, findImmediateSuccessorSession, arg.UserID, arg.SuccessorCreatedAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CSRFSecret,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ReauthenticatedAt,
		&i.AbsoluteExpiresAt,
		&i.RotationGraceUntil,
		&i.RevokedAt,
		&i.UA,
		&i.IP,
	)
	return i, err
}

const getIdentityByProviderSubject = `-- name: GetIdentityByProviderSubject :one
SELECT id, user_id, provider, provider_user_id, created_at FROM identities WHERE provider = $1 AND provider_user_id = $2
`

type GetIdentityByProviderSubjectParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetIdentityByProviderSubject(ctx context.Context, arg GetIdentityByProviderSubjectParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByProviderSubject, arg.Provider, arg.ProviderUserID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, token_hash, csrf_secret, created_at, last_seen_at, reauthenticated_at, absolute_expires_at, rotation_grace_until, revoked_at, ua, ip FROM sessions WHERE id = $1
`

// Fix round 2, finding DD-C14b: DELETE /sessions/{id}'s lineage sweep
// (sessions_handlers.go's revokeLineagePartners) needs the just-revoked
// TARGET session's own created_at/rotation_grace_until/user_id to look up
// its rotation lineage partner(s) -- RevokeSessionForUser only reports a
// row count, not the row itself, and the target is not always the
// caller's own current session (sess, already fully in hand from
// context), so a second read is unavoidable here. revoked_at is already
// set to non-NULL by the time this runs (it always runs strictly after a
// successful RevokeForUser), but every other column this caller needs
// (created_at, rotation_grace_until, user_id) is untouched by that
// UPDATE.
func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CSRFSecret,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ReauthenticatedAt,
		&i.AbsoluteExpiresAt,
		&i.RotationGraceUntil,
		&i.RevokedAt,
		&i.UA,
		&i.IP,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, csrf_secret, created_at, last_seen_at, reauthenticated_at, absolute_expires_at, rotation_grace_until, revoked_at, ua, ip FROM sessions WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CSRFSecret,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ReauthenticatedAt,
		&i.AbsoluteExpiresAt,
		&i.RotationGraceUntil,
		&i.RevokedAt,
		&i.UA,
		&i.IP,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, avatar_key, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, avatar_key, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIdentitiesByUserID = `-- name: ListIdentitiesByUserID :many
SELECT id, user_id, provider, provider_user_id, created_at FROM identities WHERE user_id = $1 ORDER BY created_at
`

// Task 9's GET /me: every provider identity linked to user_id, oldest
// first (created_at) so the first-ever linked provider always sorts
// first.
func (q *Queries) ListIdentitiesByUserID(ctx context.Context, userID uuid.UUID) ([]Identity, error) {
	rows, err := q.db.Query(ctx, listIdentitiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Identity
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSessionsForUser = `-- name: ListLiveSessionsForUser :many
SELECT id, user_id, token_hash, csrf_secret, created_at, last_seen_at, reauthenticated_at, absolute_expires_at, rotation_grace_until, revoked_at, ua, ip FROM sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND last_seen_at >= $2::timestamptz
  AND absolute_expires_at >= $3::timestamptz
  AND (rotation_grace_until IS NULL OR rotation_grace_until >= $3::timestamptz)
ORDER BY created_at DESC, id DESC
`

type ListLiveSessionsForUserParams struct {
	UserID     uuid.UUID
	IdleCutoff time.Time
	Now        time.Time
}

// Task 9's GET /sessions device list (design spec §3): every session
// belonging to user_id that is still LIVE as of now -- mirrors
// session.go's sessionDead exactly, predicate for predicate (fix round 1,
// finding I1: the original version only excluded revoked/grace-dead rows,
// silently listing idle-expired and absolute-expired sessions as live
// devices with no GC to ever remove them):
//
//   - not explicitly revoked (revoked_at IS NULL);
//   - not idle-expired: last_seen_at >= idle_cutoff, where idle_cutoff =
//     now - idleTimeout is computed in GO (session.go's own constant) and
//     passed as a query arg, never re-literalled as a SQL interval here;
//   - not absolute-expired: absolute_expires_at >= now;
//   - not a grace-dead rotation predecessor: rotation_grace_until IS NULL
//     OR rotation_grace_until >= now -- a session rotation has already
//     superseded keeps revoked_at NULL but has rotation_grace_until in
//     the past, and that row must never appear in the caller's own
//     device list, exactly like an explicitly revoked one, just not
//     marked that way.
//
// sqlc.arg(...)::timestamptz casts are explicit so both parameters' Go
// types are plain (non-pointer) time.Time regardless of the nullable
// columns they're compared against. Ordered newest-created first, with id
// as a deterministic tiebreaker for two rows created in the same instant
// (fix round 1, M4).
func (q *Queries) ListLiveSessionsForUser(ctx context.Context, arg ListLiveSessionsForUserParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listLiveSessionsForUser, arg.UserID, arg.IdleCutoff, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.CSRFSecret,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ReauthenticatedAt,
			&i.AbsoluteExpiresAt,
			&i.RotationGraceUntil,
			&i.RevokedAt,
			&i.UA,
			&i.IP,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessions = `-- name: RevokeAllSessions :execrows
UPDATE sessions SET revoked_at = $2 WHERE user_id = $1 AND revoked_at IS NULL
`

type RevokeAllSessionsParams struct {
	UserID    uuid.UUID
	RevokedAt *time.Time
}

// Logout-everywhere: revokes every one of the user's not-already-revoked
// sessions and reports how many rows that affected.
func (q *Queries) RevokeAllSessions(ctx context.Context, arg RevokeAllSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllSessions, arg.UserID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = $2 WHERE id = $1 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID        uuid.UUID
	RevokedAt *time.Time
}

// Idempotent: revoking an already-revoked (or nonexistent) session id
// affects zero rows rather than erroring, so logout/revoke can be retried
// safely. revoked_at is immediate and orthogonal to rotation_grace_until
// (design decision 1) -- this never touches that column.
func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevokedAt)
	return err
}

const revokeSessionForUser = `-- name: RevokeSessionForUser :execrows
UPDATE sessions
SET revoked_at = $3
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
  AND last_seen_at >= $4::timestamptz
  AND absolute_expires_at >= $5::timestamptz
  AND (rotation_grace_until IS NULL OR rotation_grace_until >= $5::timestamptz)
`

type RevokeSessionForUserParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	RevokedAt  *time.Time
	IdleCutoff time.Time
	Now        time.Time
}

// Ownership-checked counterpart to RevokeSession: only revokes id if it
// also belongs to user_id AND is still LIVE by the exact same predicates
// ListLiveSessionsForUser uses below (fix round 1, findings I1/M5): a
// session that is already idle-expired, absolute-expired, or a grace-dead
// rotation predecessor must revoke ZERO rows here too -- otherwise a
// caller could "revoke" a row GET /sessions' own device list already
// refuses to show them, which is exactly the self-inconsistency the
// review caught. Returns the affected row count so a caller can
// distinguish "revoked" (1) from "no such LIVE session for this user" (0)
// -- internal/auth.SessionManager.RevokeForUser's own caller (Task 9's
// DELETE /sessions/{id}) turns 0 into a 404, not a 403, so it never
// confirms whether the id exists for someone else, is merely dead, or
// belongs to another user.
func (q *Queries) RevokeSessionForUser(ctx context.Context, arg RevokeSessionForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionForUser,
		arg.ID,
		arg.UserID,
		arg.RevokedAt,
		arg.IdleCutoff,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchLastSeenAt = `-- name: TouchLastSeenAt :exec
UPDATE sessions SET last_seen_at = $2 WHERE id = $1
`

type TouchLastSeenAtParams struct {
	ID         uuid.UUID
	LastSeenAt time.Time
}

// Unconditional: callers throttle to at most once per lastSeenThrottle
// themselves (internal/auth.SessionManager.Authenticate) before issuing
// this write, so it is not itself CAS-guarded.
func (q *Queries) TouchLastSeenAt(ctx context.Context, arg TouchLastSeenAtParams) error {
	_, err := q.db.Exec(ctx, touchLastSeenAt, arg.ID, arg.LastSeenAt)
	return err
}

const touchReauthenticatedAt = `-- name: TouchReauthenticatedAt :exec
UPDATE sessions SET reauthenticated_at = $2 WHERE id = $1
`

type TouchReauthenticatedAtParams struct {
	ID                uuid.UUID
	ReauthenticatedAt time.Time
}

// Records that this session's lineage just completed a full OAuth login
// (design decision 2) -- called only after a real reauth round trip
// (internal/auth.SessionManager.TouchReauthenticated), never by rotation.
func (q *Queries) TouchReauthenticatedAt(ctx context.Context, arg TouchReauthenticatedAtParams) error {
	_, err := q.db.Exec(ctx, touchReauthenticatedAt, arg.ID, arg.ReauthenticatedAt)
	return err
}
