// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AdvanceDiscoveryGeneration(ctx context.Context) (int64, error)
	// This system backfill intentionally does not change revision or updated_at:
	// it persists the same projected document already served to readers. It is
	// not user-scoped. See docs/adr/0017-resume-document-versioning.md.
	// Fully named parameters distinguish the from/to schema versions. Both are
	// int32, and sqlc's positional naming would emit
	// `SchemaVersion` and `SchemaVersion_2`, neither carrying its direction.
	// A caller swapping them silently rewrites current rows back to the old
	// version. Named args make the pair unswappable at the call site.
	BackfillResumeDocumentCAS(ctx context.Context, arg BackfillResumeDocumentCASParams) (int64, error)
	// Single-row conditional UPDATE that decides the >24h rotation winner: only
	// a row that has neither already started rotating (rotation_grace_until
	// still NULL) nor been revoked is claimed. Under concurrent callers racing
	// the same session id, exactly one UPDATE affects a row (returns its id);
	// every other caller's UPDATE affects zero rows and pgx reports
	// pgx.ErrNoRows -- that caller lost the race and must not mint a second
	// successor (see internal/auth.SessionManager.Authenticate).
	BeginSessionRotation(ctx context.Context, arg BeginSessionRotationParams) (uuid.UUID, error)
	// Bounded SKIP LOCKED claim: atomically transitions at most limit due pending
	// jobs to leased, increments attempts, stamps the lease pair, and returns the
	// leased rows. Two concurrent claimers are disjoint because each claims a
	// distinct row under FOR UPDATE SKIP LOCKED.
	ClaimAuthEmailJobs(ctx context.Context, arg ClaimAuthEmailJobsParams) ([]AuthEmailJob, error)
	CleanupExpiredPasswordRegistrations(ctx context.Context, arg CleanupExpiredPasswordRegistrationsParams) (int64, error)
	CleanupExpiredPasswordResetTokens(ctx context.Context, arg CleanupExpiredPasswordResetTokensParams) (int64, error)
	// Sent/terminal jobs are retained for seven days of audit, then removed in a
	// bounded page, oldest outcome first.
	CleanupFinishedAuthEmailJobs(ctx context.Context, arg CleanupFinishedAuthEmailJobsParams) (int64, error)
	ConsumeExpiredSlugTombstone(ctx context.Context, arg ConsumeExpiredSlugTombstoneParams) (uuid.UUID, error)
	// Single-use consumption (M2). One conditional UPDATE both takes the row lock
	// and decides the winner: under two concurrent exchanges of the same code the
	// second blocks, re-evaluates the predicate after the first commits, matches
	// no row, and surfaces as pgx.ErrNoRows. Unknown, expired, and already-consumed
	// codes therefore collapse to that one outcome, so no caller can branch on the
	// reason. issued_family_id records the token family this exchange creates,
	// which is what a later replay revokes.
	ConsumeOAuthAuthorizationCode(ctx context.Context, arg ConsumeOAuthAuthorizationCodeParams) (OAuthAuthorizationCode, error)
	// Atomically claims a transaction: only a row that is unexpired and not yet
	// consumed (as of now, $2) is updated and returned. A handle that is
	// unknown, expired, or already consumed matches no row, so the caller sees
	// exactly one outcome (pgx.ErrNoRows) for all three cases -- see
	// internal/auth.ErrTransactionInvalid's doc comment for why that collapse
	// is deliberate. The provider-mismatch check (RFC 9700 mix-up defense)
	// happens in Go, after this still consumes the row: an attacker replaying
	// a valid handle against the wrong provider's callback burns the
	// transaction just like any other outcome, so it can never be retried
	// against the correct provider either.
	ConsumeOAuthTransaction(ctx context.Context, arg ConsumeOAuthTransactionParams) (OAuthTransaction, error)
	// The M5 live-grant cap check. Callers serialize it with the user row lock
	// (GetUserForUpdate) so two concurrent approvals cannot both read the same
	// pre-cap count.
	CountLiveOAuthGrantsForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountResumesForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	// New jobs always start pending with attempts 0 (DEFAULT). The caller provides
	// the job id (a UUIDv7 it generated) so the outbox AAD binds to the stored row's
	// id; the caller has already encrypted the payload and computed the exact expiry
	// before commit.
	CreateAuthEmailJob(ctx context.Context, arg CreateAuthEmailJobParams) (AuthEmailJob, error)
	// Returns PostgreSQL's normalized jsonb representation of the stored body
	// and approved headers plus the exact stored byte count, so the first
	// response and every replay use identical bytes and no caller recomputes
	// capacity accounting in Go.
	CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (CreateIdempotencyRecordRow, error)
	// The caller checks the provider subject first for the common case. The
	// database uniqueness constraint remains the concurrency backstop.
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error)
	// Code issue (M2). expires_at is computed here, not passed in, so the exact
	// 60-second TTL the table checks can never be missed by a caller. Only the
	// code's digest is stored; the raw code exists solely in the redirect the user
	// agent carries.
	CreateOAuthAuthorizationCode(ctx context.Context, arg CreateOAuthAuthorizationCodeParams) (OAuthAuthorizationCode, error)
	// ---------------------------------------------------------------------------
	// Phase PM: OAuth agent access — clients, authorization codes, grants, and
	// tokens. Storage is digest-only: no query here reads, writes, or returns raw
	// code or token material, and PKCE verifiers are never stored.
	//
	// Lock order is oauth_clients -> users -> oauth_grants ->
	// oauth_authorization_codes -> oauth_tokens. Every path that revokes a token
	// family first locks its grant row (GetOAuthGrantForUpdate), and every path
	// that mutates a client's rows first locks the client row
	// (GetOAuthClientForUpdate) -- which is also what makes the idle-client sweep
	// skip a client another transaction is consenting to.
	// ---------------------------------------------------------------------------
	// Dynamic client registration (M1). The primary key returned here IS the
	// public client_id; there is no secret. last_used_at starts at created_at so
	// the column is never NULL and the ordering check holds from the first row.
	CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OAuthClient, error)
	// The first token of a family, issued by a code exchange (M3). expires_at is
	// clamped to the family's own death so no token can outlive the family it
	// belongs to; the table's ordering check is the backstop for raw SQL.
	CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) (OAuthToken, error)
	CreateOAuthTransaction(ctx context.Context, arg CreateOAuthTransactionParams) (OAuthTransaction, error)
	CreatePasswordRegistration(ctx context.Context, arg CreatePasswordRegistrationParams) (PasswordRegistration, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateResume(ctx context.Context, arg CreateResumeParams) (Resume, error)
	// Always inserts a brand-new row -- used both by Issue (fixation defense: a
	// login never reuses an existing session row) and by the >24h rotation
	// winner's successor insert (internal/auth.SessionManager.Authenticate),
	// which passes the predecessor's user_id, reauthenticated_at,
	// absolute_expires_at, ua, and ip through unchanged so a rotation never
	// extends absolute expiry or silently satisfies the recent-reauth gate.
	// rotated_from is NULL for a fresh login and contains the predecessor id
	// for a rotated successor. The partial unique index makes this an exact,
	// one-successor lineage link.
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Hand-written, sqlc-annotated queries (`-- name: X :one/:many/:exec`) that
	// become type-safe Go methods in internal/store via `make generate`.
	// Relational schema changes belong in apps/server/migrations; see
	// docs/design/data.md.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Deletes exactly this key's record if (and only if) it has expired, and
	// reports the counters to release — zero rows deleted still returns one
	// aggregate row of zeros.
	DeleteExpiredIdempotencyRecordForKey(ctx context.Context, arg DeleteExpiredIdempotencyRecordForKeyParams) (DeleteExpiredIdempotencyRecordForKeyRow, error)
	// The bounded request-path cleanup: at most limit_rows of the calling
	// user's expired records, deterministically oldest first by
	// (expires_at, id) on the composite index. FOR UPDATE SKIP LOCKED keeps
	// concurrent cleanup bounded and deadlock-free. Always returns one
	// aggregate row, even when nothing was deleted.
	DeleteExpiredIdempotencyRecordsForUser(ctx context.Context, arg DeleteExpiredIdempotencyRecordsForUserParams) (DeleteExpiredIdempotencyRecordsForUserRow, error)
	// The P8-priv scheduled sweep's bounded page: oldest expired rows across
	// all users, grouped per user so the sweep can release each user's exact
	// counters (once per returned user) before committing that cleanup
	// transaction.
	DeleteExpiredIdempotencyRecordsGlobal(ctx context.Context, arg DeleteExpiredIdempotencyRecordsGlobalParams) ([]DeleteExpiredIdempotencyRecordsGlobalRow, error)
	// Bounded cleanup, oldest expiry first on oauth_authorization_codes_expires_at_idx.
	// expires_at alone is the predicate: a consumed code keeps its original expiry,
	// so consumed and abandoned rows leave on the same schedule, and a row is never
	// removed while ConsumeOAuthAuthorizationCode could still claim it.
	DeleteExpiredOAuthAuthorizationCodes(ctx context.Context, arg DeleteExpiredOAuthAuthorizationCodesParams) (int64, error)
	// OAuth start is unauthenticated and writes one row per request. Each start
	// therefore clears a bounded batch of expired rows before creating its own.
	//
	// Bounded by an explicit LIMIT rather than an unqualified DELETE: this
	// runs on a request path, so its worst case must be a constant, not a
	// function of table size. The inner SELECT drives the index
	// oauth_transactions_expires_at_idx directly, oldest first, so repeated
	// calls make monotonic progress instead of rescanning the same rows.
	//
	// expires_at alone is the predicate: a consumed transaction still carries
	// its original expires_at, so consumed and abandoned rows alike leave on
	// the same schedule, and a row is never removed while it could still be
	// validly consumed (ConsumeOAuthTransaction's own WHERE requires
	// expires_at > now).
	DeleteExpiredOAuthTransactions(ctx context.Context, arg DeleteExpiredOAuthTransactionsParams) (int64, error)
	// Removing a client cascades its codes, grants, and tokens: deregistering an
	// agent ends every authorization it holds.
	DeleteOAuthClient(ctx context.Context, id uuid.UUID) (int64, error)
	// Deletes exactly the candidate set the caller just locked. The batch bound
	// lives in ListIdleOAuthClientCandidates; this statement never widens it.
	DeleteOAuthClients(ctx context.Context, ids []uuid.UUID) (int64, error)
	DeletePasswordRegistration(ctx context.Context, id uuid.UUID) (int64, error)
	DeletePasswordResetToken(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteResumeForUser(ctx context.Context, arg DeleteResumeForUserParams) (int64, error)
	// Revision-CAS delete returning the deleted row, so the caller can
	// validate the stored photo key and enqueue media cleanup in the same
	// transaction. Zero rows (stale revision, wrong owner, or missing id)
	// surfaces as pgx.ErrNoRows; the caller re-reads to distinguish staleness
	// from absence without creating an existence oracle.
	DeleteResumeForUserCAS(ctx context.Context, arg DeleteResumeForUserCASParams) (Resume, error)
	DeleteResumePublicCAS(ctx context.Context, arg DeleteResumePublicCASParams) (Resume, error)
	// Bounded token cleanup. An access token leaves as soon as it has expired or
	// been revoked: it carries no replay-detection role. A refresh token is kept
	// until its whole family has expired, because a superseded or revoked refresh
	// token that is presented again must still be recognized as a replay rather
	// than as an unknown token. rotated_from is ON DELETE SET NULL, so removing a
	// predecessor detaches its successor instead of cascading past the batch bound.
	DeleteTerminalOAuthTokens(ctx context.Context, arg DeleteTerminalOAuthTokensParams) (int64, error)
	// Records exact-key cleanup work in the caller's transaction (ADR 0019).
	// Duplicate enqueue of the immutable key is idempotent (zero rows); the
	// table's own check constraint rejects a malformed or cross-resume key.
	EnqueueMediaDeletionJob(ctx context.Context, arg EnqueueMediaDeletionJobParams) (int64, error)
	// Finds the exact unrevoked successor through rotated_from. The partial unique
	// index in migration 00003 permits at most one successor per predecessor;
	// timestamps must never be used to reconstruct this lineage. The reverse
	// direction is already present in a session row's rotated_from value.
	FindLiveSuccessorSession(ctx context.Context, rotatedFrom *uuid.UUID) (Session, error)
	// Inputs for the capacity Retry-After decision: while an expired retained
	// row remains the caller retries in one second (the next mutation's
	// bounded cleanup frees space); otherwise the earliest retained expiry
	// says when space can next appear.
	// earliest_expiry falls back to the caller's own now when the user retains
	// no records at all (capacity rejection with zero retained records cannot
	// normally happen); the caller maps any earliest_expiry <= now to the
	// one-second branch.
	GetIdempotencyCapacityRetryAfter(ctx context.Context, arg GetIdempotencyCapacityRetryAfterParams) (GetIdempotencyCapacityRetryAfterRow, error)
	GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyRecord, error)
	GetIdentityByProviderSubject(ctx context.Context, arg GetIdentityByProviderSubjectParams) (Identity, error)
	// Re-locks the exact leased job by its owner before the bounded send handoff,
	// so a token replacement that already committed cannot race this delivery.
	GetLeasedAuthEmailJobForUpdate(ctx context.Context, arg GetLeasedAuthEmailJobForUpdateParams) (AuthEmailJob, error)
	// The grant-skip read: a live grant with equal-or-wider scopes lets authorize
	// issue a code without a second consent.
	GetLiveOAuthGrant(ctx context.Context, arg GetLiveOAuthGrantParams) (OAuthGrant, error)
	// Ambiguous-delete recovery proves the exact immutable cleanup job without
	// scanning or exposing unrelated object keys.
	GetMediaDeletionJobByObjectKey(ctx context.Context, arg GetMediaDeletionJobByObjectKeyParams) (MediaDeletionJob, error)
	// Replay lookup: returns the row whether or not it was consumed, so the caller
	// can see the family a consumed code issued and revoke exactly those tokens.
	GetOAuthAuthorizationCodeByDigest(ctx context.Context, codeDigest []byte) (OAuthAuthorizationCode, error)
	// The locked replay lookup used before a consumed-code replay revokes the
	// family it issued, so the revocation and the row it read cannot interleave.
	GetOAuthAuthorizationCodeByDigestForUpdate(ctx context.Context, codeDigest []byte) (OAuthAuthorizationCode, error)
	GetOAuthClient(ctx context.Context, id uuid.UUID) (OAuthClient, error)
	// The client-row lock the authorize, consent, and token paths take before
	// writing a grant, code, or token for that client. Holding it is what lets
	// ListIdleOAuthClientCandidates skip (rather than collect) a client that is
	// being consented to right now.
	GetOAuthClientForUpdate(ctx context.Context, id uuid.UUID) (OAuthClient, error)
	// The grant-row lock every token-family revocation takes first, so a rotation
	// committing concurrently cannot resurrect a family the revocation just killed.
	GetOAuthGrantForUpdate(ctx context.Context, id uuid.UUID) (OAuthGrant, error)
	// The bearer boundary's single round trip (M7): token row, its grant, and its
	// account in one query. The caller applies expiry, revocation, supersession,
	// and kind checks to the returned row; every rejection class therefore reads
	// the same rows and produces the same closed response.
	GetOAuthTokenAuthorityByDigest(ctx context.Context, tokenDigest []byte) (GetOAuthTokenAuthorityByDigestRow, error)
	// Locks (creating if absent) the caller's usage row inside the current
	// transaction. The no-op DO UPDATE assignment is what makes the conflict
	// arm take the row lock and return the existing row; user_id itself never
	// appears in a SET clause.
	GetOrCreateIdempotencyUsageForUpdate(ctx context.Context, userID uuid.UUID) (IdempotencyUsage, error)
	GetPasswordCredential(ctx context.Context, userID uuid.UUID) (PasswordCredential, error)
	GetPasswordCredentialForUpdate(ctx context.Context, userID uuid.UUID) (PasswordCredential, error)
	GetPasswordRegistrationByDigest(ctx context.Context, tokenDigest []byte) (PasswordRegistration, error)
	GetPasswordRegistrationByEmailForUpdate(ctx context.Context, email string) (PasswordRegistration, error)
	GetPasswordRegistrationForUpdate(ctx context.Context, id uuid.UUID) (PasswordRegistration, error)
	GetPasswordResetTokenByDigest(ctx context.Context, tokenDigest []byte) (PasswordResetToken, error)
	GetPasswordResetTokenByUserForUpdate(ctx context.Context, userID uuid.UUID) (PasswordResetToken, error)
	GetPasswordResetTokenForUpdate(ctx context.Context, id uuid.UUID) (PasswordResetToken, error)
	// The generation and eligible slug set are selected by one PostgreSQL
	// statement so aggregate discovery admission cannot pair different commits.
	GetPublicDiscoverySnapshot(ctx context.Context) (GetPublicDiscoverySnapshotRow, error)
	GetPublicResumeByOwner(ctx context.Context, arg GetPublicResumeByOwnerParams) (Resume, error)
	// Missing, never-published, private, renamed, and deleted rows all surface as
	// pgx.ErrNoRows. Representation-specific flags are checked after this live
	// gate without exposing a different lookup result.
	GetPublicResumeBySlug(ctx context.Context, slug string) (Resume, error)
	GetPublicState(ctx context.Context) (PublicState, error)
	// System-job read for the document-version backfill. It is intentionally
	// not user-scoped, unlike product reads. It adds no write path.
	GetResumeByID(ctx context.Context, id uuid.UUID) (Resume, error)
	GetResumeForUser(ctx context.Context, arg GetResumeForUserParams) (Resume, error)
	// Loads a target so the caller can revoke its rotation partner.
	// RevokeSessionForUser returns only a row count, and the target need not be the
	// caller's current session, so the lineage values require this read.
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	// Session-row lock for password add/change, which revokes the current session
	// and every sibling atomically.
	GetSessionByIDForUpdate(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error)
	GetSlugClaim(ctx context.Context, slug string) (uuid.UUID, error)
	GetSlugTombstoneForUpdate(ctx context.Context, slug string) (SlugTombstone, error)
	// Ownership read before a new-account insert. The caller passes the canonical
	// lowercase form; users.email is citext so the comparison is already
	// case-insensitive, and the unique constraint arbitrates the actual insert.
	GetUserByCanonicalEmail(ctx context.Context, email string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// ---------------------------------------------------------------------------
	// Phase PA: password credentials, registrations, reset tokens, and email jobs.
	// Lock order (D4) is user -> credential -> reset token -> sessions. These
	// queries expose exactly the row locks that order needs and no others.
	// ---------------------------------------------------------------------------
	// The user-row lock every session issuer and password mutation serializes on.
	GetUserForUpdate(ctx context.Context, id uuid.UUID) (User, error)
	// Refresh rotation (M3). Every identity field -- family, client, user, grant,
	// and family expiry -- is read from the predecessor row rather than trusted
	// from the caller, so a rotated token structurally cannot join a different
	// family, client, user, or grant than the token it succeeds. A missing
	// predecessor selects no row and returns pgx.ErrNoRows instead of inserting an
	// orphan. The partial unique index on rotated_from means one predecessor can
	// mint at most one successor even under concurrent rotations.
	InsertRotatedOAuthToken(ctx context.Context, arg InsertRotatedOAuthTokenParams) (OAuthToken, error)
	InsertSlugTombstone(ctx context.Context, arg InsertSlugTombstoneParams) (SlugTombstone, error)
	// Discovery bytes contain only eligible slugs in raw byte order. The
	// COALESCE is unreachable under the predicate and gives sqlc a non-null Go
	// string instead of a pointer.
	ListEligiblePublicSlugs(ctx context.Context) ([]string, error)
	// Ordered by creation time then ID, oldest first with a deterministic tie-breaker.
	ListIdentitiesByUserID(ctx context.Context, userID uuid.UUID) ([]Identity, error)
	// The bounded idle-client sweep (M1/M5): clients registered before
	// idle_before that hold no live grant and no live token. FOR UPDATE SKIP
	// LOCKED both reserves the returned rows for the caller's transaction -- so a
	// concurrent grant insert blocks on the FK's key-share lock and then fails
	// rather than being cascaded away -- and skips any client another transaction
	// already locked. Ordered oldest-first on oauth_clients_created_at_idx so
	// repeated sweeps make monotonic progress.
	ListIdleOAuthClientCandidates(ctx context.Context, arg ListIdleOAuthClientCandidatesParams) ([]uuid.UUID, error)
	// Startup readiness: the distinct key IDs every pending/leased (non-terminal,
	// non-expired) job references. The key ring must decrypt all of them.
	ListLiveAuthEmailJobKeyIDs(ctx context.Context, now time.Time) ([]string, error)
	// The connected-agents list: client name, scopes, and when the agent was
	// connected and last used. Last-used comes from the grant's tokens rather than
	// a duplicated column, so there is one source of truth for agent activity.
	// Bounded by limit_rows; ordered newest-first with id as a deterministic
	// tiebreaker.
	//
	// The correlated ORDER BY ... LIMIT 1 is deliberate where max() would read
	// more naturally: sqlc cannot type an aggregate expression and emits
	// interface{} for it, while a plain nullable column reference keeps the Go
	// type *time.Time — NULL for a grant whose tokens have never been used.
	ListLiveOAuthGrantsForUser(ctx context.Context, arg ListLiveOAuthGrantsForUserParams) ([]ListLiveOAuthGrantsForUserRow, error)
	// Lists sessions that internal/auth also considers live:
	//
	//   - not explicitly revoked (revoked_at IS NULL);
	//   - not idle-expired: last_seen_at >= idle_cutoff, where idle_cutoff =
	//     now - idleTimeout is computed in Go (session.go's own constant) and
	//     passed as a query arg, never re-literalled as a SQL interval here;
	//   - not absolute-expired: absolute_expires_at >= now;
	//   - not a grace-dead rotation predecessor: rotation_grace_until IS NULL
	//     OR rotation_grace_until >= now -- a superseded session keeps
	//     revoked_at NULL but has rotation_grace_until in
	//     the past, and that row must never appear in the caller's own
	//     device list, exactly like an explicitly revoked one, just not
	//     marked that way.
	//
	// sqlc.arg(...)::timestamptz casts are explicit so both parameters' Go
	// types are plain (non-pointer) time.Time regardless of the nullable
	// columns they're compared against. Ordered newest-created first, with id
	// as a deterministic tiebreaker for equal creation times.
	ListLiveSessionsForUser(ctx context.Context, arg ListLiveSessionsForUserParams) ([]Session, error)
	ListResumeIDsBelowSchemaVersion(ctx context.Context, arg ListResumeIDsBelowSchemaVersionParams) ([]uuid.UUID, error)
	ListResumesForUser(ctx context.Context, userID uuid.UUID) ([]Resume, error)
	LockPublicState(ctx context.Context) (PublicState, error)
	LockSlugClaim(ctx context.Context, slug string) error
	LockUserForResumeWrite(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// SES accepted: clears every encryption and lease field and records sent_at.
	MarkAuthEmailJobSent(ctx context.Context, arg MarkAuthEmailJobSentParams) (int64, error)
	// Permanent failure, expiry, or the eighth attempt: clears every encryption and
	// lease field and records terminal_at. A stale pending job may terminate
	// without ever being leased (attempts stays 0).
	MarkAuthEmailJobTerminal(ctx context.Context, arg MarkAuthEmailJobTerminalParams) (int64, error)
	// Normalizes a candidate response through the same jsonb representation an
	// insert would store and reports the exact byte count the usage
	// reservation must account for — the one canonical byte expression shared
	// with backfill, insert, and cleanup.
	NormalizeIdempotencyResponse(ctx context.Context, arg NormalizeIdempotencyResponseParams) (NormalizeIdempotencyResponseRow, error)
	PublishResumeCAS(ctx context.Context, arg PublishResumeCASParams) (Resume, error)
	// Releases exactly the counters of physically deleted records, in the same
	// transaction as their deletion. The migration's purge-then-backfill order
	// plus transactional maintenance guarantee this can never underflow the
	// non-negative checks.
	ReleaseIdempotencyUsage(ctx context.Context, arg ReleaseIdempotencyUsageParams) (int64, error)
	// A temporary failure releases the lease back to pending with the next attempt
	// time, retaining ciphertext and the already-incremented attempt count. The
	// caller never requeues at attempts = 8 (that path marks terminal instead).
	RequeueAuthEmailJob(ctx context.Context, arg RequeueAuthEmailJobParams) (int64, error)
	// Bounded stale-lease recovery: a lease that expired without a completed send
	// returns to pending, rolling back the claim's attempt increment (the send
	// never happened) and re-dueing immediately. Ordered so repeated calls make
	// monotonic progress.
	RequeueExpiredAuthEmailLeases(ctx context.Context, arg RequeueExpiredAuthEmailLeasesParams) (int64, error)
	// Logout-everywhere: revokes every one of the user's not-already-revoked
	// sessions and reports how many rows that affected.
	RevokeAllSessions(ctx context.Context, arg RevokeAllSessionsParams) (int64, error)
	// Internal revocation (RFC 7009 and consumed-code replay), where the grant id
	// came from a token row the caller already validated. Idempotent: revoking an
	// already-revoked grant affects zero rows.
	RevokeOAuthGrant(ctx context.Context, arg RevokeOAuthGrantParams) (int64, error)
	// The settings-page revocation. Ownership is part of the predicate, so a
	// missing, already-revoked, and differently owned grant all return
	// pgx.ErrNoRows and no existence oracle appears.
	RevokeOAuthGrantForUser(ctx context.Context, arg RevokeOAuthGrantForUserParams) (OAuthGrant, error)
	// Superseded-token replay defense: every still-live member of one family dies
	// together, in the caller's transaction, under the grant row lock.
	RevokeOAuthTokenFamily(ctx context.Context, arg RevokeOAuthTokenFamilyParams) (int64, error)
	// Grant revocation kills every family issued under it, not just the newest.
	RevokeOAuthTokensForGrant(ctx context.Context, arg RevokeOAuthTokensForGrantParams) (int64, error)
	// Idempotent: revoking an already-revoked (or nonexistent) session id
	// affects zero rows rather than erroring, so logout/revoke can be retried
	// safely. revoked_at is immediate and orthogonal to rotation_grace_until
	// and this query never changes that column.
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	// Revokes only a live session owned by user_id. The live predicates match
	// ListLiveSessionsForUser so a hidden expired session cannot be reported as
	// revoked. The affected-row count lets the caller return the same absence
	// result for missing, expired, and differently owned sessions.
	RevokeSessionForUser(ctx context.Context, arg RevokeSessionForUserParams) (int64, error)
	// Starts a predecessor's short grace period after its successor is first
	// used. BeginSessionRotation parks rotation_grace_until at
	// min(now + rotationAge, its own absolute_expires_at) -- non-NULL, so the
	// rotation CAS still
	// admits exactly one winner, far enough out that a successor whose one and
	// only raw-token delivery was lost never orphans the lineage, and bounded
	// so a predecessor that is never superseded in practice still expires on a
	// credential's timescale rather than the session's. This is the statement
	// that converts that parked value into a real, short deadline once the
	// successor's token has provably reached a client.
	//
	// The `rotation_grace_until > grace_until` predicate makes it
	// monotonically SHRINKING and idempotent: the first call moves the
	// deadline in from the parked bound to first-use + rotationGrace;
	// every later call (the same successor's second, third, ... request, or a
	// concurrent one racing it) proposes a LATER deadline and therefore
	// matches no row. A predecessor's grace can never be pushed back out by
	// continued use of the successor, which would otherwise keep a superseded
	// credential alive indefinitely.
	StartSessionRotationGrace(ctx context.Context, arg StartSessionRotationGraceParams) error
	// Marks the presented refresh token superseded as part of a rotation. family_id
	// is part of the predicate, so a caller holding one family's identifier can
	// never mark a token belonging to another family, and a second supersession of
	// the same row affects nothing (pgx.ErrNoRows) -- which is exactly the replay
	// the caller turns into a whole-family revocation.
	SupersedeOAuthToken(ctx context.Context, arg SupersedeOAuthTokenParams) (OAuthToken, error)
	// Unconditional: callers throttle to at most once per lastSeenThrottle
	// themselves (internal/auth.SessionManager.Authenticate) before issuing
	// this write, so it is not itself CAS-guarded.
	TouchLastSeenAt(ctx context.Context, arg TouchLastSeenAtParams) error
	// Bounded activity record: at most one write per client per touch window. The
	// caller passes touch_before = now - window, so the throttle is enforced by
	// the predicate rather than by caller bookkeeping.
	TouchOAuthClientLastUsed(ctx context.Context, arg TouchOAuthClientLastUsedParams) (int64, error)
	// Bounded activity record (M3): at most one write per token per touch window,
	// and never on a revoked token. The caller passes touch_before = now - window.
	TouchOAuthTokenLastUsed(ctx context.Context, arg TouchOAuthTokenLastUsedParams) (int64, error)
	// Records that this session's lineage just completed a full OAuth login
	// after a real reauthentication round trip, never by rotation.
	TouchReauthenticatedAt(ctx context.Context, arg TouchReauthenticatedAtParams) error
	// Conditionally admits one new retained record of record_bytes stored
	// bytes within the caps. Zero rows (pgx.ErrNoRows) means the insert would
	// exceed a cap and the caller must reject with the typed capacity error
	// without committing the mutation.
	TryReserveIdempotencyUsage(ctx context.Context, arg TryReserveIdempotencyUsageParams) (TryReserveIdempotencyUsageRow, error)
	// The returned revision is the NEW revision (revision + 1), never the
	// caller's expected one. A stale or non-matching $3 updates zero rows and
	// surfaces as pgx.ErrNoRows, which internal/resume turns into
	// *RevisionMismatchError or ErrNotFound.
	UpdateResumeDocumentCAS(ctx context.Context, arg UpdateResumeDocumentCASParams) (int64, error)
	// The P2B full-aggregate metadata write (D15/D17): title, lng, and the
	// caller's complete already-projected document under ONE revision CAS. The
	// returned revision is the NEW revision. A stale or non-matching $3
	// updates zero rows and surfaces as pgx.ErrNoRows, which internal/resume
	// turns into *RevisionMismatchError or ErrNotFound. user_id never appears
	// in a SET clause (the cap trigger fires on UPDATE OF user_id).
	UpdateResumeMetadataAndDocumentCAS(ctx context.Context, arg UpdateResumeMetadataAndDocumentCASParams) (int64, error)
	// The returned revision is the NEW revision (revision + 1), never the
	// caller's expected one. A stale or non-matching $3 updates zero rows and
	// surfaces as pgx.ErrNoRows, which internal/resume turns into
	// *RevisionMismatchError or ErrNotFound.
	UpdateResumeTitleCAS(ctx context.Context, arg UpdateResumeTitleCASParams) (int64, error)
	// Consent approval (M8): records a new grant or refreshes the live one's
	// scopes. The conflict target names the partial unique index's predicate, so
	// the upsert arbitrates on exactly the "one live grant per (user, client)"
	// rule the database enforces. created_at is never rewritten -- the settings
	// list shows when the agent was first connected, not when it was last
	// re-approved.
	UpsertOAuthGrant(ctx context.Context, arg UpsertOAuthGrantParams) (OAuthGrant, error)
	// Insert-or-replace the single credential under the row lock the caller
	// already holds (GetPasswordCredentialForUpdate), re-encoding the hash and
	// bumping changed_at on the conflict arm.
	UpsertPasswordCredential(ctx context.Context, arg UpsertPasswordCredentialParams) (PasswordCredential, error)
}

var _ Querier = (*Queries)(nil)
