// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BackfillResumeDocumentCAS(ctx context.Context, arg BackfillResumeDocumentCASParams) (int64, error)
	// Single-row conditional UPDATE that decides the >24h rotation winner: only
	// a row that has neither already started rotating (rotation_grace_until
	// still NULL) nor been revoked is claimed. Under concurrent callers racing
	// the same session id, exactly one UPDATE affects a row (returns its id);
	// every other caller's UPDATE affects zero rows and pgx reports
	// pgx.ErrNoRows -- that caller lost the race and must not mint a second
	// successor (see internal/auth.SessionManager.Authenticate).
	BeginSessionRotation(ctx context.Context, arg BeginSessionRotationParams) (uuid.UUID, error)
	// Atomically claims a transaction: only a row that is unexpired and not yet
	// consumed (as of now, $2) is updated and returned. A handle that is
	// unknown, expired, or already consumed matches no row, so the caller sees
	// exactly one outcome (pgx.ErrNoRows) for all three cases -- see
	// internal/auth.ErrTransactionInvalid's doc comment for why that collapse
	// is deliberate. The provider-mismatch check (RFC 9700 mix-up defense)
	// happens in Go, after this still consumes the row: an attacker replaying
	// a valid handle against the wrong provider's callback burns the
	// transaction just like any other outcome, so it can never be retried
	// against the correct provider either.
	ConsumeOAuthTransaction(ctx context.Context, arg ConsumeOAuthTransactionParams) (OAuthTransaction, error)
	CountResumesForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) error
	// internal/auth's login-resolution algorithm calls
	// GetIdentityByProviderSubject first specifically to avoid racing
	// identities_provider_subject_key's UNIQUE (provider, provider_user_id) in
	// the common case; Task 10's link algorithm handles the
	// already-claimed-by-another-user case explicitly instead of relying on
	// this insert to fail.
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error)
	CreateOAuthTransaction(ctx context.Context, arg CreateOAuthTransactionParams) (OAuthTransaction, error)
	CreateResume(ctx context.Context, arg CreateResumeParams) (Resume, error)
	// Always inserts a brand-new row -- used both by Issue (fixation defense: a
	// login never reuses an existing session row) and by the >24h rotation
	// winner's successor insert (internal/auth.SessionManager.Authenticate),
	// which passes the predecessor's user_id, reauthenticated_at,
	// absolute_expires_at, ua, and ip through unchanged so a rotation never
	// extends absolute expiry or silently satisfies the recent-reauth gate.
	// rotated_from (fix round 3, DD-C14c) is NULL for Issue's own fresh-login
	// insert, and the predecessor's own id for tryRotate's successor insert --
	// the exact, database-enforced (sessions_rotated_from_key) lineage link
	// FindLiveSuccessorSession below and the row's own rotated_from column
	// (no query needed for the predecessor direction) both depend on.
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Hand-written, sqlc-annotated queries (`-- name: X :one/:many/:exec`) that
	// become type-safe Go methods in internal/store via `make generate`. See
	// docs/specs/aboutme-design.md §3 "Schema management".
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// D11 opportunistic reaping (owner ruling): every Execute deletes the
	// calling user's expired rows in the same tx before inserting, so the TTL
	// is enforced by normal traffic, not by a job that doesn't exist yet.
	DeleteExpiredIdempotencyRecordsForUser(ctx context.Context, arg DeleteExpiredIdempotencyRecordsForUserParams) (int64, error)
	DeleteIdempotencyRecordIfExpired(ctx context.Context, arg DeleteIdempotencyRecordIfExpiredParams) (int64, error)
	DeleteResumeForUser(ctx context.Context, arg DeleteResumeForUserParams) (int64, error)
	// Fix round 3, finding DD-C14c (owner ruling: schema change, replacing
	// fix round 1/2's timestamp-reconstruction queries): given a session
	// that may itself be a rotation PREDECESSOR, finds the exact successor
	// row it was rotated INTO, if that successor is still live (revoked_at
	// IS NULL). Exact by construction, not a heuristic: rotated_from is a
	// foreign key tryRotate's successor insert (internal/auth/session.go)
	// sets once, at INSERT time, to the predecessor's own id, and
	// sessions_rotated_from_key (sql/schema.sql) is a partial UNIQUE index
	// on it -- a predecessor has AT MOST ONE successor, enforced by the
	// database itself, not merely by BeginSessionRotation's CAS. This
	// replaces fix round 1/2's FindImmediatePredecessorSession/
	// FindImmediateSuccessorSession, which reconstructed the link from
	// rotation_grace_until/created_at timing alone: that approach was proven
	// to silently match ANY same-user session sharing the same microsecond
	// (pgx's :one takes the first row silently), which a frozen-clock test
	// (or, in principle, sufficiently concurrent real traffic) can trigger --
	// see task-9-report.md's fix round 3 section. The predecessor direction
	// needs no equivalent query at all: a session's own rotated_from column,
	// already in hand on any row already read, IS the answer.
	FindLiveSuccessorSession(ctx context.Context, rotatedFrom *uuid.UUID) (Session, error)
	GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyRecord, error)
	GetIdentityByProviderSubject(ctx context.Context, arg GetIdentityByProviderSubjectParams) (Identity, error)
	GetResumeForUser(ctx context.Context, arg GetResumeForUserParams) (Resume, error)
	// Fix round 2, finding DD-C14b: DELETE /sessions/{id}'s lineage sweep
	// (sessions_handlers.go's revokeLineagePartners) needs the just-revoked
	// TARGET session's own id/rotated_from/user_id to look up its rotation
	// lineage partner(s) -- RevokeSessionForUser only reports a row count,
	// not the row itself, and the target is not always the caller's own
	// current session (sess, already fully in hand from context), so a
	// second read is unavoidable here. revoked_at is already set to
	// non-NULL by the time this runs (it always runs strictly after a
	// successful RevokeForUser), but every other column this caller needs
	// is untouched by that UPDATE.
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Task 9's GET /me: every provider identity linked to user_id, oldest
	// first (created_at) so the first-ever linked provider always sorts
	// first.
	ListIdentitiesByUserID(ctx context.Context, userID uuid.UUID) ([]Identity, error)
	// Task 9's GET /sessions device list (design spec §3): every session
	// belonging to user_id that is still LIVE as of now -- mirrors
	// session.go's sessionDead exactly, predicate for predicate (fix round 1,
	// finding I1: the original version only excluded revoked/grace-dead rows,
	// silently listing idle-expired and absolute-expired sessions as live
	// devices with no GC to ever remove them):
	//
	//   - not explicitly revoked (revoked_at IS NULL);
	//   - not idle-expired: last_seen_at >= idle_cutoff, where idle_cutoff =
	//     now - idleTimeout is computed in GO (session.go's own constant) and
	//     passed as a query arg, never re-literalled as a SQL interval here;
	//   - not absolute-expired: absolute_expires_at >= now;
	//   - not a grace-dead rotation predecessor: rotation_grace_until IS NULL
	//     OR rotation_grace_until >= now -- a session rotation has already
	//     superseded keeps revoked_at NULL but has rotation_grace_until in
	//     the past, and that row must never appear in the caller's own
	//     device list, exactly like an explicitly revoked one, just not
	//     marked that way.
	//
	// sqlc.arg(...)::timestamptz casts are explicit so both parameters' Go
	// types are plain (non-pointer) time.Time regardless of the nullable
	// columns they're compared against. Ordered newest-created first, with id
	// as a deterministic tiebreaker for two rows created in the same instant
	// (fix round 1, M4).
	ListLiveSessionsForUser(ctx context.Context, arg ListLiveSessionsForUserParams) ([]Session, error)
	ListResumeIDsBelowSchemaVersion(ctx context.Context, arg ListResumeIDsBelowSchemaVersionParams) ([]uuid.UUID, error)
	ListResumesForUser(ctx context.Context, userID uuid.UUID) ([]Resume, error)
	LockUserForResumeWrite(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// Logout-everywhere: revokes every one of the user's not-already-revoked
	// sessions and reports how many rows that affected.
	RevokeAllSessions(ctx context.Context, arg RevokeAllSessionsParams) (int64, error)
	// Idempotent: revoking an already-revoked (or nonexistent) session id
	// affects zero rows rather than erroring, so logout/revoke can be retried
	// safely. revoked_at is immediate and orthogonal to rotation_grace_until
	// (design decision 1) -- this never touches that column.
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	// Ownership-checked counterpart to RevokeSession: only revokes id if it
	// also belongs to user_id AND is still LIVE by the exact same predicates
	// ListLiveSessionsForUser uses below (fix round 1, findings I1/M5): a
	// session that is already idle-expired, absolute-expired, or a grace-dead
	// rotation predecessor must revoke ZERO rows here too -- otherwise a
	// caller could "revoke" a row GET /sessions' own device list already
	// refuses to show them, which is exactly the self-inconsistency the
	// review caught. Returns the affected row count so a caller can
	// distinguish "revoked" (1) from "no such LIVE session for this user" (0)
	// -- internal/auth.SessionManager.RevokeForUser's own caller (Task 9's
	// DELETE /sessions/{id}) turns 0 into a 404, not a 403, so it never
	// confirms whether the id exists for someone else, is merely dead, or
	// belongs to another user.
	RevokeSessionForUser(ctx context.Context, arg RevokeSessionForUserParams) (int64, error)
	// Unconditional: callers throttle to at most once per lastSeenThrottle
	// themselves (internal/auth.SessionManager.Authenticate) before issuing
	// this write, so it is not itself CAS-guarded.
	TouchLastSeenAt(ctx context.Context, arg TouchLastSeenAtParams) error
	// Records that this session's lineage just completed a full OAuth login
	// (design decision 2) -- called only after a real reauth round trip
	// (internal/auth.SessionManager.TouchReauthenticated), never by rotation.
	TouchReauthenticatedAt(ctx context.Context, arg TouchReauthenticatedAtParams) error
	UpdateResumeDocumentCAS(ctx context.Context, arg UpdateResumeDocumentCASParams) (int64, error)
	UpdateResumeTitleCAS(ctx context.Context, arg UpdateResumeTitleCASParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
