// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	// Hand-written, sqlc-annotated queries (`-- name: X :one/:many/:exec`) that
	// become type-safe Go methods in internal/store via `make generate`. See
	// docs/specs/aboutme-design.md §3 "Schema management".
	//
	// No product-table queries yet (schema.sql defines no product tables) —
	// those land alongside users/identities/sessions in Phase 1 and
	// resumes/slug_tombstones in Phase 2A. sqlc requires at least one query to
	// generate anything, so the one query below is a deliberate placeholder:
	// it proves the schema.sql -> sqlc -> internal/store codegen path produces
	// real, compiling Go end-to-end (task 0.3's generation path must be
	// verified, not just configured) without inventing product schema. Replace
	// or remove it once Phase 1 adds real queries.
	Ping(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
