// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_membership.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const runtimeMarkMaintenanceReplicaJoinReady = `-- name: RuntimeMarkMaintenanceReplicaJoinReady :one
WITH result AS MATERIALIZED (
 SELECT public.runtime_mark_maintenance_replica_join_ready($1::uuid,$2::text,$3::text,$4::text,$5::text,$6::text,$7::text) AS r
)
SELECT (r).replica_id::uuid AS replica_id,(r).replica_kind::text AS replica_kind,(r).state::text AS state,
 COALESCE((r).desired_replicas,0::smallint)::smallint AS desired_replicas_value,((r).desired_replicas IS NOT NULL)::boolean AS desired_replicas_present,
 COALESCE((r).active_serving_replicas,0::smallint)::smallint AS active_serving_replicas_value,((r).active_serving_replicas IS NOT NULL)::boolean AS active_serving_replicas_present,
 COALESCE((r).active_maintenance_replicas,0::smallint)::smallint AS active_maintenance_replicas_value,((r).active_maintenance_replicas IS NOT NULL)::boolean AS active_maintenance_replicas_present,
 COALESCE((r).partition_1_enabled,false)::boolean AS partition_1_enabled_value,((r).partition_1_enabled IS NOT NULL)::boolean AS partition_1_enabled_present,
 COALESCE((r).partition_2_enabled,false)::boolean AS partition_2_enabled_value,((r).partition_2_enabled IS NOT NULL)::boolean AS partition_2_enabled_present,
 (r).capacity_generation::bigint AS capacity_generation,(r).controller_generation::bigint AS controller_generation,
 (r).controller_operation_id::text AS controller_operation_id,(r).admission_enabled::boolean AS admission_enabled,
 (r).lifecycle_phase::text AS lifecycle_phase,(r).replayed::boolean AS replayed FROM result
`

type RuntimeMarkMaintenanceReplicaJoinReadyParams struct {
	ReplicaID            uuid.UUID
	InstanceID           string
	ContainerInstanceArn string
	CaddyTaskArn         string
	GoTaskArn            string
	NuxtTaskArn          string
	ReleaseDigest        string
}

type RuntimeMarkMaintenanceReplicaJoinReadyRow struct {
	ReplicaID                        uuid.UUID
	ReplicaKind                      string
	State                            string
	DesiredReplicasValue             int16
	DesiredReplicasPresent           bool
	ActiveServingReplicasValue       int16
	ActiveServingReplicasPresent     bool
	ActiveMaintenanceReplicasValue   int16
	ActiveMaintenanceReplicasPresent bool
	Partition1EnabledValue           bool
	Partition1EnabledPresent         bool
	Partition2EnabledValue           bool
	Partition2EnabledPresent         bool
	CapacityGeneration               int64
	ControllerGeneration             int64
	ControllerOperationID            string
	AdmissionEnabled                 bool
	LifecyclePhase                   string
	Replayed                         bool
}

func (q *Queries) RuntimeMarkMaintenanceReplicaJoinReady(ctx context.Context, arg RuntimeMarkMaintenanceReplicaJoinReadyParams) (RuntimeMarkMaintenanceReplicaJoinReadyRow, error) {
	row := q.db.QueryRow(ctx, runtimeMarkMaintenanceReplicaJoinReady,
		arg.ReplicaID,
		arg.InstanceID,
		arg.ContainerInstanceArn,
		arg.CaddyTaskArn,
		arg.GoTaskArn,
		arg.NuxtTaskArn,
		arg.ReleaseDigest,
	)
	var i RuntimeMarkMaintenanceReplicaJoinReadyRow
	err := row.Scan(
		&i.ReplicaID,
		&i.ReplicaKind,
		&i.State,
		&i.DesiredReplicasValue,
		&i.DesiredReplicasPresent,
		&i.ActiveServingReplicasValue,
		&i.ActiveServingReplicasPresent,
		&i.ActiveMaintenanceReplicasValue,
		&i.ActiveMaintenanceReplicasPresent,
		&i.Partition1EnabledValue,
		&i.Partition1EnabledPresent,
		&i.Partition2EnabledValue,
		&i.Partition2EnabledPresent,
		&i.CapacityGeneration,
		&i.ControllerGeneration,
		&i.ControllerOperationID,
		&i.AdmissionEnabled,
		&i.LifecyclePhase,
		&i.Replayed,
	)
	return i, err
}

const runtimeMarkServingReplicaJoinReady = `-- name: RuntimeMarkServingReplicaJoinReady :one
WITH result AS MATERIALIZED (
 SELECT public.runtime_mark_serving_replica_join_ready($1::uuid,$2::text,$3::text,$4::text,$5::text,$6::text,$7::text) AS r
)
SELECT (r).replica_id::uuid AS replica_id,(r).replica_kind::text AS replica_kind,(r).state::text AS state,
 COALESCE((r).desired_replicas,0::smallint)::smallint AS desired_replicas_value,((r).desired_replicas IS NOT NULL)::boolean AS desired_replicas_present,
 COALESCE((r).active_serving_replicas,0::smallint)::smallint AS active_serving_replicas_value,((r).active_serving_replicas IS NOT NULL)::boolean AS active_serving_replicas_present,
 COALESCE((r).active_maintenance_replicas,0::smallint)::smallint AS active_maintenance_replicas_value,((r).active_maintenance_replicas IS NOT NULL)::boolean AS active_maintenance_replicas_present,
 COALESCE((r).partition_1_enabled,false)::boolean AS partition_1_enabled_value,((r).partition_1_enabled IS NOT NULL)::boolean AS partition_1_enabled_present,
 COALESCE((r).partition_2_enabled,false)::boolean AS partition_2_enabled_value,((r).partition_2_enabled IS NOT NULL)::boolean AS partition_2_enabled_present,
 (r).capacity_generation::bigint AS capacity_generation,(r).controller_generation::bigint AS controller_generation,
 (r).controller_operation_id::text AS controller_operation_id,(r).admission_enabled::boolean AS admission_enabled,
 (r).lifecycle_phase::text AS lifecycle_phase,(r).replayed::boolean AS replayed FROM result
`

type RuntimeMarkServingReplicaJoinReadyParams struct {
	ReplicaID            uuid.UUID
	InstanceID           string
	ContainerInstanceArn string
	CaddyTaskArn         string
	GoTaskArn            string
	NuxtTaskArn          string
	ReleaseDigest        string
}

type RuntimeMarkServingReplicaJoinReadyRow struct {
	ReplicaID                        uuid.UUID
	ReplicaKind                      string
	State                            string
	DesiredReplicasValue             int16
	DesiredReplicasPresent           bool
	ActiveServingReplicasValue       int16
	ActiveServingReplicasPresent     bool
	ActiveMaintenanceReplicasValue   int16
	ActiveMaintenanceReplicasPresent bool
	Partition1EnabledValue           bool
	Partition1EnabledPresent         bool
	Partition2EnabledValue           bool
	Partition2EnabledPresent         bool
	CapacityGeneration               int64
	ControllerGeneration             int64
	ControllerOperationID            string
	AdmissionEnabled                 bool
	LifecyclePhase                   string
	Replayed                         bool
}

func (q *Queries) RuntimeMarkServingReplicaJoinReady(ctx context.Context, arg RuntimeMarkServingReplicaJoinReadyParams) (RuntimeMarkServingReplicaJoinReadyRow, error) {
	row := q.db.QueryRow(ctx, runtimeMarkServingReplicaJoinReady,
		arg.ReplicaID,
		arg.InstanceID,
		arg.ContainerInstanceArn,
		arg.CaddyTaskArn,
		arg.GoTaskArn,
		arg.NuxtTaskArn,
		arg.ReleaseDigest,
	)
	var i RuntimeMarkServingReplicaJoinReadyRow
	err := row.Scan(
		&i.ReplicaID,
		&i.ReplicaKind,
		&i.State,
		&i.DesiredReplicasValue,
		&i.DesiredReplicasPresent,
		&i.ActiveServingReplicasValue,
		&i.ActiveServingReplicasPresent,
		&i.ActiveMaintenanceReplicasValue,
		&i.ActiveMaintenanceReplicasPresent,
		&i.Partition1EnabledValue,
		&i.Partition1EnabledPresent,
		&i.Partition2EnabledValue,
		&i.Partition2EnabledPresent,
		&i.CapacityGeneration,
		&i.ControllerGeneration,
		&i.ControllerOperationID,
		&i.AdmissionEnabled,
		&i.LifecyclePhase,
		&i.Replayed,
	)
	return i, err
}

const runtimeRegisterMaintenanceReplica = `-- name: RuntimeRegisterMaintenanceReplica :one
WITH result AS MATERIALIZED (
 SELECT public.runtime_register_maintenance_replica($1::uuid,$2::text,$3::text,$4::text,$5::text,$6::text,$7::text) AS r
)
SELECT (r).replica_id::uuid AS replica_id,(r).replica_kind::text AS replica_kind,(r).state::text AS state,
 COALESCE((r).desired_replicas,0::smallint)::smallint AS desired_replicas_value,((r).desired_replicas IS NOT NULL)::boolean AS desired_replicas_present,
 COALESCE((r).active_serving_replicas,0::smallint)::smallint AS active_serving_replicas_value,((r).active_serving_replicas IS NOT NULL)::boolean AS active_serving_replicas_present,
 COALESCE((r).active_maintenance_replicas,0::smallint)::smallint AS active_maintenance_replicas_value,((r).active_maintenance_replicas IS NOT NULL)::boolean AS active_maintenance_replicas_present,
 COALESCE((r).partition_1_enabled,false)::boolean AS partition_1_enabled_value,((r).partition_1_enabled IS NOT NULL)::boolean AS partition_1_enabled_present,
 COALESCE((r).partition_2_enabled,false)::boolean AS partition_2_enabled_value,((r).partition_2_enabled IS NOT NULL)::boolean AS partition_2_enabled_present,
 (r).capacity_generation::bigint AS capacity_generation,(r).controller_generation::bigint AS controller_generation,
 (r).controller_operation_id::text AS controller_operation_id,(r).admission_enabled::boolean AS admission_enabled,
 (r).lifecycle_phase::text AS lifecycle_phase,(r).replayed::boolean AS replayed FROM result
`

type RuntimeRegisterMaintenanceReplicaParams struct {
	ReplicaID            uuid.UUID
	InstanceID           string
	ContainerInstanceArn string
	CaddyTaskArn         string
	GoTaskArn            string
	NuxtTaskArn          string
	ReleaseDigest        string
}

type RuntimeRegisterMaintenanceReplicaRow struct {
	ReplicaID                        uuid.UUID
	ReplicaKind                      string
	State                            string
	DesiredReplicasValue             int16
	DesiredReplicasPresent           bool
	ActiveServingReplicasValue       int16
	ActiveServingReplicasPresent     bool
	ActiveMaintenanceReplicasValue   int16
	ActiveMaintenanceReplicasPresent bool
	Partition1EnabledValue           bool
	Partition1EnabledPresent         bool
	Partition2EnabledValue           bool
	Partition2EnabledPresent         bool
	CapacityGeneration               int64
	ControllerGeneration             int64
	ControllerOperationID            string
	AdmissionEnabled                 bool
	LifecyclePhase                   string
	Replayed                         bool
}

func (q *Queries) RuntimeRegisterMaintenanceReplica(ctx context.Context, arg RuntimeRegisterMaintenanceReplicaParams) (RuntimeRegisterMaintenanceReplicaRow, error) {
	row := q.db.QueryRow(ctx, runtimeRegisterMaintenanceReplica,
		arg.ReplicaID,
		arg.InstanceID,
		arg.ContainerInstanceArn,
		arg.CaddyTaskArn,
		arg.GoTaskArn,
		arg.NuxtTaskArn,
		arg.ReleaseDigest,
	)
	var i RuntimeRegisterMaintenanceReplicaRow
	err := row.Scan(
		&i.ReplicaID,
		&i.ReplicaKind,
		&i.State,
		&i.DesiredReplicasValue,
		&i.DesiredReplicasPresent,
		&i.ActiveServingReplicasValue,
		&i.ActiveServingReplicasPresent,
		&i.ActiveMaintenanceReplicasValue,
		&i.ActiveMaintenanceReplicasPresent,
		&i.Partition1EnabledValue,
		&i.Partition1EnabledPresent,
		&i.Partition2EnabledValue,
		&i.Partition2EnabledPresent,
		&i.CapacityGeneration,
		&i.ControllerGeneration,
		&i.ControllerOperationID,
		&i.AdmissionEnabled,
		&i.LifecyclePhase,
		&i.Replayed,
	)
	return i, err
}

const runtimeRegisterServingReplica = `-- name: RuntimeRegisterServingReplica :one
WITH result AS MATERIALIZED (
 SELECT public.runtime_register_serving_replica($1::uuid,$2::text,$3::text,$4::text,$5::text,$6::text,$7::text) AS r
)
SELECT (r).replica_id::uuid AS replica_id,(r).replica_kind::text AS replica_kind,(r).state::text AS state,
 COALESCE((r).desired_replicas,0::smallint)::smallint AS desired_replicas_value,((r).desired_replicas IS NOT NULL)::boolean AS desired_replicas_present,
 COALESCE((r).active_serving_replicas,0::smallint)::smallint AS active_serving_replicas_value,((r).active_serving_replicas IS NOT NULL)::boolean AS active_serving_replicas_present,
 COALESCE((r).active_maintenance_replicas,0::smallint)::smallint AS active_maintenance_replicas_value,((r).active_maintenance_replicas IS NOT NULL)::boolean AS active_maintenance_replicas_present,
 COALESCE((r).partition_1_enabled,false)::boolean AS partition_1_enabled_value,((r).partition_1_enabled IS NOT NULL)::boolean AS partition_1_enabled_present,
 COALESCE((r).partition_2_enabled,false)::boolean AS partition_2_enabled_value,((r).partition_2_enabled IS NOT NULL)::boolean AS partition_2_enabled_present,
 (r).capacity_generation::bigint AS capacity_generation,(r).controller_generation::bigint AS controller_generation,
 (r).controller_operation_id::text AS controller_operation_id,(r).admission_enabled::boolean AS admission_enabled,
 (r).lifecycle_phase::text AS lifecycle_phase,(r).replayed::boolean AS replayed FROM result
`

type RuntimeRegisterServingReplicaParams struct {
	ReplicaID            uuid.UUID
	InstanceID           string
	ContainerInstanceArn string
	CaddyTaskArn         string
	GoTaskArn            string
	NuxtTaskArn          string
	ReleaseDigest        string
}

type RuntimeRegisterServingReplicaRow struct {
	ReplicaID                        uuid.UUID
	ReplicaKind                      string
	State                            string
	DesiredReplicasValue             int16
	DesiredReplicasPresent           bool
	ActiveServingReplicasValue       int16
	ActiveServingReplicasPresent     bool
	ActiveMaintenanceReplicasValue   int16
	ActiveMaintenanceReplicasPresent bool
	Partition1EnabledValue           bool
	Partition1EnabledPresent         bool
	Partition2EnabledValue           bool
	Partition2EnabledPresent         bool
	CapacityGeneration               int64
	ControllerGeneration             int64
	ControllerOperationID            string
	AdmissionEnabled                 bool
	LifecyclePhase                   string
	Replayed                         bool
}

func (q *Queries) RuntimeRegisterServingReplica(ctx context.Context, arg RuntimeRegisterServingReplicaParams) (RuntimeRegisterServingReplicaRow, error) {
	row := q.db.QueryRow(ctx, runtimeRegisterServingReplica,
		arg.ReplicaID,
		arg.InstanceID,
		arg.ContainerInstanceArn,
		arg.CaddyTaskArn,
		arg.GoTaskArn,
		arg.NuxtTaskArn,
		arg.ReleaseDigest,
	)
	var i RuntimeRegisterServingReplicaRow
	err := row.Scan(
		&i.ReplicaID,
		&i.ReplicaKind,
		&i.State,
		&i.DesiredReplicasValue,
		&i.DesiredReplicasPresent,
		&i.ActiveServingReplicasValue,
		&i.ActiveServingReplicasPresent,
		&i.ActiveMaintenanceReplicasValue,
		&i.ActiveMaintenanceReplicasPresent,
		&i.Partition1EnabledValue,
		&i.Partition1EnabledPresent,
		&i.Partition2EnabledValue,
		&i.Partition2EnabledPresent,
		&i.CapacityGeneration,
		&i.ControllerGeneration,
		&i.ControllerOperationID,
		&i.AdmissionEnabled,
		&i.LifecyclePhase,
		&i.Replayed,
	)
	return i, err
}
