// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_lifecycle.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const runtimeActivateReplicaCapacity = `-- name: RuntimeActivateReplicaCapacity :one
WITH result AS MATERIALIZED (
 SELECT public.runtime_activate_replica_capacity($1::bigint,$2::text,$3::uuid,$4::text,$5::text,$6::text,$7::text,$8::text,$9::text,$10::uuid) AS r
)
SELECT (r).replica_id::uuid AS replica_id,(r).replica_kind::text AS replica_kind,(r).state::text AS state,
 COALESCE((r).desired_replicas,0::smallint)::smallint AS desired_replicas_value,((r).desired_replicas IS NOT NULL)::boolean AS desired_replicas_present,
 COALESCE((r).active_serving_replicas,0::smallint)::smallint AS active_serving_replicas_value,((r).active_serving_replicas IS NOT NULL)::boolean AS active_serving_replicas_present,
 COALESCE((r).active_maintenance_replicas,0::smallint)::smallint AS active_maintenance_replicas_value,((r).active_maintenance_replicas IS NOT NULL)::boolean AS active_maintenance_replicas_present,
 COALESCE((r).partition_1_enabled,false)::boolean AS partition_1_enabled_value,((r).partition_1_enabled IS NOT NULL)::boolean AS partition_1_enabled_present,
 COALESCE((r).partition_2_enabled,false)::boolean AS partition_2_enabled_value,((r).partition_2_enabled IS NOT NULL)::boolean AS partition_2_enabled_present,
 (r).capacity_generation::bigint AS capacity_generation,(r).controller_generation::bigint AS controller_generation,
 (r).controller_operation_id::text AS controller_operation_id,(r).admission_enabled::boolean AS admission_enabled,
 (r).lifecycle_phase::text AS lifecycle_phase,(r).replayed::boolean AS replayed FROM result
`

type RuntimeActivateReplicaCapacityParams struct {
	ExpectedControllerGeneration int64
	OperationID                  string
	ReplicaID                    uuid.UUID
	InstanceID                   string
	ContainerInstanceArn         string
	CaddyTaskArn                 string
	GoTaskArn                    string
	NuxtTaskArn                  string
	ReleaseDigest                string
	ReplacedReplicaID            *uuid.UUID
}

type RuntimeActivateReplicaCapacityRow struct {
	ReplicaID                        uuid.UUID
	ReplicaKind                      string
	State                            string
	DesiredReplicasValue             int16
	DesiredReplicasPresent           bool
	ActiveServingReplicasValue       int16
	ActiveServingReplicasPresent     bool
	ActiveMaintenanceReplicasValue   int16
	ActiveMaintenanceReplicasPresent bool
	Partition1EnabledValue           bool
	Partition1EnabledPresent         bool
	Partition2EnabledValue           bool
	Partition2EnabledPresent         bool
	CapacityGeneration               int64
	ControllerGeneration             int64
	ControllerOperationID            string
	AdmissionEnabled                 bool
	LifecyclePhase                   string
	Replayed                         bool
}

func (q *Queries) RuntimeActivateReplicaCapacity(ctx context.Context, arg RuntimeActivateReplicaCapacityParams) (RuntimeActivateReplicaCapacityRow, error) {
	row := q.db.QueryRow(ctx, runtimeActivateReplicaCapacity,
		arg.ExpectedControllerGeneration,
		arg.OperationID,
		arg.ReplicaID,
		arg.InstanceID,
		arg.ContainerInstanceArn,
		arg.CaddyTaskArn,
		arg.GoTaskArn,
		arg.NuxtTaskArn,
		arg.ReleaseDigest,
		arg.ReplacedReplicaID,
	)
	var i RuntimeActivateReplicaCapacityRow
	err := row.Scan(
		&i.ReplicaID,
		&i.ReplicaKind,
		&i.State,
		&i.DesiredReplicasValue,
		&i.DesiredReplicasPresent,
		&i.ActiveServingReplicasValue,
		&i.ActiveServingReplicasPresent,
		&i.ActiveMaintenanceReplicasValue,
		&i.ActiveMaintenanceReplicasPresent,
		&i.Partition1EnabledValue,
		&i.Partition1EnabledPresent,
		&i.Partition2EnabledValue,
		&i.Partition2EnabledPresent,
		&i.CapacityGeneration,
		&i.ControllerGeneration,
		&i.ControllerOperationID,
		&i.AdmissionEnabled,
		&i.LifecyclePhase,
		&i.Replayed,
	)
	return i, err
}

const runtimeBeginReplicaTermination = `-- name: RuntimeBeginReplicaTermination :one
WITH result AS MATERIALIZED (
 SELECT public.runtime_begin_replica_termination($1::bigint,$2::text,$3::text,$4::uuid,$5::text,$6::text,$7::text) AS r
)
SELECT (r).replica_id::uuid AS replica_id,(r).replica_kind::text AS replica_kind,(r).state::text AS state,
 COALESCE((r).desired_replicas,0::smallint)::smallint AS desired_replicas_value,((r).desired_replicas IS NOT NULL)::boolean AS desired_replicas_present,
 COALESCE((r).active_serving_replicas,0::smallint)::smallint AS active_serving_replicas_value,((r).active_serving_replicas IS NOT NULL)::boolean AS active_serving_replicas_present,
 COALESCE((r).active_maintenance_replicas,0::smallint)::smallint AS active_maintenance_replicas_value,((r).active_maintenance_replicas IS NOT NULL)::boolean AS active_maintenance_replicas_present,
 COALESCE((r).partition_1_enabled,false)::boolean AS partition_1_enabled_value,((r).partition_1_enabled IS NOT NULL)::boolean AS partition_1_enabled_present,
 COALESCE((r).partition_2_enabled,false)::boolean AS partition_2_enabled_value,((r).partition_2_enabled IS NOT NULL)::boolean AS partition_2_enabled_present,
 (r).capacity_generation::bigint AS capacity_generation,(r).controller_generation::bigint AS controller_generation,
 (r).controller_operation_id::text AS controller_operation_id,(r).admission_enabled::boolean AS admission_enabled,
 (r).lifecycle_phase::text AS lifecycle_phase,(r).replayed::boolean AS replayed FROM result
`

type RuntimeBeginReplicaTerminationParams struct {
	ExpectedControllerGeneration int64
	OperationID                  string
	RequestID                    string
	ReplicaID                    uuid.UUID
	InstanceID                   string
	ReleaseDigest                string
	Reason                       string
}

type RuntimeBeginReplicaTerminationRow struct {
	ReplicaID                        uuid.UUID
	ReplicaKind                      string
	State                            string
	DesiredReplicasValue             int16
	DesiredReplicasPresent           bool
	ActiveServingReplicasValue       int16
	ActiveServingReplicasPresent     bool
	ActiveMaintenanceReplicasValue   int16
	ActiveMaintenanceReplicasPresent bool
	Partition1EnabledValue           bool
	Partition1EnabledPresent         bool
	Partition2EnabledValue           bool
	Partition2EnabledPresent         bool
	CapacityGeneration               int64
	ControllerGeneration             int64
	ControllerOperationID            string
	AdmissionEnabled                 bool
	LifecyclePhase                   string
	Replayed                         bool
}

func (q *Queries) RuntimeBeginReplicaTermination(ctx context.Context, arg RuntimeBeginReplicaTerminationParams) (RuntimeBeginReplicaTerminationRow, error) {
	row := q.db.QueryRow(ctx, runtimeBeginReplicaTermination,
		arg.ExpectedControllerGeneration,
		arg.OperationID,
		arg.RequestID,
		arg.ReplicaID,
		arg.InstanceID,
		arg.ReleaseDigest,
		arg.Reason,
	)
	var i RuntimeBeginReplicaTerminationRow
	err := row.Scan(
		&i.ReplicaID,
		&i.ReplicaKind,
		&i.State,
		&i.DesiredReplicasValue,
		&i.DesiredReplicasPresent,
		&i.ActiveServingReplicasValue,
		&i.ActiveServingReplicasPresent,
		&i.ActiveMaintenanceReplicasValue,
		&i.ActiveMaintenanceReplicasPresent,
		&i.Partition1EnabledValue,
		&i.Partition1EnabledPresent,
		&i.Partition2EnabledValue,
		&i.Partition2EnabledPresent,
		&i.CapacityGeneration,
		&i.ControllerGeneration,
		&i.ControllerOperationID,
		&i.AdmissionEnabled,
		&i.LifecyclePhase,
		&i.Replayed,
	)
	return i, err
}

const runtimeFinishScaleIn = `-- name: RuntimeFinishScaleIn :one
WITH result AS MATERIALIZED (
 SELECT public.runtime_finish_scale_in($1::bigint,$2::text,$3::uuid,$4::text,$5::text,$6::text,$7::text) AS r
)
SELECT (r).replica_id::uuid AS replica_id,(r).replica_kind::text AS replica_kind,(r).state::text AS state,
 COALESCE((r).desired_replicas,0::smallint)::smallint AS desired_replicas_value,((r).desired_replicas IS NOT NULL)::boolean AS desired_replicas_present,
 COALESCE((r).active_serving_replicas,0::smallint)::smallint AS active_serving_replicas_value,((r).active_serving_replicas IS NOT NULL)::boolean AS active_serving_replicas_present,
 COALESCE((r).active_maintenance_replicas,0::smallint)::smallint AS active_maintenance_replicas_value,((r).active_maintenance_replicas IS NOT NULL)::boolean AS active_maintenance_replicas_present,
 COALESCE((r).partition_1_enabled,false)::boolean AS partition_1_enabled_value,((r).partition_1_enabled IS NOT NULL)::boolean AS partition_1_enabled_present,
 COALESCE((r).partition_2_enabled,false)::boolean AS partition_2_enabled_value,((r).partition_2_enabled IS NOT NULL)::boolean AS partition_2_enabled_present,
 (r).capacity_generation::bigint AS capacity_generation,(r).controller_generation::bigint AS controller_generation,
 (r).controller_operation_id::text AS controller_operation_id,(r).admission_enabled::boolean AS admission_enabled,
 (r).lifecycle_phase::text AS lifecycle_phase,(r).replayed::boolean AS replayed FROM result
`

type RuntimeFinishScaleInParams struct {
	ExpectedControllerGeneration int64
	OperationID                  string
	ReplicaID                    uuid.UUID
	InstanceID                   string
	ReleaseDigest                string
	LeaveOperationID             *string
	FencingEvidenceID            string
}

type RuntimeFinishScaleInRow struct {
	ReplicaID                        uuid.UUID
	ReplicaKind                      string
	State                            string
	DesiredReplicasValue             int16
	DesiredReplicasPresent           bool
	ActiveServingReplicasValue       int16
	ActiveServingReplicasPresent     bool
	ActiveMaintenanceReplicasValue   int16
	ActiveMaintenanceReplicasPresent bool
	Partition1EnabledValue           bool
	Partition1EnabledPresent         bool
	Partition2EnabledValue           bool
	Partition2EnabledPresent         bool
	CapacityGeneration               int64
	ControllerGeneration             int64
	ControllerOperationID            string
	AdmissionEnabled                 bool
	LifecyclePhase                   string
	Replayed                         bool
}

func (q *Queries) RuntimeFinishScaleIn(ctx context.Context, arg RuntimeFinishScaleInParams) (RuntimeFinishScaleInRow, error) {
	row := q.db.QueryRow(ctx, runtimeFinishScaleIn,
		arg.ExpectedControllerGeneration,
		arg.OperationID,
		arg.ReplicaID,
		arg.InstanceID,
		arg.ReleaseDigest,
		arg.LeaveOperationID,
		arg.FencingEvidenceID,
	)
	var i RuntimeFinishScaleInRow
	err := row.Scan(
		&i.ReplicaID,
		&i.ReplicaKind,
		&i.State,
		&i.DesiredReplicasValue,
		&i.DesiredReplicasPresent,
		&i.ActiveServingReplicasValue,
		&i.ActiveServingReplicasPresent,
		&i.ActiveMaintenanceReplicasValue,
		&i.ActiveMaintenanceReplicasPresent,
		&i.Partition1EnabledValue,
		&i.Partition1EnabledPresent,
		&i.Partition2EnabledValue,
		&i.Partition2EnabledPresent,
		&i.CapacityGeneration,
		&i.ControllerGeneration,
		&i.ControllerOperationID,
		&i.AdmissionEnabled,
		&i.LifecyclePhase,
		&i.Replayed,
	)
	return i, err
}

const runtimePrepareMaintenanceDrain = `-- name: RuntimePrepareMaintenanceDrain :one
WITH result AS MATERIALIZED (
 SELECT public.runtime_prepare_maintenance_drain($1::bigint,$2::text,$3::uuid,$4::text,$5::text) AS r
)
SELECT (r).replica_id::uuid AS replica_id,(r).replica_kind::text AS replica_kind,(r).state::text AS state,
 COALESCE((r).desired_replicas,0::smallint)::smallint AS desired_replicas_value,((r).desired_replicas IS NOT NULL)::boolean AS desired_replicas_present,
 COALESCE((r).active_serving_replicas,0::smallint)::smallint AS active_serving_replicas_value,((r).active_serving_replicas IS NOT NULL)::boolean AS active_serving_replicas_present,
 COALESCE((r).active_maintenance_replicas,0::smallint)::smallint AS active_maintenance_replicas_value,((r).active_maintenance_replicas IS NOT NULL)::boolean AS active_maintenance_replicas_present,
 COALESCE((r).partition_1_enabled,false)::boolean AS partition_1_enabled_value,((r).partition_1_enabled IS NOT NULL)::boolean AS partition_1_enabled_present,
 COALESCE((r).partition_2_enabled,false)::boolean AS partition_2_enabled_value,((r).partition_2_enabled IS NOT NULL)::boolean AS partition_2_enabled_present,
 (r).capacity_generation::bigint AS capacity_generation,(r).controller_generation::bigint AS controller_generation,
 (r).controller_operation_id::text AS controller_operation_id,(r).admission_enabled::boolean AS admission_enabled,
 (r).lifecycle_phase::text AS lifecycle_phase,(r).replayed::boolean AS replayed FROM result
`

type RuntimePrepareMaintenanceDrainParams struct {
	ExpectedControllerGeneration int64
	OperationID                  string
	ReplicaID                    uuid.UUID
	InstanceID                   string
	ReleaseDigest                string
}

type RuntimePrepareMaintenanceDrainRow struct {
	ReplicaID                        uuid.UUID
	ReplicaKind                      string
	State                            string
	DesiredReplicasValue             int16
	DesiredReplicasPresent           bool
	ActiveServingReplicasValue       int16
	ActiveServingReplicasPresent     bool
	ActiveMaintenanceReplicasValue   int16
	ActiveMaintenanceReplicasPresent bool
	Partition1EnabledValue           bool
	Partition1EnabledPresent         bool
	Partition2EnabledValue           bool
	Partition2EnabledPresent         bool
	CapacityGeneration               int64
	ControllerGeneration             int64
	ControllerOperationID            string
	AdmissionEnabled                 bool
	LifecyclePhase                   string
	Replayed                         bool
}

func (q *Queries) RuntimePrepareMaintenanceDrain(ctx context.Context, arg RuntimePrepareMaintenanceDrainParams) (RuntimePrepareMaintenanceDrainRow, error) {
	row := q.db.QueryRow(ctx, runtimePrepareMaintenanceDrain,
		arg.ExpectedControllerGeneration,
		arg.OperationID,
		arg.ReplicaID,
		arg.InstanceID,
		arg.ReleaseDigest,
	)
	var i RuntimePrepareMaintenanceDrainRow
	err := row.Scan(
		&i.ReplicaID,
		&i.ReplicaKind,
		&i.State,
		&i.DesiredReplicasValue,
		&i.DesiredReplicasPresent,
		&i.ActiveServingReplicasValue,
		&i.ActiveServingReplicasPresent,
		&i.ActiveMaintenanceReplicasValue,
		&i.ActiveMaintenanceReplicasPresent,
		&i.Partition1EnabledValue,
		&i.Partition1EnabledPresent,
		&i.Partition2EnabledValue,
		&i.Partition2EnabledPresent,
		&i.CapacityGeneration,
		&i.ControllerGeneration,
		&i.ControllerOperationID,
		&i.AdmissionEnabled,
		&i.LifecyclePhase,
		&i.Replayed,
	)
	return i, err
}

const runtimePrepareScaleIn = `-- name: RuntimePrepareScaleIn :one
WITH result AS MATERIALIZED (
 SELECT public.runtime_prepare_scale_in($1::bigint,$2::text,$3::uuid,$4::text,$5::text) AS r
)
SELECT (r).replica_id::uuid AS replica_id,(r).replica_kind::text AS replica_kind,(r).state::text AS state,
 COALESCE((r).desired_replicas,0::smallint)::smallint AS desired_replicas_value,((r).desired_replicas IS NOT NULL)::boolean AS desired_replicas_present,
 COALESCE((r).active_serving_replicas,0::smallint)::smallint AS active_serving_replicas_value,((r).active_serving_replicas IS NOT NULL)::boolean AS active_serving_replicas_present,
 COALESCE((r).active_maintenance_replicas,0::smallint)::smallint AS active_maintenance_replicas_value,((r).active_maintenance_replicas IS NOT NULL)::boolean AS active_maintenance_replicas_present,
 COALESCE((r).partition_1_enabled,false)::boolean AS partition_1_enabled_value,((r).partition_1_enabled IS NOT NULL)::boolean AS partition_1_enabled_present,
 COALESCE((r).partition_2_enabled,false)::boolean AS partition_2_enabled_value,((r).partition_2_enabled IS NOT NULL)::boolean AS partition_2_enabled_present,
 (r).capacity_generation::bigint AS capacity_generation,(r).controller_generation::bigint AS controller_generation,
 (r).controller_operation_id::text AS controller_operation_id,(r).admission_enabled::boolean AS admission_enabled,
 (r).lifecycle_phase::text AS lifecycle_phase,(r).replayed::boolean AS replayed FROM result
`

type RuntimePrepareScaleInParams struct {
	ExpectedControllerGeneration int64
	OperationID                  string
	ReplicaID                    uuid.UUID
	InstanceID                   string
	ReleaseDigest                string
}

type RuntimePrepareScaleInRow struct {
	ReplicaID                        uuid.UUID
	ReplicaKind                      string
	State                            string
	DesiredReplicasValue             int16
	DesiredReplicasPresent           bool
	ActiveServingReplicasValue       int16
	ActiveServingReplicasPresent     bool
	ActiveMaintenanceReplicasValue   int16
	ActiveMaintenanceReplicasPresent bool
	Partition1EnabledValue           bool
	Partition1EnabledPresent         bool
	Partition2EnabledValue           bool
	Partition2EnabledPresent         bool
	CapacityGeneration               int64
	ControllerGeneration             int64
	ControllerOperationID            string
	AdmissionEnabled                 bool
	LifecyclePhase                   string
	Replayed                         bool
}

func (q *Queries) RuntimePrepareScaleIn(ctx context.Context, arg RuntimePrepareScaleInParams) (RuntimePrepareScaleInRow, error) {
	row := q.db.QueryRow(ctx, runtimePrepareScaleIn,
		arg.ExpectedControllerGeneration,
		arg.OperationID,
		arg.ReplicaID,
		arg.InstanceID,
		arg.ReleaseDigest,
	)
	var i RuntimePrepareScaleInRow
	err := row.Scan(
		&i.ReplicaID,
		&i.ReplicaKind,
		&i.State,
		&i.DesiredReplicasValue,
		&i.DesiredReplicasPresent,
		&i.ActiveServingReplicasValue,
		&i.ActiveServingReplicasPresent,
		&i.ActiveMaintenanceReplicasValue,
		&i.ActiveMaintenanceReplicasPresent,
		&i.Partition1EnabledValue,
		&i.Partition1EnabledPresent,
		&i.Partition2EnabledValue,
		&i.Partition2EnabledPresent,
		&i.CapacityGeneration,
		&i.ControllerGeneration,
		&i.ControllerOperationID,
		&i.AdmissionEnabled,
		&i.LifecyclePhase,
		&i.Replayed,
	)
	return i, err
}

const runtimePrepareScaleOut = `-- name: RuntimePrepareScaleOut :one
WITH result AS MATERIALIZED (
 SELECT public.runtime_prepare_scale_out($1::bigint,$2::text) AS r
)
SELECT (r).desired_replicas::smallint AS desired_replicas,
 (r).active_serving_replicas::smallint AS active_serving_replicas,
 (r).active_maintenance_replicas::smallint AS active_maintenance_replicas,
 (r).partition_1_enabled::boolean AS partition_1_enabled,(r).partition_2_enabled::boolean AS partition_2_enabled,
 (r).capacity_generation::bigint AS capacity_generation,(r).controller_generation::bigint AS controller_generation,
 (r).controller_operation_id::text AS controller_operation_id,(r).admission_enabled::boolean AS admission_enabled,
 (r).lifecycle_phase::text AS lifecycle_phase,
 COALESCE((r).write_gate,''::text)::text AS write_gate_value,((r).write_gate IS NOT NULL)::boolean AS write_gate_present,
 COALESCE((r).write_generation,0::bigint)::bigint AS write_generation_value,((r).write_generation IS NOT NULL)::boolean AS write_generation_present,
 (r).replayed::boolean AS replayed FROM result
`

type RuntimePrepareScaleOutParams struct {
	ExpectedControllerGeneration int64
	OperationID                  string
}

type RuntimePrepareScaleOutRow struct {
	DesiredReplicas           int16
	ActiveServingReplicas     int16
	ActiveMaintenanceReplicas int16
	Partition1Enabled         bool
	Partition2Enabled         bool
	CapacityGeneration        int64
	ControllerGeneration      int64
	ControllerOperationID     string
	AdmissionEnabled          bool
	LifecyclePhase            string
	WriteGateValue            string
	WriteGatePresent          bool
	WriteGenerationValue      int64
	WriteGenerationPresent    bool
	Replayed                  bool
}

func (q *Queries) RuntimePrepareScaleOut(ctx context.Context, arg RuntimePrepareScaleOutParams) (RuntimePrepareScaleOutRow, error) {
	row := q.db.QueryRow(ctx, runtimePrepareScaleOut, arg.ExpectedControllerGeneration, arg.OperationID)
	var i RuntimePrepareScaleOutRow
	err := row.Scan(
		&i.DesiredReplicas,
		&i.ActiveServingReplicas,
		&i.ActiveMaintenanceReplicas,
		&i.Partition1Enabled,
		&i.Partition2Enabled,
		&i.CapacityGeneration,
		&i.ControllerGeneration,
		&i.ControllerOperationID,
		&i.AdmissionEnabled,
		&i.LifecyclePhase,
		&i.WriteGateValue,
		&i.WriteGatePresent,
		&i.WriteGenerationValue,
		&i.WriteGenerationPresent,
		&i.Replayed,
	)
	return i, err
}
