// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_claims.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const runtimeAcquireSSEClaim = `-- name: RuntimeAcquireSSEClaim :one
WITH result AS MATERIALIZED (SELECT public.runtime_acquire_sse_claim($1::uuid,$2::uuid,$3::bytea,$4::bytea) AS r)
SELECT
  (result.r).outcome::text AS outcome,
  (result.r).claim_id::uuid AS claim_id,
  COALESCE((result.r).policy_id,''::text)::text AS policy_id_value, ((result.r).policy_id IS NOT NULL)::boolean AS policy_id_present,
  COALESCE((result.r).replica_id,'00000000-0000-0000-0000-000000000000'::uuid)::uuid AS replica_id_value, ((result.r).replica_id IS NOT NULL)::boolean AS replica_id_present,
  COALESCE((result.r).work_id,'00000000-0000-0000-0000-000000000000'::uuid)::uuid AS work_id_value, ((result.r).work_id IS NOT NULL)::boolean AS work_id_present,
  COALESCE((result.r).state,''::text)::text AS state_value, ((result.r).state IS NOT NULL)::boolean AS state_present,
  COALESCE((result.r).admitted_at,'1970-01-01 UTC'::timestamptz)::timestamptz AS admitted_at_value, ((result.r).admitted_at IS NOT NULL)::boolean AS admitted_at_present,
  COALESCE((result.r).deadline_at,'1970-01-01 UTC'::timestamptz)::timestamptz AS deadline_at_value, ((result.r).deadline_at IS NOT NULL)::boolean AS deadline_at_present,
  COALESCE((result.r).released_at,'1970-01-01 UTC'::timestamptz)::timestamptz AS released_at_value, ((result.r).released_at IS NOT NULL)::boolean AS released_at_present,
  COALESCE((result.r).release_reason,''::text)::text AS release_reason_value, ((result.r).release_reason IS NOT NULL)::boolean AS release_reason_present,
  COALESCE((result.r).request_digest,''::bytea)::bytea AS request_digest_value, ((result.r).request_digest IS NOT NULL)::boolean AS request_digest_present,
  COALESCE((result.r).scope_count,0::smallint)::smallint AS scope_count_value, ((result.r).scope_count IS NOT NULL)::boolean AS scope_count_present,
  COALESCE((result.r).scope_1_kind,''::text)::text AS scope_1_kind_value, ((result.r).scope_1_kind IS NOT NULL)::boolean AS scope_1_kind_present,
  COALESCE((result.r).scope_1_digest,''::bytea)::bytea AS scope_1_digest_value, ((result.r).scope_1_digest IS NOT NULL)::boolean AS scope_1_digest_present,
  COALESCE((result.r).scope_1_allocation_ordinal,0::bigint)::bigint AS scope_1_allocation_ordinal_value, ((result.r).scope_1_allocation_ordinal IS NOT NULL)::boolean AS scope_1_allocation_ordinal_present,
  COALESCE((result.r).scope_2_kind,''::text)::text AS scope_2_kind_value, ((result.r).scope_2_kind IS NOT NULL)::boolean AS scope_2_kind_present,
  COALESCE((result.r).scope_2_digest,''::bytea)::bytea AS scope_2_digest_value, ((result.r).scope_2_digest IS NOT NULL)::boolean AS scope_2_digest_present,
  COALESCE((result.r).scope_2_allocation_ordinal,0::bigint)::bigint AS scope_2_allocation_ordinal_value, ((result.r).scope_2_allocation_ordinal IS NOT NULL)::boolean AS scope_2_allocation_ordinal_present
FROM result
`

type RuntimeAcquireSSEClaimParams struct {
	ClaimID       uuid.UUID
	ReplicaID     uuid.UUID
	IpDigest      []byte
	AccountDigest []byte
}

type RuntimeAcquireSSEClaimRow struct {
	Outcome                        string
	ClaimID                        uuid.UUID
	PolicyIDValue                  string
	PolicyIDPresent                bool
	ReplicaIDValue                 uuid.UUID
	ReplicaIDPresent               bool
	WorkIDValue                    uuid.UUID
	WorkIDPresent                  bool
	StateValue                     string
	StatePresent                   bool
	AdmittedAtValue                time.Time
	AdmittedAtPresent              bool
	DeadlineAtValue                time.Time
	DeadlineAtPresent              bool
	ReleasedAtValue                time.Time
	ReleasedAtPresent              bool
	ReleaseReasonValue             string
	ReleaseReasonPresent           bool
	RequestDigestValue             []byte
	RequestDigestPresent           bool
	ScopeCountValue                int16
	ScopeCountPresent              bool
	Scope1KindValue                string
	Scope1KindPresent              bool
	Scope1DigestValue              []byte
	Scope1DigestPresent            bool
	Scope1AllocationOrdinalValue   int64
	Scope1AllocationOrdinalPresent bool
	Scope2KindValue                string
	Scope2KindPresent              bool
	Scope2DigestValue              []byte
	Scope2DigestPresent            bool
	Scope2AllocationOrdinalValue   int64
	Scope2AllocationOrdinalPresent bool
}

func (q *Queries) RuntimeAcquireSSEClaim(ctx context.Context, arg RuntimeAcquireSSEClaimParams) (RuntimeAcquireSSEClaimRow, error) {
	row := q.db.QueryRow(ctx, runtimeAcquireSSEClaim,
		arg.ClaimID,
		arg.ReplicaID,
		arg.IpDigest,
		arg.AccountDigest,
	)
	var i RuntimeAcquireSSEClaimRow
	err := row.Scan(
		&i.Outcome,
		&i.ClaimID,
		&i.PolicyIDValue,
		&i.PolicyIDPresent,
		&i.ReplicaIDValue,
		&i.ReplicaIDPresent,
		&i.WorkIDValue,
		&i.WorkIDPresent,
		&i.StateValue,
		&i.StatePresent,
		&i.AdmittedAtValue,
		&i.AdmittedAtPresent,
		&i.DeadlineAtValue,
		&i.DeadlineAtPresent,
		&i.ReleasedAtValue,
		&i.ReleasedAtPresent,
		&i.ReleaseReasonValue,
		&i.ReleaseReasonPresent,
		&i.RequestDigestValue,
		&i.RequestDigestPresent,
		&i.ScopeCountValue,
		&i.ScopeCountPresent,
		&i.Scope1KindValue,
		&i.Scope1KindPresent,
		&i.Scope1DigestValue,
		&i.Scope1DigestPresent,
		&i.Scope1AllocationOrdinalValue,
		&i.Scope1AllocationOrdinalPresent,
		&i.Scope2KindValue,
		&i.Scope2KindPresent,
		&i.Scope2DigestValue,
		&i.Scope2DigestPresent,
		&i.Scope2AllocationOrdinalValue,
		&i.Scope2AllocationOrdinalPresent,
	)
	return i, err
}

const runtimeAcquireSingleClaim = `-- name: RuntimeAcquireSingleClaim :one
WITH result AS MATERIALIZED (SELECT public.runtime_acquire_single_claim($1::uuid,$2::text,$3::uuid,$4::uuid,$5::text,$6::bytea) AS r)
SELECT
  (result.r).outcome::text AS outcome,
  (result.r).claim_id::uuid AS claim_id,
  COALESCE((result.r).policy_id,''::text)::text AS policy_id_value, ((result.r).policy_id IS NOT NULL)::boolean AS policy_id_present,
  COALESCE((result.r).replica_id,'00000000-0000-0000-0000-000000000000'::uuid)::uuid AS replica_id_value, ((result.r).replica_id IS NOT NULL)::boolean AS replica_id_present,
  COALESCE((result.r).work_id,'00000000-0000-0000-0000-000000000000'::uuid)::uuid AS work_id_value, ((result.r).work_id IS NOT NULL)::boolean AS work_id_present,
  COALESCE((result.r).state,''::text)::text AS state_value, ((result.r).state IS NOT NULL)::boolean AS state_present,
  COALESCE((result.r).admitted_at,'1970-01-01 UTC'::timestamptz)::timestamptz AS admitted_at_value, ((result.r).admitted_at IS NOT NULL)::boolean AS admitted_at_present,
  COALESCE((result.r).deadline_at,'1970-01-01 UTC'::timestamptz)::timestamptz AS deadline_at_value, ((result.r).deadline_at IS NOT NULL)::boolean AS deadline_at_present,
  COALESCE((result.r).released_at,'1970-01-01 UTC'::timestamptz)::timestamptz AS released_at_value, ((result.r).released_at IS NOT NULL)::boolean AS released_at_present,
  COALESCE((result.r).release_reason,''::text)::text AS release_reason_value, ((result.r).release_reason IS NOT NULL)::boolean AS release_reason_present,
  COALESCE((result.r).request_digest,''::bytea)::bytea AS request_digest_value, ((result.r).request_digest IS NOT NULL)::boolean AS request_digest_present,
  COALESCE((result.r).scope_count,0::smallint)::smallint AS scope_count_value, ((result.r).scope_count IS NOT NULL)::boolean AS scope_count_present,
  COALESCE((result.r).scope_1_kind,''::text)::text AS scope_1_kind_value, ((result.r).scope_1_kind IS NOT NULL)::boolean AS scope_1_kind_present,
  COALESCE((result.r).scope_1_digest,''::bytea)::bytea AS scope_1_digest_value, ((result.r).scope_1_digest IS NOT NULL)::boolean AS scope_1_digest_present,
  COALESCE((result.r).scope_1_allocation_ordinal,0::bigint)::bigint AS scope_1_allocation_ordinal_value, ((result.r).scope_1_allocation_ordinal IS NOT NULL)::boolean AS scope_1_allocation_ordinal_present,
  COALESCE((result.r).scope_2_kind,''::text)::text AS scope_2_kind_value, ((result.r).scope_2_kind IS NOT NULL)::boolean AS scope_2_kind_present,
  COALESCE((result.r).scope_2_digest,''::bytea)::bytea AS scope_2_digest_value, ((result.r).scope_2_digest IS NOT NULL)::boolean AS scope_2_digest_present,
  COALESCE((result.r).scope_2_allocation_ordinal,0::bigint)::bigint AS scope_2_allocation_ordinal_value, ((result.r).scope_2_allocation_ordinal IS NOT NULL)::boolean AS scope_2_allocation_ordinal_present
FROM result
`

type RuntimeAcquireSingleClaimParams struct {
	ClaimID     uuid.UUID
	PolicyID    string
	ReplicaID   uuid.UUID
	WorkID      *uuid.UUID
	ScopeKind   string
	ScopeDigest []byte
}

type RuntimeAcquireSingleClaimRow struct {
	Outcome                        string
	ClaimID                        uuid.UUID
	PolicyIDValue                  string
	PolicyIDPresent                bool
	ReplicaIDValue                 uuid.UUID
	ReplicaIDPresent               bool
	WorkIDValue                    uuid.UUID
	WorkIDPresent                  bool
	StateValue                     string
	StatePresent                   bool
	AdmittedAtValue                time.Time
	AdmittedAtPresent              bool
	DeadlineAtValue                time.Time
	DeadlineAtPresent              bool
	ReleasedAtValue                time.Time
	ReleasedAtPresent              bool
	ReleaseReasonValue             string
	ReleaseReasonPresent           bool
	RequestDigestValue             []byte
	RequestDigestPresent           bool
	ScopeCountValue                int16
	ScopeCountPresent              bool
	Scope1KindValue                string
	Scope1KindPresent              bool
	Scope1DigestValue              []byte
	Scope1DigestPresent            bool
	Scope1AllocationOrdinalValue   int64
	Scope1AllocationOrdinalPresent bool
	Scope2KindValue                string
	Scope2KindPresent              bool
	Scope2DigestValue              []byte
	Scope2DigestPresent            bool
	Scope2AllocationOrdinalValue   int64
	Scope2AllocationOrdinalPresent bool
}

func (q *Queries) RuntimeAcquireSingleClaim(ctx context.Context, arg RuntimeAcquireSingleClaimParams) (RuntimeAcquireSingleClaimRow, error) {
	row := q.db.QueryRow(ctx, runtimeAcquireSingleClaim,
		arg.ClaimID,
		arg.PolicyID,
		arg.ReplicaID,
		arg.WorkID,
		arg.ScopeKind,
		arg.ScopeDigest,
	)
	var i RuntimeAcquireSingleClaimRow
	err := row.Scan(
		&i.Outcome,
		&i.ClaimID,
		&i.PolicyIDValue,
		&i.PolicyIDPresent,
		&i.ReplicaIDValue,
		&i.ReplicaIDPresent,
		&i.WorkIDValue,
		&i.WorkIDPresent,
		&i.StateValue,
		&i.StatePresent,
		&i.AdmittedAtValue,
		&i.AdmittedAtPresent,
		&i.DeadlineAtValue,
		&i.DeadlineAtPresent,
		&i.ReleasedAtValue,
		&i.ReleasedAtPresent,
		&i.ReleaseReasonValue,
		&i.ReleaseReasonPresent,
		&i.RequestDigestValue,
		&i.RequestDigestPresent,
		&i.ScopeCountValue,
		&i.ScopeCountPresent,
		&i.Scope1KindValue,
		&i.Scope1KindPresent,
		&i.Scope1DigestValue,
		&i.Scope1DigestPresent,
		&i.Scope1AllocationOrdinalValue,
		&i.Scope1AllocationOrdinalPresent,
		&i.Scope2KindValue,
		&i.Scope2KindPresent,
		&i.Scope2DigestValue,
		&i.Scope2DigestPresent,
		&i.Scope2AllocationOrdinalValue,
		&i.Scope2AllocationOrdinalPresent,
	)
	return i, err
}

const runtimeGCReleasedClaimReceipts = `-- name: RuntimeGCReleasedClaimReceipts :one
WITH result AS MATERIALIZED (
  SELECT gc FROM public.runtime_gc_released_claim_receipts() AS gc
)
SELECT (result.gc).deleted_claim_count::integer AS deleted_claim_count,
  (result.gc).deleted_scope_summary_count::integer AS deleted_scope_summary_count
FROM result
`

type RuntimeGCReleasedClaimReceiptsRow struct {
	DeletedClaimCount        int32
	DeletedScopeSummaryCount int32
}

func (q *Queries) RuntimeGCReleasedClaimReceipts(ctx context.Context) (RuntimeGCReleasedClaimReceiptsRow, error) {
	row := q.db.QueryRow(ctx, runtimeGCReleasedClaimReceipts)
	var i RuntimeGCReleasedClaimReceiptsRow
	err := row.Scan(&i.DeletedClaimCount, &i.DeletedScopeSummaryCount)
	return i, err
}

const runtimePromoteClaim = `-- name: RuntimePromoteClaim :one
WITH result AS MATERIALIZED (SELECT public.runtime_promote_claim($1::uuid,$2::uuid,$3::bytea) AS r)
SELECT
  (result.r).outcome::text AS outcome,
  (result.r).claim_id::uuid AS claim_id,
  COALESCE((result.r).policy_id,''::text)::text AS policy_id_value, ((result.r).policy_id IS NOT NULL)::boolean AS policy_id_present,
  COALESCE((result.r).replica_id,'00000000-0000-0000-0000-000000000000'::uuid)::uuid AS replica_id_value, ((result.r).replica_id IS NOT NULL)::boolean AS replica_id_present,
  COALESCE((result.r).work_id,'00000000-0000-0000-0000-000000000000'::uuid)::uuid AS work_id_value, ((result.r).work_id IS NOT NULL)::boolean AS work_id_present,
  COALESCE((result.r).state,''::text)::text AS state_value, ((result.r).state IS NOT NULL)::boolean AS state_present,
  COALESCE((result.r).admitted_at,'1970-01-01 UTC'::timestamptz)::timestamptz AS admitted_at_value, ((result.r).admitted_at IS NOT NULL)::boolean AS admitted_at_present,
  COALESCE((result.r).deadline_at,'1970-01-01 UTC'::timestamptz)::timestamptz AS deadline_at_value, ((result.r).deadline_at IS NOT NULL)::boolean AS deadline_at_present,
  COALESCE((result.r).released_at,'1970-01-01 UTC'::timestamptz)::timestamptz AS released_at_value, ((result.r).released_at IS NOT NULL)::boolean AS released_at_present,
  COALESCE((result.r).release_reason,''::text)::text AS release_reason_value, ((result.r).release_reason IS NOT NULL)::boolean AS release_reason_present,
  COALESCE((result.r).request_digest,''::bytea)::bytea AS request_digest_value, ((result.r).request_digest IS NOT NULL)::boolean AS request_digest_present,
  COALESCE((result.r).scope_count,0::smallint)::smallint AS scope_count_value, ((result.r).scope_count IS NOT NULL)::boolean AS scope_count_present,
  COALESCE((result.r).scope_1_kind,''::text)::text AS scope_1_kind_value, ((result.r).scope_1_kind IS NOT NULL)::boolean AS scope_1_kind_present,
  COALESCE((result.r).scope_1_digest,''::bytea)::bytea AS scope_1_digest_value, ((result.r).scope_1_digest IS NOT NULL)::boolean AS scope_1_digest_present,
  COALESCE((result.r).scope_1_allocation_ordinal,0::bigint)::bigint AS scope_1_allocation_ordinal_value, ((result.r).scope_1_allocation_ordinal IS NOT NULL)::boolean AS scope_1_allocation_ordinal_present,
  COALESCE((result.r).scope_2_kind,''::text)::text AS scope_2_kind_value, ((result.r).scope_2_kind IS NOT NULL)::boolean AS scope_2_kind_present,
  COALESCE((result.r).scope_2_digest,''::bytea)::bytea AS scope_2_digest_value, ((result.r).scope_2_digest IS NOT NULL)::boolean AS scope_2_digest_present,
  COALESCE((result.r).scope_2_allocation_ordinal,0::bigint)::bigint AS scope_2_allocation_ordinal_value, ((result.r).scope_2_allocation_ordinal IS NOT NULL)::boolean AS scope_2_allocation_ordinal_present
FROM result
`

type RuntimePromoteClaimParams struct {
	ClaimID           uuid.UUID
	ExpectedReplicaID uuid.UUID
	RequestDigest     []byte
}

type RuntimePromoteClaimRow struct {
	Outcome                        string
	ClaimID                        uuid.UUID
	PolicyIDValue                  string
	PolicyIDPresent                bool
	ReplicaIDValue                 uuid.UUID
	ReplicaIDPresent               bool
	WorkIDValue                    uuid.UUID
	WorkIDPresent                  bool
	StateValue                     string
	StatePresent                   bool
	AdmittedAtValue                time.Time
	AdmittedAtPresent              bool
	DeadlineAtValue                time.Time
	DeadlineAtPresent              bool
	ReleasedAtValue                time.Time
	ReleasedAtPresent              bool
	ReleaseReasonValue             string
	ReleaseReasonPresent           bool
	RequestDigestValue             []byte
	RequestDigestPresent           bool
	ScopeCountValue                int16
	ScopeCountPresent              bool
	Scope1KindValue                string
	Scope1KindPresent              bool
	Scope1DigestValue              []byte
	Scope1DigestPresent            bool
	Scope1AllocationOrdinalValue   int64
	Scope1AllocationOrdinalPresent bool
	Scope2KindValue                string
	Scope2KindPresent              bool
	Scope2DigestValue              []byte
	Scope2DigestPresent            bool
	Scope2AllocationOrdinalValue   int64
	Scope2AllocationOrdinalPresent bool
}

func (q *Queries) RuntimePromoteClaim(ctx context.Context, arg RuntimePromoteClaimParams) (RuntimePromoteClaimRow, error) {
	row := q.db.QueryRow(ctx, runtimePromoteClaim, arg.ClaimID, arg.ExpectedReplicaID, arg.RequestDigest)
	var i RuntimePromoteClaimRow
	err := row.Scan(
		&i.Outcome,
		&i.ClaimID,
		&i.PolicyIDValue,
		&i.PolicyIDPresent,
		&i.ReplicaIDValue,
		&i.ReplicaIDPresent,
		&i.WorkIDValue,
		&i.WorkIDPresent,
		&i.StateValue,
		&i.StatePresent,
		&i.AdmittedAtValue,
		&i.AdmittedAtPresent,
		&i.DeadlineAtValue,
		&i.DeadlineAtPresent,
		&i.ReleasedAtValue,
		&i.ReleasedAtPresent,
		&i.ReleaseReasonValue,
		&i.ReleaseReasonPresent,
		&i.RequestDigestValue,
		&i.RequestDigestPresent,
		&i.ScopeCountValue,
		&i.ScopeCountPresent,
		&i.Scope1KindValue,
		&i.Scope1KindPresent,
		&i.Scope1DigestValue,
		&i.Scope1DigestPresent,
		&i.Scope1AllocationOrdinalValue,
		&i.Scope1AllocationOrdinalPresent,
		&i.Scope2KindValue,
		&i.Scope2KindPresent,
		&i.Scope2DigestValue,
		&i.Scope2DigestPresent,
		&i.Scope2AllocationOrdinalValue,
		&i.Scope2AllocationOrdinalPresent,
	)
	return i, err
}

const runtimeReleaseClaim = `-- name: RuntimeReleaseClaim :one
WITH result AS MATERIALIZED (SELECT public.runtime_release_claim($1::uuid,$2::uuid,$3::bytea,$4::text) AS r)
SELECT
  (result.r).outcome::text AS outcome,
  (result.r).claim_id::uuid AS claim_id,
  COALESCE((result.r).policy_id,''::text)::text AS policy_id_value, ((result.r).policy_id IS NOT NULL)::boolean AS policy_id_present,
  COALESCE((result.r).replica_id,'00000000-0000-0000-0000-000000000000'::uuid)::uuid AS replica_id_value, ((result.r).replica_id IS NOT NULL)::boolean AS replica_id_present,
  COALESCE((result.r).work_id,'00000000-0000-0000-0000-000000000000'::uuid)::uuid AS work_id_value, ((result.r).work_id IS NOT NULL)::boolean AS work_id_present,
  COALESCE((result.r).state,''::text)::text AS state_value, ((result.r).state IS NOT NULL)::boolean AS state_present,
  COALESCE((result.r).admitted_at,'1970-01-01 UTC'::timestamptz)::timestamptz AS admitted_at_value, ((result.r).admitted_at IS NOT NULL)::boolean AS admitted_at_present,
  COALESCE((result.r).deadline_at,'1970-01-01 UTC'::timestamptz)::timestamptz AS deadline_at_value, ((result.r).deadline_at IS NOT NULL)::boolean AS deadline_at_present,
  COALESCE((result.r).released_at,'1970-01-01 UTC'::timestamptz)::timestamptz AS released_at_value, ((result.r).released_at IS NOT NULL)::boolean AS released_at_present,
  COALESCE((result.r).release_reason,''::text)::text AS release_reason_value, ((result.r).release_reason IS NOT NULL)::boolean AS release_reason_present,
  COALESCE((result.r).request_digest,''::bytea)::bytea AS request_digest_value, ((result.r).request_digest IS NOT NULL)::boolean AS request_digest_present,
  COALESCE((result.r).scope_count,0::smallint)::smallint AS scope_count_value, ((result.r).scope_count IS NOT NULL)::boolean AS scope_count_present,
  COALESCE((result.r).scope_1_kind,''::text)::text AS scope_1_kind_value, ((result.r).scope_1_kind IS NOT NULL)::boolean AS scope_1_kind_present,
  COALESCE((result.r).scope_1_digest,''::bytea)::bytea AS scope_1_digest_value, ((result.r).scope_1_digest IS NOT NULL)::boolean AS scope_1_digest_present,
  COALESCE((result.r).scope_1_allocation_ordinal,0::bigint)::bigint AS scope_1_allocation_ordinal_value, ((result.r).scope_1_allocation_ordinal IS NOT NULL)::boolean AS scope_1_allocation_ordinal_present,
  COALESCE((result.r).scope_2_kind,''::text)::text AS scope_2_kind_value, ((result.r).scope_2_kind IS NOT NULL)::boolean AS scope_2_kind_present,
  COALESCE((result.r).scope_2_digest,''::bytea)::bytea AS scope_2_digest_value, ((result.r).scope_2_digest IS NOT NULL)::boolean AS scope_2_digest_present,
  COALESCE((result.r).scope_2_allocation_ordinal,0::bigint)::bigint AS scope_2_allocation_ordinal_value, ((result.r).scope_2_allocation_ordinal IS NOT NULL)::boolean AS scope_2_allocation_ordinal_present
FROM result
`

type RuntimeReleaseClaimParams struct {
	ClaimID           uuid.UUID
	ExpectedReplicaID uuid.UUID
	RequestDigest     []byte
	Reason            string
}

type RuntimeReleaseClaimRow struct {
	Outcome                        string
	ClaimID                        uuid.UUID
	PolicyIDValue                  string
	PolicyIDPresent                bool
	ReplicaIDValue                 uuid.UUID
	ReplicaIDPresent               bool
	WorkIDValue                    uuid.UUID
	WorkIDPresent                  bool
	StateValue                     string
	StatePresent                   bool
	AdmittedAtValue                time.Time
	AdmittedAtPresent              bool
	DeadlineAtValue                time.Time
	DeadlineAtPresent              bool
	ReleasedAtValue                time.Time
	ReleasedAtPresent              bool
	ReleaseReasonValue             string
	ReleaseReasonPresent           bool
	RequestDigestValue             []byte
	RequestDigestPresent           bool
	ScopeCountValue                int16
	ScopeCountPresent              bool
	Scope1KindValue                string
	Scope1KindPresent              bool
	Scope1DigestValue              []byte
	Scope1DigestPresent            bool
	Scope1AllocationOrdinalValue   int64
	Scope1AllocationOrdinalPresent bool
	Scope2KindValue                string
	Scope2KindPresent              bool
	Scope2DigestValue              []byte
	Scope2DigestPresent            bool
	Scope2AllocationOrdinalValue   int64
	Scope2AllocationOrdinalPresent bool
}

func (q *Queries) RuntimeReleaseClaim(ctx context.Context, arg RuntimeReleaseClaimParams) (RuntimeReleaseClaimRow, error) {
	row := q.db.QueryRow(ctx, runtimeReleaseClaim,
		arg.ClaimID,
		arg.ExpectedReplicaID,
		arg.RequestDigest,
		arg.Reason,
	)
	var i RuntimeReleaseClaimRow
	err := row.Scan(
		&i.Outcome,
		&i.ClaimID,
		&i.PolicyIDValue,
		&i.PolicyIDPresent,
		&i.ReplicaIDValue,
		&i.ReplicaIDPresent,
		&i.WorkIDValue,
		&i.WorkIDPresent,
		&i.StateValue,
		&i.StatePresent,
		&i.AdmittedAtValue,
		&i.AdmittedAtPresent,
		&i.DeadlineAtValue,
		&i.DeadlineAtPresent,
		&i.ReleasedAtValue,
		&i.ReleasedAtPresent,
		&i.ReleaseReasonValue,
		&i.ReleaseReasonPresent,
		&i.RequestDigestValue,
		&i.RequestDigestPresent,
		&i.ScopeCountValue,
		&i.ScopeCountPresent,
		&i.Scope1KindValue,
		&i.Scope1KindPresent,
		&i.Scope1DigestValue,
		&i.Scope1DigestPresent,
		&i.Scope1AllocationOrdinalValue,
		&i.Scope1AllocationOrdinalPresent,
		&i.Scope2KindValue,
		&i.Scope2KindPresent,
		&i.Scope2DigestValue,
		&i.Scope2DigestPresent,
		&i.Scope2AllocationOrdinalValue,
		&i.Scope2AllocationOrdinalPresent,
	)
	return i, err
}

const runtimeResolveClaim = `-- name: RuntimeResolveClaim :one
WITH result AS MATERIALIZED (SELECT public.runtime_resolve_claim($1::uuid,$2::uuid,$3::bytea) AS r)
SELECT
  (result.r).outcome::text AS outcome,
  (result.r).claim_id::uuid AS claim_id,
  COALESCE((result.r).policy_id,''::text)::text AS policy_id_value, ((result.r).policy_id IS NOT NULL)::boolean AS policy_id_present,
  COALESCE((result.r).replica_id,'00000000-0000-0000-0000-000000000000'::uuid)::uuid AS replica_id_value, ((result.r).replica_id IS NOT NULL)::boolean AS replica_id_present,
  COALESCE((result.r).work_id,'00000000-0000-0000-0000-000000000000'::uuid)::uuid AS work_id_value, ((result.r).work_id IS NOT NULL)::boolean AS work_id_present,
  COALESCE((result.r).state,''::text)::text AS state_value, ((result.r).state IS NOT NULL)::boolean AS state_present,
  COALESCE((result.r).admitted_at,'1970-01-01 UTC'::timestamptz)::timestamptz AS admitted_at_value, ((result.r).admitted_at IS NOT NULL)::boolean AS admitted_at_present,
  COALESCE((result.r).deadline_at,'1970-01-01 UTC'::timestamptz)::timestamptz AS deadline_at_value, ((result.r).deadline_at IS NOT NULL)::boolean AS deadline_at_present,
  COALESCE((result.r).released_at,'1970-01-01 UTC'::timestamptz)::timestamptz AS released_at_value, ((result.r).released_at IS NOT NULL)::boolean AS released_at_present,
  COALESCE((result.r).release_reason,''::text)::text AS release_reason_value, ((result.r).release_reason IS NOT NULL)::boolean AS release_reason_present,
  COALESCE((result.r).request_digest,''::bytea)::bytea AS request_digest_value, ((result.r).request_digest IS NOT NULL)::boolean AS request_digest_present,
  COALESCE((result.r).scope_count,0::smallint)::smallint AS scope_count_value, ((result.r).scope_count IS NOT NULL)::boolean AS scope_count_present,
  COALESCE((result.r).scope_1_kind,''::text)::text AS scope_1_kind_value, ((result.r).scope_1_kind IS NOT NULL)::boolean AS scope_1_kind_present,
  COALESCE((result.r).scope_1_digest,''::bytea)::bytea AS scope_1_digest_value, ((result.r).scope_1_digest IS NOT NULL)::boolean AS scope_1_digest_present,
  COALESCE((result.r).scope_1_allocation_ordinal,0::bigint)::bigint AS scope_1_allocation_ordinal_value, ((result.r).scope_1_allocation_ordinal IS NOT NULL)::boolean AS scope_1_allocation_ordinal_present,
  COALESCE((result.r).scope_2_kind,''::text)::text AS scope_2_kind_value, ((result.r).scope_2_kind IS NOT NULL)::boolean AS scope_2_kind_present,
  COALESCE((result.r).scope_2_digest,''::bytea)::bytea AS scope_2_digest_value, ((result.r).scope_2_digest IS NOT NULL)::boolean AS scope_2_digest_present,
  COALESCE((result.r).scope_2_allocation_ordinal,0::bigint)::bigint AS scope_2_allocation_ordinal_value, ((result.r).scope_2_allocation_ordinal IS NOT NULL)::boolean AS scope_2_allocation_ordinal_present
FROM result
`

type RuntimeResolveClaimParams struct {
	ClaimID           uuid.UUID
	ExpectedReplicaID uuid.UUID
	RequestDigest     []byte
}

type RuntimeResolveClaimRow struct {
	Outcome                        string
	ClaimID                        uuid.UUID
	PolicyIDValue                  string
	PolicyIDPresent                bool
	ReplicaIDValue                 uuid.UUID
	ReplicaIDPresent               bool
	WorkIDValue                    uuid.UUID
	WorkIDPresent                  bool
	StateValue                     string
	StatePresent                   bool
	AdmittedAtValue                time.Time
	AdmittedAtPresent              bool
	DeadlineAtValue                time.Time
	DeadlineAtPresent              bool
	ReleasedAtValue                time.Time
	ReleasedAtPresent              bool
	ReleaseReasonValue             string
	ReleaseReasonPresent           bool
	RequestDigestValue             []byte
	RequestDigestPresent           bool
	ScopeCountValue                int16
	ScopeCountPresent              bool
	Scope1KindValue                string
	Scope1KindPresent              bool
	Scope1DigestValue              []byte
	Scope1DigestPresent            bool
	Scope1AllocationOrdinalValue   int64
	Scope1AllocationOrdinalPresent bool
	Scope2KindValue                string
	Scope2KindPresent              bool
	Scope2DigestValue              []byte
	Scope2DigestPresent            bool
	Scope2AllocationOrdinalValue   int64
	Scope2AllocationOrdinalPresent bool
}

func (q *Queries) RuntimeResolveClaim(ctx context.Context, arg RuntimeResolveClaimParams) (RuntimeResolveClaimRow, error) {
	row := q.db.QueryRow(ctx, runtimeResolveClaim, arg.ClaimID, arg.ExpectedReplicaID, arg.RequestDigest)
	var i RuntimeResolveClaimRow
	err := row.Scan(
		&i.Outcome,
		&i.ClaimID,
		&i.PolicyIDValue,
		&i.PolicyIDPresent,
		&i.ReplicaIDValue,
		&i.ReplicaIDPresent,
		&i.WorkIDValue,
		&i.WorkIDPresent,
		&i.StateValue,
		&i.StatePresent,
		&i.AdmittedAtValue,
		&i.AdmittedAtPresent,
		&i.DeadlineAtValue,
		&i.DeadlineAtPresent,
		&i.ReleasedAtValue,
		&i.ReleasedAtPresent,
		&i.ReleaseReasonValue,
		&i.ReleaseReasonPresent,
		&i.RequestDigestValue,
		&i.RequestDigestPresent,
		&i.ScopeCountValue,
		&i.ScopeCountPresent,
		&i.Scope1KindValue,
		&i.Scope1KindPresent,
		&i.Scope1DigestValue,
		&i.Scope1DigestPresent,
		&i.Scope1AllocationOrdinalValue,
		&i.Scope1AllocationOrdinalPresent,
		&i.Scope2KindValue,
		&i.Scope2KindPresent,
		&i.Scope2DigestValue,
		&i.Scope2DigestPresent,
		&i.Scope2AllocationOrdinalValue,
		&i.Scope2AllocationOrdinalPresent,
	)
	return i, err
}
