// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_membership_evidence.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const runtimeFinishMaintenanceGracefulLeave = `-- name: RuntimeFinishMaintenanceGracefulLeave :one
WITH result AS MATERIALIZED (
 SELECT public.runtime_finish_maintenance_graceful_leave($1::uuid,$2::text,$3::text,$4::bigint,$5::text) AS r
)
SELECT (r).replica_id::uuid AS replica_id,(r).state::text AS state,
 (r).receipt_operation_id::text AS receipt_operation_id,
 (r).controller_generation::bigint AS controller_generation,
 (r).joined_transition_count::integer AS joined_transition_count,
 (r).joined_claim_count::integer AS joined_claim_count,
 (r).recorded_at::timestamptz AS recorded_at,(r).replayed::boolean AS replayed FROM result
`

type RuntimeFinishMaintenanceGracefulLeaveParams struct {
	ReplicaID                    uuid.UUID
	InstanceID                   string
	ReleaseDigest                string
	ExpectedControllerGeneration int64
	OperationID                  string
}

type RuntimeFinishMaintenanceGracefulLeaveRow struct {
	ReplicaID             uuid.UUID
	State                 string
	ReceiptOperationID    string
	ControllerGeneration  int64
	JoinedTransitionCount int32
	JoinedClaimCount      int32
	RecordedAt            time.Time
	Replayed              bool
}

func (q *Queries) RuntimeFinishMaintenanceGracefulLeave(ctx context.Context, arg RuntimeFinishMaintenanceGracefulLeaveParams) (RuntimeFinishMaintenanceGracefulLeaveRow, error) {
	row := q.db.QueryRow(ctx, runtimeFinishMaintenanceGracefulLeave,
		arg.ReplicaID,
		arg.InstanceID,
		arg.ReleaseDigest,
		arg.ExpectedControllerGeneration,
		arg.OperationID,
	)
	var i RuntimeFinishMaintenanceGracefulLeaveRow
	err := row.Scan(
		&i.ReplicaID,
		&i.State,
		&i.ReceiptOperationID,
		&i.ControllerGeneration,
		&i.JoinedTransitionCount,
		&i.JoinedClaimCount,
		&i.RecordedAt,
		&i.Replayed,
	)
	return i, err
}

const runtimeFinishServingGracefulLeave = `-- name: RuntimeFinishServingGracefulLeave :one
WITH result AS MATERIALIZED (
 SELECT public.runtime_finish_serving_graceful_leave($1::uuid,$2::text,$3::text,$4::bigint,$5::text) AS r
)
SELECT (r).replica_id::uuid AS replica_id,(r).state::text AS state,
 (r).receipt_operation_id::text AS receipt_operation_id,
 (r).controller_generation::bigint AS controller_generation,
 (r).joined_transition_count::integer AS joined_transition_count,
 (r).joined_claim_count::integer AS joined_claim_count,
 (r).recorded_at::timestamptz AS recorded_at,(r).replayed::boolean AS replayed FROM result
`

type RuntimeFinishServingGracefulLeaveParams struct {
	ReplicaID                    uuid.UUID
	InstanceID                   string
	ReleaseDigest                string
	ExpectedControllerGeneration int64
	OperationID                  string
}

type RuntimeFinishServingGracefulLeaveRow struct {
	ReplicaID             uuid.UUID
	State                 string
	ReceiptOperationID    string
	ControllerGeneration  int64
	JoinedTransitionCount int32
	JoinedClaimCount      int32
	RecordedAt            time.Time
	Replayed              bool
}

func (q *Queries) RuntimeFinishServingGracefulLeave(ctx context.Context, arg RuntimeFinishServingGracefulLeaveParams) (RuntimeFinishServingGracefulLeaveRow, error) {
	row := q.db.QueryRow(ctx, runtimeFinishServingGracefulLeave,
		arg.ReplicaID,
		arg.InstanceID,
		arg.ReleaseDigest,
		arg.ExpectedControllerGeneration,
		arg.OperationID,
	)
	var i RuntimeFinishServingGracefulLeaveRow
	err := row.Scan(
		&i.ReplicaID,
		&i.State,
		&i.ReceiptOperationID,
		&i.ControllerGeneration,
		&i.JoinedTransitionCount,
		&i.JoinedClaimCount,
		&i.RecordedAt,
		&i.Replayed,
	)
	return i, err
}

const runtimeRecordEC2Termination = `-- name: RuntimeRecordEC2Termination :one
WITH result AS MATERIALIZED (
 SELECT public.runtime_record_ec2_termination($1::uuid,$2::text,$3::text,$4::text,$5::text,$6::timestamptz,$7::timestamptz,$8::text) AS r
)
SELECT (r).replica_id::uuid AS replica_id,(r).state::text AS state,
 (r).evidence_id::text AS evidence_id,
 (r).reclaimed_claim_count::integer AS reclaimed_claim_count,
 (r).recorded_at::timestamptz AS recorded_at,(r).replayed::boolean AS replayed FROM result
`

type RuntimeRecordEC2TerminationParams struct {
	ReplicaID            uuid.UUID
	InstanceID           string
	ReleaseDigest        string
	RequestID            string
	EvidenceID           string
	RequestedAt          time.Time
	ObservedTerminatedAt time.Time
	ObservedState        string
}

type RuntimeRecordEC2TerminationRow struct {
	ReplicaID           uuid.UUID
	State               string
	EvidenceID          string
	ReclaimedClaimCount int32
	RecordedAt          time.Time
	Replayed            bool
}

func (q *Queries) RuntimeRecordEC2Termination(ctx context.Context, arg RuntimeRecordEC2TerminationParams) (RuntimeRecordEC2TerminationRow, error) {
	row := q.db.QueryRow(ctx, runtimeRecordEC2Termination,
		arg.ReplicaID,
		arg.InstanceID,
		arg.ReleaseDigest,
		arg.RequestID,
		arg.EvidenceID,
		arg.RequestedAt,
		arg.ObservedTerminatedAt,
		arg.ObservedState,
	)
	var i RuntimeRecordEC2TerminationRow
	err := row.Scan(
		&i.ReplicaID,
		&i.State,
		&i.EvidenceID,
		&i.ReclaimedClaimCount,
		&i.RecordedAt,
		&i.Replayed,
	)
	return i, err
}
