// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_rates.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const runtimeAdmitSlugChange = `-- name: RuntimeAdmitSlugChange :one
WITH result AS MATERIALIZED (SELECT public.runtime_admit_slug_change($1::bytea) AS r)
SELECT
  (result.r).allowed::boolean AS allowed,
  (result.r).retry_after_seconds::integer AS retry_after_seconds,
  (result.r).bucket_kind::text AS bucket_kind,
  COALESCE((result.r).partition,0::smallint)::smallint AS partition_value, ((result.r).partition IS NOT NULL)::boolean AS partition_present,
  (result.r).effective_at::timestamptz AS effective_at
FROM result
`

type RuntimeAdmitSlugChangeRow struct {
	Allowed           bool
	RetryAfterSeconds int32
	BucketKind        string
	PartitionValue    int16
	PartitionPresent  bool
	EffectiveAt       time.Time
}

func (q *Queries) RuntimeAdmitSlugChange(ctx context.Context, keyDigest []byte) (RuntimeAdmitSlugChangeRow, error) {
	row := q.db.QueryRow(ctx, runtimeAdmitSlugChange, keyDigest)
	var i RuntimeAdmitSlugChangeRow
	err := row.Scan(
		&i.Allowed,
		&i.RetryAfterSeconds,
		&i.BucketKind,
		&i.PartitionValue,
		&i.PartitionPresent,
		&i.EffectiveAt,
	)
	return i, err
}

const runtimeAdmitTokenRate = `-- name: RuntimeAdmitTokenRate :one
WITH result AS MATERIALIZED (SELECT public.runtime_admit_token_rate($1::text,$2::bytea) AS r)
SELECT
  (result.r).allowed::boolean AS allowed,
  (result.r).retry_after_seconds::integer AS retry_after_seconds,
  (result.r).bucket_kind::text AS bucket_kind,
  COALESCE((result.r).partition,0::smallint)::smallint AS partition_value, ((result.r).partition IS NOT NULL)::boolean AS partition_present,
  (result.r).effective_at::timestamptz AS effective_at
FROM result
`

type RuntimeAdmitTokenRateParams struct {
	PolicyID  string
	KeyDigest []byte
}

type RuntimeAdmitTokenRateRow struct {
	Allowed           bool
	RetryAfterSeconds int32
	BucketKind        string
	PartitionValue    int16
	PartitionPresent  bool
	EffectiveAt       time.Time
}

func (q *Queries) RuntimeAdmitTokenRate(ctx context.Context, arg RuntimeAdmitTokenRateParams) (RuntimeAdmitTokenRateRow, error) {
	row := q.db.QueryRow(ctx, runtimeAdmitTokenRate, arg.PolicyID, arg.KeyDigest)
	var i RuntimeAdmitTokenRateRow
	err := row.Scan(
		&i.Allowed,
		&i.RetryAfterSeconds,
		&i.BucketKind,
		&i.PartitionValue,
		&i.PartitionPresent,
		&i.EffectiveAt,
	)
	return i, err
}

const runtimeCleanupAdmissionAttemptReceipts = `-- name: RuntimeCleanupAdmissionAttemptReceipts :one
WITH result AS MATERIALIZED (SELECT public.runtime_cleanup_admission_attempt_receipts($1::integer) AS r)
SELECT (result.r).deleted_count::integer AS deleted_count
FROM result
`

func (q *Queries) RuntimeCleanupAdmissionAttemptReceipts(ctx context.Context, pageSize int32) (int32, error) {
	row := q.db.QueryRow(ctx, runtimeCleanupAdmissionAttemptReceipts, pageSize)
	var deleted_count int32
	err := row.Scan(&deleted_count)
	return deleted_count, err
}

const runtimeCleanupRateBuckets = `-- name: RuntimeCleanupRateBuckets :one
WITH result AS MATERIALIZED (SELECT public.runtime_cleanup_rate_buckets($1::text,$2::integer) AS r)
SELECT
  (result.r).deleted_count::integer AS deleted_count,
  (result.r).effective_at::timestamptz AS effective_at,
  (result.r).policy_idle::boolean AS policy_idle
FROM result
`

type RuntimeCleanupRateBucketsParams struct {
	PolicyID string
	PageSize int32
}

type RuntimeCleanupRateBucketsRow struct {
	DeletedCount int32
	EffectiveAt  time.Time
	PolicyIdle   bool
}

func (q *Queries) RuntimeCleanupRateBuckets(ctx context.Context, arg RuntimeCleanupRateBucketsParams) (RuntimeCleanupRateBucketsRow, error) {
	row := q.db.QueryRow(ctx, runtimeCleanupRateBuckets, arg.PolicyID, arg.PageSize)
	var i RuntimeCleanupRateBucketsRow
	err := row.Scan(&i.DeletedCount, &i.EffectiveAt, &i.PolicyIdle)
	return i, err
}

const runtimeClearPasswordFailure = `-- name: RuntimeClearPasswordFailure :one
WITH result AS MATERIALIZED (SELECT public.runtime_clear_password_failure($1::bytea) AS r)
SELECT
  (result.r).cleared::boolean AS cleared,
  (result.r).bucket_kind::text AS bucket_kind,
  COALESCE((result.r).partition,0::smallint)::smallint AS partition_value, ((result.r).partition IS NOT NULL)::boolean AS partition_present
FROM result
`

type RuntimeClearPasswordFailureRow struct {
	Cleared          bool
	BucketKind       string
	PartitionValue   int16
	PartitionPresent bool
}

func (q *Queries) RuntimeClearPasswordFailure(ctx context.Context, keyDigest []byte) (RuntimeClearPasswordFailureRow, error) {
	row := q.db.QueryRow(ctx, runtimeClearPasswordFailure, keyDigest)
	var i RuntimeClearPasswordFailureRow
	err := row.Scan(
		&i.Cleared,
		&i.BucketKind,
		&i.PartitionValue,
		&i.PartitionPresent,
	)
	return i, err
}

const runtimeFinishAdmissionAttempt = `-- name: RuntimeFinishAdmissionAttempt :one
WITH result AS MATERIALIZED (SELECT public.runtime_finish_admission_attempt($1::uuid,$2::text) AS r)
SELECT
  (result.r).resolution::text AS resolution,
  COALESCE((result.r).stored_outcome,''::text)::text AS stored_outcome_value, ((result.r).stored_outcome IS NOT NULL)::boolean AS stored_outcome_present
FROM result
`

type RuntimeFinishAdmissionAttemptParams struct {
	AttemptID uuid.UUID
	Outcome   string
}

type RuntimeFinishAdmissionAttemptRow struct {
	Resolution           string
	StoredOutcomeValue   string
	StoredOutcomePresent bool
}

func (q *Queries) RuntimeFinishAdmissionAttempt(ctx context.Context, arg RuntimeFinishAdmissionAttemptParams) (RuntimeFinishAdmissionAttemptRow, error) {
	row := q.db.QueryRow(ctx, runtimeFinishAdmissionAttempt, arg.AttemptID, arg.Outcome)
	var i RuntimeFinishAdmissionAttemptRow
	err := row.Scan(&i.Resolution, &i.StoredOutcomeValue, &i.StoredOutcomePresent)
	return i, err
}

const runtimePasswordFailureState = `-- name: RuntimePasswordFailureState :one
WITH result AS MATERIALIZED (SELECT public.runtime_password_failure_state($1::bytea) AS r)
SELECT
  (result.r).exhausted::boolean AS exhausted,
  (result.r).retry_after_seconds::integer AS retry_after_seconds,
  (result.r).bucket_kind::text AS bucket_kind,
  COALESCE((result.r).partition,0::smallint)::smallint AS partition_value, ((result.r).partition IS NOT NULL)::boolean AS partition_present,
  (result.r).effective_at::timestamptz AS effective_at,
  (result.r).allocated::boolean AS allocated,
  (result.r).activity_refreshed::boolean AS activity_refreshed
FROM result
`

type RuntimePasswordFailureStateRow struct {
	Exhausted         bool
	RetryAfterSeconds int32
	BucketKind        string
	PartitionValue    int16
	PartitionPresent  bool
	EffectiveAt       time.Time
	Allocated         bool
	ActivityRefreshed bool
}

func (q *Queries) RuntimePasswordFailureState(ctx context.Context, keyDigest []byte) (RuntimePasswordFailureStateRow, error) {
	row := q.db.QueryRow(ctx, runtimePasswordFailureState, keyDigest)
	var i RuntimePasswordFailureStateRow
	err := row.Scan(
		&i.Exhausted,
		&i.RetryAfterSeconds,
		&i.BucketKind,
		&i.PartitionValue,
		&i.PartitionPresent,
		&i.EffectiveAt,
		&i.Allocated,
		&i.ActivityRefreshed,
	)
	return i, err
}

const runtimeRecordPasswordFailure = `-- name: RuntimeRecordPasswordFailure :one
WITH result AS MATERIALIZED (SELECT public.runtime_record_password_failure($1::bytea) AS r)
SELECT
  (result.r).exhausted::boolean AS exhausted,
  (result.r).retry_after_seconds::integer AS retry_after_seconds,
  (result.r).bucket_kind::text AS bucket_kind,
  COALESCE((result.r).partition,0::smallint)::smallint AS partition_value, ((result.r).partition IS NOT NULL)::boolean AS partition_present,
  (result.r).effective_at::timestamptz AS effective_at,
  (result.r).allocated::boolean AS allocated,
  (result.r).activity_refreshed::boolean AS activity_refreshed
FROM result
`

type RuntimeRecordPasswordFailureRow struct {
	Exhausted         bool
	RetryAfterSeconds int32
	BucketKind        string
	PartitionValue    int16
	PartitionPresent  bool
	EffectiveAt       time.Time
	Allocated         bool
	ActivityRefreshed bool
}

func (q *Queries) RuntimeRecordPasswordFailure(ctx context.Context, keyDigest []byte) (RuntimeRecordPasswordFailureRow, error) {
	row := q.db.QueryRow(ctx, runtimeRecordPasswordFailure, keyDigest)
	var i RuntimeRecordPasswordFailureRow
	err := row.Scan(
		&i.Exhausted,
		&i.RetryAfterSeconds,
		&i.BucketKind,
		&i.PartitionValue,
		&i.PartitionPresent,
		&i.EffectiveAt,
		&i.Allocated,
		&i.ActivityRefreshed,
	)
	return i, err
}

const runtimeReserveOAuthFailedGrant = `-- name: RuntimeReserveOAuthFailedGrant :one
WITH result AS MATERIALIZED (SELECT public.runtime_reserve_oauth_failed_grant($1::uuid,$2::uuid) AS r)
SELECT
  (result.r).allowed::boolean AS allowed,
  (result.r).retry_after_seconds::integer AS retry_after_seconds,
  COALESCE((result.r).bucket_kind,''::text)::text AS bucket_kind_value, ((result.r).bucket_kind IS NOT NULL)::boolean AS bucket_kind_present,
  COALESCE((result.r).partition,0::smallint)::smallint AS partition_value, ((result.r).partition IS NOT NULL)::boolean AS partition_present,
  (result.r).replayed::boolean AS replayed
FROM result
`

type RuntimeReserveOAuthFailedGrantParams struct {
	AttemptID uuid.UUID
	ClientID  uuid.UUID
}

type RuntimeReserveOAuthFailedGrantRow struct {
	Allowed           bool
	RetryAfterSeconds int32
	BucketKindValue   string
	BucketKindPresent bool
	PartitionValue    int16
	PartitionPresent  bool
	Replayed          bool
}

func (q *Queries) RuntimeReserveOAuthFailedGrant(ctx context.Context, arg RuntimeReserveOAuthFailedGrantParams) (RuntimeReserveOAuthFailedGrantRow, error) {
	row := q.db.QueryRow(ctx, runtimeReserveOAuthFailedGrant, arg.AttemptID, arg.ClientID)
	var i RuntimeReserveOAuthFailedGrantRow
	err := row.Scan(
		&i.Allowed,
		&i.RetryAfterSeconds,
		&i.BucketKindValue,
		&i.BucketKindPresent,
		&i.PartitionValue,
		&i.PartitionPresent,
		&i.Replayed,
	)
	return i, err
}
