// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: showcase.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const approveResumeShowcase = `-- name: ApproveResumeShowcase :one
UPDATE resume_showcase AS s
SET reviewed_key = s.review_key,
    review_outcome = 'approved',
    reviewed_at = $1::timestamptz,
    first_listed_at = COALESCE(s.first_listed_at, $1::timestamptz)
FROM resumes AS r
WHERE r.id = s.resume_id
  AND r.slug = $2::text
  AND s.review_key = $3::text
RETURNING s.resume_id
`

type ApproveResumeShowcaseParams struct {
	ReviewedAt time.Time
	Slug       string
	ReviewKey  string
}

// Approves only while the named key is still the current review key. The
// first approval of an opt-in sets first_listed_at; later approvals keep it.
func (q *Queries) ApproveResumeShowcase(ctx context.Context, arg ApproveResumeShowcaseParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, approveResumeShowcase, arg.ReviewedAt, arg.Slug, arg.ReviewKey)
	var resume_id uuid.UUID
	err := row.Scan(&resume_id)
	return resume_id, err
}

const countShowcase = `-- name: CountShowcase :one
SELECT count(*)::bigint
FROM resume_showcase s
JOIN resumes r ON r.id = s.resume_id
CROSS JOIN LATERAL (
    SELECT (CASE lower(split_part(coalesce(r.lng, ''), '-', 1))
        WHEN 'vi' THEN 'vi' WHEN 'en' THEN 'en' ELSE 'other' END)::text AS language
) AS l
WHERE s.review_outcome = 'approved'
  AND s.reviewed_key = s.review_key
  AND r.live = true
  AND r.sign_in_to_view = false
  AND ($1::text IS NULL OR s.role = $1::text)
  AND ($2::text IS NULL OR l.language = $2::text)
  AND (
      $3::text IS NULL
      OR ($3::text = 'custom' AND s.template_id IS NULL)
      OR s.template_id = $3::text
  )
`

type CountShowcaseParams struct {
	Role     *string
	Lang     *string
	Template *string
}

func (q *Queries) CountShowcase(ctx context.Context, arg CountShowcaseParams) (int64, error) {
	row := q.db.QueryRow(ctx, countShowcase, arg.Role, arg.Lang, arg.Template)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const declineResumeShowcase = `-- name: DeclineResumeShowcase :one
UPDATE resume_showcase AS s
SET reviewed_key = s.review_key,
    review_outcome = 'declined',
    reviewed_at = $1::timestamptz
FROM resumes AS r
WHERE r.id = s.resume_id
  AND r.slug = $2::text
  AND s.review_key = $3::text
RETURNING s.resume_id
`

type DeclineResumeShowcaseParams struct {
	ReviewedAt time.Time
	Slug       string
	ReviewKey  string
}

// Declines only while the named key is still the current review key. It keeps
// first_listed_at: a later approval of a changed key does not move the resume up.
func (q *Queries) DeclineResumeShowcase(ctx context.Context, arg DeclineResumeShowcaseParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, declineResumeShowcase, arg.ReviewedAt, arg.Slug, arg.ReviewKey)
	var resume_id uuid.UUID
	err := row.Scan(&resume_id)
	return resume_id, err
}

const deleteResumeShowcase = `-- name: DeleteResumeShowcase :execrows
DELETE FROM resume_showcase
WHERE resume_id = $1
`

func (q *Queries) DeleteResumeShowcase(ctx context.Context, resumeID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteResumeShowcase, resumeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getResumeShowcase = `-- name: GetResumeShowcase :one

SELECT resume_id, requested_at, role, review_key, card_version, template_id, reviewed_key, review_outcome, reviewed_at, first_listed_at FROM resume_showcase
WHERE resume_id = $1
`

// Community showcase queries (docs/design/showcase.md, ADR 0029). The
// resume_showcase row exists only while the opt-in does.
func (q *Queries) GetResumeShowcase(ctx context.Context, resumeID uuid.UUID) (ResumeShowcase, error) {
	row := q.db.QueryRow(ctx, getResumeShowcase, resumeID)
	var i ResumeShowcase
	err := row.Scan(
		&i.ResumeID,
		&i.RequestedAt,
		&i.Role,
		&i.ReviewKey,
		&i.CardVersion,
		&i.TemplateID,
		&i.ReviewedKey,
		&i.ReviewOutcome,
		&i.ReviewedAt,
		&i.FirstListedAt,
	)
	return i, err
}

const getResumeShowcaseBySlug = `-- name: GetResumeShowcaseBySlug :one
SELECT r.slug, s.role, s.review_key, s.card_version, s.template_id, s.reviewed_key,
       s.review_outcome, s.requested_at, s.reviewed_at, s.first_listed_at
FROM resume_showcase s
JOIN resumes r ON r.id = s.resume_id
WHERE r.slug = $1::text
`

type GetResumeShowcaseBySlugRow struct {
	Slug          *string
	Role          *string
	ReviewKey     string
	CardVersion   string
	TemplateID    *string
	ReviewedKey   *string
	ReviewOutcome *string
	RequestedAt   time.Time
	ReviewedAt    *time.Time
	FirstListedAt *time.Time
}

func (q *Queries) GetResumeShowcaseBySlug(ctx context.Context, slug string) (GetResumeShowcaseBySlugRow, error) {
	row := q.db.QueryRow(ctx, getResumeShowcaseBySlug, slug)
	var i GetResumeShowcaseBySlugRow
	err := row.Scan(
		&i.Slug,
		&i.Role,
		&i.ReviewKey,
		&i.CardVersion,
		&i.TemplateID,
		&i.ReviewedKey,
		&i.ReviewOutcome,
		&i.RequestedAt,
		&i.ReviewedAt,
		&i.FirstListedAt,
	)
	return i, err
}

const getResumeShowcaseForUpdate = `-- name: GetResumeShowcaseForUpdate :one
SELECT resume_id, requested_at, role, review_key, card_version, template_id, reviewed_key, review_outcome, reviewed_at, first_listed_at FROM resume_showcase
WHERE resume_id = $1
FOR UPDATE
`

// Locks the opt-in row so a derived-value write and an operator review
// serialize: a review that names a key the write just replaced matches no row.
func (q *Queries) GetResumeShowcaseForUpdate(ctx context.Context, resumeID uuid.UUID) (ResumeShowcase, error) {
	row := q.db.QueryRow(ctx, getResumeShowcaseForUpdate, resumeID)
	var i ResumeShowcase
	err := row.Scan(
		&i.ResumeID,
		&i.RequestedAt,
		&i.Role,
		&i.ReviewKey,
		&i.CardVersion,
		&i.TemplateID,
		&i.ReviewedKey,
		&i.ReviewOutcome,
		&i.ReviewedAt,
		&i.FirstListedAt,
	)
	return i, err
}

const insertResumeShowcase = `-- name: InsertResumeShowcase :exec
INSERT INTO resume_showcase (resume_id, requested_at, role, review_key, card_version, template_id)
VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type InsertResumeShowcaseParams struct {
	ResumeID    uuid.UUID
	RequestedAt time.Time
	Role        *string
	ReviewKey   string
	CardVersion string
	TemplateID  *string
}

// A new opt-in starts with no review result and no first-listed time.
func (q *Queries) InsertResumeShowcase(ctx context.Context, arg InsertResumeShowcaseParams) error {
	_, err := q.db.Exec(ctx, insertResumeShowcase,
		arg.ResumeID,
		arg.RequestedAt,
		arg.Role,
		arg.ReviewKey,
		arg.CardVersion,
		arg.TemplateID,
	)
	return err
}

const listPendingResumeShowcases = `-- name: ListPendingResumeShowcases :many
SELECT r.slug, s.review_key, s.card_version, s.requested_at
FROM resume_showcase s
JOIN resumes r ON r.id = s.resume_id
WHERE s.review_outcome IS NULL OR s.reviewed_key IS DISTINCT FROM s.review_key
ORDER BY s.requested_at, s.resume_id
`

type ListPendingResumeShowcasesRow struct {
	Slug        *string
	ReviewKey   string
	CardVersion string
	RequestedAt time.Time
}

// Opted in with no review result for the current key.
func (q *Queries) ListPendingResumeShowcases(ctx context.Context) ([]ListPendingResumeShowcasesRow, error) {
	rows, err := q.db.Query(ctx, listPendingResumeShowcases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingResumeShowcasesRow
	for rows.Next() {
		var i ListPendingResumeShowcasesRow
		if err := rows.Scan(
			&i.Slug,
			&i.ReviewKey,
			&i.CardVersion,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResumeShowcaseIDs = `-- name: ListResumeShowcaseIDs :many
SELECT resume_id FROM resume_showcase
ORDER BY resume_id
`

func (q *Queries) ListResumeShowcaseIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listResumeShowcaseIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var resume_id uuid.UUID
		if err := rows.Scan(&resume_id); err != nil {
			return nil, err
		}
		items = append(items, resume_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResumeShowcasesForUser = `-- name: ListResumeShowcasesForUser :many
SELECT s.resume_id, s.requested_at, s.role, s.review_key, s.card_version, s.template_id, s.reviewed_key, s.review_outcome, s.reviewed_at, s.first_listed_at
FROM resume_showcase s
JOIN resumes r ON r.id = s.resume_id
WHERE r.user_id = $1
`

func (q *Queries) ListResumeShowcasesForUser(ctx context.Context, userID uuid.UUID) ([]ResumeShowcase, error) {
	rows, err := q.db.Query(ctx, listResumeShowcasesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResumeShowcase
	for rows.Next() {
		var i ResumeShowcase
		if err := rows.Scan(
			&i.ResumeID,
			&i.RequestedAt,
			&i.Role,
			&i.ReviewKey,
			&i.CardVersion,
			&i.TemplateID,
			&i.ReviewedKey,
			&i.ReviewOutcome,
			&i.ReviewedAt,
			&i.FirstListedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShowcase = `-- name: ListShowcase :many
SELECT r.id, r.slug, r.schema_version, r.personal_details,
       s.card_version, s.template_id, s.role, l.language
FROM resume_showcase s
JOIN resumes r ON r.id = s.resume_id
CROSS JOIN LATERAL (
    SELECT (CASE lower(split_part(coalesce(r.lng, ''), '-', 1))
        WHEN 'vi' THEN 'vi' WHEN 'en' THEN 'en' ELSE 'other' END)::text AS language
) AS l
WHERE s.review_outcome = 'approved'
  AND s.reviewed_key = s.review_key
  AND r.live = true
  AND r.sign_in_to_view = false
  AND ($1::text IS NULL OR s.role = $1::text)
  AND ($2::text IS NULL OR l.language = $2::text)
  AND (
      $3::text IS NULL
      OR ($3::text = 'custom' AND s.template_id IS NULL)
      OR s.template_id = $3::text
  )
ORDER BY s.first_listed_at DESC, s.resume_id DESC
LIMIT $5::int OFFSET $4::int
`

type ListShowcaseParams struct {
	Role       *string
	Lang       *string
	Template   *string
	PageOffset int32
	PageSize   int32
}

type ListShowcaseRow struct {
	ID              uuid.UUID
	Slug            *string
	SchemaVersion   int32
	PersonalDetails json.RawMessage
	CardVersion     string
	TemplateID      *string
	Role            *string
	Language        string
}

// The public listing. One statement checks all five listing conditions: the
// opt-in row exists, the review result is approved, the approved key equals
// the current key, the resume is live, and sign in to view is off. It reads
// committed state on every call; nothing caches it. The page needs only the
// personal details (for the card's image text), so it reads no other document
// part; schema_version tells the caller whether those details are current.
func (q *Queries) ListShowcase(ctx context.Context, arg ListShowcaseParams) ([]ListShowcaseRow, error) {
	rows, err := q.db.Query(ctx, listShowcase,
		arg.Role,
		arg.Lang,
		arg.Template,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShowcaseRow
	for rows.Next() {
		var i ListShowcaseRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.SchemaVersion,
			&i.PersonalDetails,
			&i.CardVersion,
			&i.TemplateID,
			&i.Role,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResumeShowcaseDerived = `-- name: UpdateResumeShowcaseDerived :exec
UPDATE resume_showcase
SET review_key = $1,
    card_version = $2,
    template_id = $3
WHERE resume_id = $4
`

type UpdateResumeShowcaseDerivedParams struct {
	ReviewKey   string
	CardVersion string
	TemplateID  *string
	ResumeID    uuid.UUID
}

func (q *Queries) UpdateResumeShowcaseDerived(ctx context.Context, arg UpdateResumeShowcaseDerivedParams) error {
	_, err := q.db.Exec(ctx, updateResumeShowcaseDerived,
		arg.ReviewKey,
		arg.CardVersion,
		arg.TemplateID,
		arg.ResumeID,
	)
	return err
}

const updateResumeShowcaseRole = `-- name: UpdateResumeShowcaseRole :exec
UPDATE resume_showcase
SET role = $1
WHERE resume_id = $2
`

type UpdateResumeShowcaseRoleParams struct {
	Role     *string
	ResumeID uuid.UUID
}

func (q *Queries) UpdateResumeShowcaseRole(ctx context.Context, arg UpdateResumeShowcaseRoleParams) error {
	_, err := q.db.Exec(ctx, updateResumeShowcaseRole, arg.Role, arg.ResumeID)
	return err
}
