// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: showcase.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countShowcase = `-- name: CountShowcase :one
SELECT count(*)::bigint
FROM resume_showcase s
JOIN resumes r ON r.id = s.resume_id
CROSS JOIN LATERAL (
    SELECT (CASE lower(split_part(coalesce(r.lng, ''), '-', 1))
        WHEN 'vi' THEN 'vi' WHEN 'en' THEN 'en' ELSE 'other' END)::text AS language
) AS l
WHERE r.live = true
  AND r.sign_in_to_view = false
  AND ($1::text IS NULL OR s.role = $1::text)
  AND ($2::text IS NULL OR l.language = $2::text)
  AND (
      $3::text IS NULL
      OR ($3::text = 'custom' AND s.template_id IS NULL)
      OR s.template_id = $3::text
  )
`

type CountShowcaseParams struct {
	Role     *string
	Lang     *string
	Template *string
}

func (q *Queries) CountShowcase(ctx context.Context, arg CountShowcaseParams) (int64, error) {
	row := q.db.QueryRow(ctx, countShowcase, arg.Role, arg.Lang, arg.Template)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteResumeShowcase = `-- name: DeleteResumeShowcase :execrows
DELETE FROM resume_showcase
WHERE resume_id = $1
`

func (q *Queries) DeleteResumeShowcase(ctx context.Context, resumeID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteResumeShowcase, resumeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getResumeShowcase = `-- name: GetResumeShowcase :one

SELECT resume_id, requested_at, role, review_key, card_version, template_id, reviewed_key, review_outcome, reviewed_at, first_listed_at FROM resume_showcase
WHERE resume_id = $1
`

// Community showcase queries (docs/design/showcase.md, ADR 0029). The
// resume_showcase row exists only while the opt-in does.
func (q *Queries) GetResumeShowcase(ctx context.Context, resumeID uuid.UUID) (ResumeShowcase, error) {
	row := q.db.QueryRow(ctx, getResumeShowcase, resumeID)
	var i ResumeShowcase
	err := row.Scan(
		&i.ResumeID,
		&i.RequestedAt,
		&i.Role,
		&i.ReviewKey,
		&i.CardVersion,
		&i.TemplateID,
		&i.ReviewedKey,
		&i.ReviewOutcome,
		&i.ReviewedAt,
		&i.FirstListedAt,
	)
	return i, err
}

const getResumeShowcaseForUpdate = `-- name: GetResumeShowcaseForUpdate :one
SELECT resume_id, requested_at, role, review_key, card_version, template_id, reviewed_key, review_outcome, reviewed_at, first_listed_at FROM resume_showcase
WHERE resume_id = $1
FOR UPDATE
`

// Locks the opt-in row so concurrent derived-value writes serialize.
func (q *Queries) GetResumeShowcaseForUpdate(ctx context.Context, resumeID uuid.UUID) (ResumeShowcase, error) {
	row := q.db.QueryRow(ctx, getResumeShowcaseForUpdate, resumeID)
	var i ResumeShowcase
	err := row.Scan(
		&i.ResumeID,
		&i.RequestedAt,
		&i.Role,
		&i.ReviewKey,
		&i.CardVersion,
		&i.TemplateID,
		&i.ReviewedKey,
		&i.ReviewOutcome,
		&i.ReviewedAt,
		&i.FirstListedAt,
	)
	return i, err
}

const insertResumeShowcase = `-- name: InsertResumeShowcase :exec
INSERT INTO resume_showcase (resume_id, requested_at, role, card_version, template_id)
VALUES (
    $1, $2, $3,
    $4, $5
)
`

type InsertResumeShowcaseParams struct {
	ResumeID    uuid.UUID
	RequestedAt time.Time
	Role        *string
	CardVersion string
	TemplateID  *string
}

// review_key and the other review columns are unused; the insert leaves them
// to their defaults (docs/design/showcase.md "Data and contract").
func (q *Queries) InsertResumeShowcase(ctx context.Context, arg InsertResumeShowcaseParams) error {
	_, err := q.db.Exec(ctx, insertResumeShowcase,
		arg.ResumeID,
		arg.RequestedAt,
		arg.Role,
		arg.CardVersion,
		arg.TemplateID,
	)
	return err
}

const listResumeShowcaseIDs = `-- name: ListResumeShowcaseIDs :many
SELECT resume_id FROM resume_showcase
ORDER BY resume_id
`

func (q *Queries) ListResumeShowcaseIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listResumeShowcaseIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var resume_id uuid.UUID
		if err := rows.Scan(&resume_id); err != nil {
			return nil, err
		}
		items = append(items, resume_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResumeShowcasesForUser = `-- name: ListResumeShowcasesForUser :many
SELECT s.resume_id, s.requested_at, s.role, s.review_key, s.card_version, s.template_id, s.reviewed_key, s.review_outcome, s.reviewed_at, s.first_listed_at
FROM resume_showcase s
JOIN resumes r ON r.id = s.resume_id
WHERE r.user_id = $1
`

func (q *Queries) ListResumeShowcasesForUser(ctx context.Context, userID uuid.UUID) ([]ResumeShowcase, error) {
	rows, err := q.db.Query(ctx, listResumeShowcasesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResumeShowcase
	for rows.Next() {
		var i ResumeShowcase
		if err := rows.Scan(
			&i.ResumeID,
			&i.RequestedAt,
			&i.Role,
			&i.ReviewKey,
			&i.CardVersion,
			&i.TemplateID,
			&i.ReviewedKey,
			&i.ReviewOutcome,
			&i.ReviewedAt,
			&i.FirstListedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShowcase = `-- name: ListShowcase :many
SELECT r.id, r.slug, r.schema_version, r.personal_details,
       s.card_version, s.template_id, s.role, l.language
FROM resume_showcase s
JOIN resumes r ON r.id = s.resume_id
CROSS JOIN LATERAL (
    SELECT (CASE lower(split_part(coalesce(r.lng, ''), '-', 1))
        WHEN 'vi' THEN 'vi' WHEN 'en' THEN 'en' ELSE 'other' END)::text AS language
) AS l
WHERE r.live = true
  AND r.sign_in_to_view = false
  AND ($1::text IS NULL OR s.role = $1::text)
  AND ($2::text IS NULL OR l.language = $2::text)
  AND (
      $3::text IS NULL
      OR ($3::text = 'custom' AND s.template_id IS NULL)
      OR s.template_id = $3::text
  )
ORDER BY s.requested_at DESC, s.resume_id DESC
LIMIT $5::int OFFSET $4::int
`

type ListShowcaseParams struct {
	Role       *string
	Lang       *string
	Template   *string
	PageOffset int32
	PageSize   int32
}

type ListShowcaseRow struct {
	ID              uuid.UUID
	Slug            *string
	SchemaVersion   int32
	PersonalDetails json.RawMessage
	CardVersion     string
	TemplateID      *string
	Role            *string
	Language        string
}

// The public listing. One statement checks all three listing conditions: the
// opt-in row exists, the resume is live, and sign in to view is off. It reads
// committed state on every call; nothing caches it. The page needs only the
// personal details (for the card's image text), so it reads no other document
// part; schema_version tells the caller whether those details are current.
func (q *Queries) ListShowcase(ctx context.Context, arg ListShowcaseParams) ([]ListShowcaseRow, error) {
	rows, err := q.db.Query(ctx, listShowcase,
		arg.Role,
		arg.Lang,
		arg.Template,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShowcaseRow
	for rows.Next() {
		var i ListShowcaseRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.SchemaVersion,
			&i.PersonalDetails,
			&i.CardVersion,
			&i.TemplateID,
			&i.Role,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResumeShowcaseDerived = `-- name: UpdateResumeShowcaseDerived :exec
UPDATE resume_showcase
SET card_version = $1,
    template_id = $2
WHERE resume_id = $3
`

type UpdateResumeShowcaseDerivedParams struct {
	CardVersion string
	TemplateID  *string
	ResumeID    uuid.UUID
}

func (q *Queries) UpdateResumeShowcaseDerived(ctx context.Context, arg UpdateResumeShowcaseDerivedParams) error {
	_, err := q.db.Exec(ctx, updateResumeShowcaseDerived, arg.CardVersion, arg.TemplateID, arg.ResumeID)
	return err
}

const updateResumeShowcaseRole = `-- name: UpdateResumeShowcaseRole :exec
UPDATE resume_showcase
SET role = $1
WHERE resume_id = $2
`

type UpdateResumeShowcaseRoleParams struct {
	Role     *string
	ResumeID uuid.UUID
}

func (q *Queries) UpdateResumeShowcaseRole(ctx context.Context, arg UpdateResumeShowcaseRoleParams) error {
	_, err := q.db.Exec(ctx, updateResumeShowcaseRole, arg.Role, arg.ResumeID)
	return err
}
