// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view_counts.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addResumeShareSignalDays = `-- name: AddResumeShareSignalDays :exec
INSERT INTO resume_share_signal_days AS s (resume_id, day, platform, fetches)
SELECT cell.resume_id, cell.day, cell.platform, cell.fetches
FROM (
    SELECT unnest($1::uuid[]) AS resume_id,
           unnest($2::date[]) AS day,
           unnest($3::text[]) AS platform,
           unnest($4::int[]) AS fetches
) AS cell
JOIN resumes ON resumes.id = cell.resume_id
ORDER BY cell.resume_id, cell.day, cell.platform
ON CONFLICT (resume_id, day, platform) DO UPDATE SET
    fetches = s.fetches + EXCLUDED.fetches
`

type AddResumeShareSignalDaysParams struct {
	ResumeIds []uuid.UUID
	Days      []pgtype.Date
	Platforms []string
	Fetches   []int32
}

func (q *Queries) AddResumeShareSignalDays(ctx context.Context, arg AddResumeShareSignalDaysParams) error {
	_, err := q.db.Exec(ctx, addResumeShareSignalDays,
		arg.ResumeIds,
		arg.Days,
		arg.Platforms,
		arg.Fetches,
	)
	return err
}

const addResumeViewDays = `-- name: AddResumeViewDays :exec
INSERT INTO resume_view_days AS d (resume_id, day, counted, bot, datacenter, anomaly, invalid, crawler)
SELECT cell.resume_id, cell.day, cell.counted, cell.bot, cell.datacenter, cell.anomaly, cell.invalid, cell.crawler
FROM (
    SELECT unnest($1::uuid[]) AS resume_id,
           unnest($2::date[]) AS day,
           unnest($3::int[]) AS counted,
           unnest($4::int[]) AS bot,
           unnest($5::int[]) AS datacenter,
           unnest($6::int[]) AS anomaly,
           unnest($7::int[]) AS invalid,
           unnest($8::int[]) AS crawler
) AS cell
JOIN resumes ON resumes.id = cell.resume_id
ORDER BY cell.resume_id, cell.day
ON CONFLICT (resume_id, day) DO UPDATE SET
    counted = d.counted + EXCLUDED.counted,
    bot = d.bot + EXCLUDED.bot,
    datacenter = d.datacenter + EXCLUDED.datacenter,
    anomaly = d.anomaly + EXCLUDED.anomaly,
    invalid = d.invalid + EXCLUDED.invalid,
    crawler = d.crawler + EXCLUDED.crawler
`

type AddResumeViewDaysParams struct {
	ResumeIds  []uuid.UUID
	Days       []pgtype.Date
	Counted    []int32
	Bot        []int32
	Datacenter []int32
	Anomaly    []int32
	Invalid    []int32
	Crawler    []int32
}

// Target-list unnest zips the equal-length arrays row by row. The join
// skips a resume deleted since the view; the cascade removes its rows
// otherwise.
func (q *Queries) AddResumeViewDays(ctx context.Context, arg AddResumeViewDaysParams) error {
	_, err := q.db.Exec(ctx, addResumeViewDays,
		arg.ResumeIds,
		arg.Days,
		arg.Counted,
		arg.Bot,
		arg.Datacenter,
		arg.Anomaly,
		arg.Invalid,
		arg.Crawler,
	)
	return err
}

const deleteOldResumeShareSignalDaysPage = `-- name: DeleteOldResumeShareSignalDaysPage :execrows
WITH candidates AS MATERIALIZED (
    SELECT resume_id, day, platform
    FROM resume_share_signal_days
    WHERE day < $1::date
    ORDER BY day, resume_id, platform
    LIMIT LEAST($2::int, 1000)
    FOR UPDATE SKIP LOCKED
)
DELETE FROM resume_share_signal_days AS s
USING candidates
WHERE s.resume_id = candidates.resume_id AND s.day = candidates.day
  AND s.platform = candidates.platform
`

type DeleteOldResumeShareSignalDaysPageParams struct {
	Cutoff    pgtype.Date
	LimitRows int32
}

func (q *Queries) DeleteOldResumeShareSignalDaysPage(ctx context.Context, arg DeleteOldResumeShareSignalDaysPageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldResumeShareSignalDaysPage, arg.Cutoff, arg.LimitRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldResumeViewDaysPage = `-- name: DeleteOldResumeViewDaysPage :execrows
WITH candidates AS MATERIALIZED (
    SELECT resume_id, day
    FROM resume_view_days
    WHERE day < $1::date
    ORDER BY day, resume_id
    LIMIT LEAST($2::int, 1000)
    FOR UPDATE SKIP LOCKED
)
DELETE FROM resume_view_days AS d
USING candidates
WHERE d.resume_id = candidates.resume_id AND d.day = candidates.day
`

type DeleteOldResumeViewDaysPageParams struct {
	Cutoff    pgtype.Date
	LimitRows int32
}

// Daily counts are kept 400 days (docs/design/viewer-analytics/README.md).
func (q *Queries) DeleteOldResumeViewDaysPage(ctx context.Context, arg DeleteOldResumeViewDaysPageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldResumeViewDaysPage, arg.Cutoff, arg.LimitRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLiveViewResumeByID = `-- name: GetLiveViewResumeByID :one
SELECT id, user_id FROM resumes
WHERE id = $1::uuid AND live = true
`

type GetLiveViewResumeByIDRow struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetLiveViewResumeByID(ctx context.Context, id uuid.UUID) (GetLiveViewResumeByIDRow, error) {
	row := q.db.QueryRow(ctx, getLiveViewResumeByID, id)
	var i GetLiveViewResumeByIDRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const getLiveViewResumeBySlug = `-- name: GetLiveViewResumeBySlug :one

SELECT id, user_id FROM resumes
WHERE slug = $1::text AND live = true
`

type GetLiveViewResumeBySlugRow struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// View count queries (docs/design/viewer-analytics/counting.md). Tables hold
// daily numbers only; days are Asia/Ho_Chi_Minh dates.
// The same live gate as GetPublicResumeBySlug.
func (q *Queries) GetLiveViewResumeBySlug(ctx context.Context, slug string) (GetLiveViewResumeBySlugRow, error) {
	row := q.db.QueryRow(ctx, getLiveViewResumeBySlug, slug)
	var i GetLiveViewResumeBySlugRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const getOwnedViewResume = `-- name: GetOwnedViewResume :one
SELECT id, title, slug, live FROM resumes
WHERE id = $1::uuid AND user_id = $2::uuid
`

type GetOwnedViewResumeParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetOwnedViewResumeRow struct {
	ID    uuid.UUID
	Title string
	Slug  *string
	Live  bool
}

func (q *Queries) GetOwnedViewResume(ctx context.Context, arg GetOwnedViewResumeParams) (GetOwnedViewResumeRow, error) {
	row := q.db.QueryRow(ctx, getOwnedViewResume, arg.ID, arg.UserID)
	var i GetOwnedViewResumeRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Live,
	)
	return i, err
}

const listResumeShareSignals = `-- name: ListResumeShareSignals :many
SELECT platform, sum(fetches)::bigint AS fetches
FROM resume_share_signal_days
WHERE resume_id = $1::uuid AND day >= $2::date
GROUP BY platform
HAVING sum(fetches) > 0
ORDER BY sum(fetches) DESC, platform
`

type ListResumeShareSignalsParams struct {
	ResumeID uuid.UUID
	Since    pgtype.Date
}

type ListResumeShareSignalsRow struct {
	Platform string
	Fetches  int64
}

func (q *Queries) ListResumeShareSignals(ctx context.Context, arg ListResumeShareSignalsParams) ([]ListResumeShareSignalsRow, error) {
	rows, err := q.db.Query(ctx, listResumeShareSignals, arg.ResumeID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResumeShareSignalsRow
	for rows.Next() {
		var i ListResumeShareSignalsRow
		if err := rows.Scan(&i.Platform, &i.Fetches); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResumeViewDays = `-- name: ListResumeViewDays :many
SELECT day, counted, bot, datacenter, anomaly, invalid, crawler
FROM resume_view_days
WHERE resume_id = $1::uuid AND day >= $2::date
ORDER BY day
`

type ListResumeViewDaysParams struct {
	ResumeID uuid.UUID
	Since    pgtype.Date
}

type ListResumeViewDaysRow struct {
	Day        pgtype.Date
	Counted    int32
	Bot        int32
	Datacenter int32
	Anomaly    int32
	Invalid    int32
	Crawler    int32
}

func (q *Queries) ListResumeViewDays(ctx context.Context, arg ListResumeViewDaysParams) ([]ListResumeViewDaysRow, error) {
	rows, err := q.db.Query(ctx, listResumeViewDays, arg.ResumeID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResumeViewDaysRow
	for rows.Next() {
		var i ListResumeViewDaysRow
		if err := rows.Scan(
			&i.Day,
			&i.Counted,
			&i.Bot,
			&i.Datacenter,
			&i.Anomaly,
			&i.Invalid,
			&i.Crawler,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViewSummaries = `-- name: ListViewSummaries :many
SELECT r.id, r.title, r.slug, r.live,
       COALESCE(sum(d.counted) FILTER (WHERE d.day >= $1::date), 0)::bigint AS real7,
       COALESCE(sum(d.bot + d.datacenter + d.anomaly + d.invalid + d.crawler)
           FILTER (WHERE d.day >= $1::date), 0)::bigint AS filtered7,
       COALESCE(sum(d.counted) FILTER (WHERE d.day >= $2::date), 0)::bigint AS real30,
       COALESCE(sum(d.bot + d.datacenter + d.anomaly + d.invalid + d.crawler)
           FILTER (WHERE d.day >= $2::date), 0)::bigint AS filtered30,
       COALESCE(sum(d.counted), 0)::bigint AS real90,
       COALESCE(sum(d.bot + d.datacenter + d.anomaly + d.invalid + d.crawler), 0)::bigint AS filtered90
FROM resumes AS r
LEFT JOIN resume_view_days AS d
    ON d.resume_id = r.id AND d.day >= $3::date
WHERE r.user_id = $4::uuid
  AND (r.live OR EXISTS (SELECT 1 FROM resume_view_days AS any_day WHERE any_day.resume_id = r.id))
GROUP BY r.id
ORDER BY r.created_at DESC, r.id DESC
LIMIT 1000
`

type ListViewSummariesParams struct {
	Since7  pgtype.Date
	Since30 pgtype.Date
	Since90 pgtype.Date
	UserID  uuid.UUID
}

type ListViewSummariesRow struct {
	ID         uuid.UUID
	Title      string
	Slug       *string
	Live       bool
	Real7      int64
	Filtered7  int64
	Real30     int64
	Filtered30 int64
	Real90     int64
	Filtered90 int64
}

// Every owned resume that is live or has counts, with totals over the last
// 7, 30, and 90 days.
func (q *Queries) ListViewSummaries(ctx context.Context, arg ListViewSummariesParams) ([]ListViewSummariesRow, error) {
	rows, err := q.db.Query(ctx, listViewSummaries,
		arg.Since7,
		arg.Since30,
		arg.Since90,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListViewSummariesRow
	for rows.Next() {
		var i ListViewSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Live,
			&i.Real7,
			&i.Filtered7,
			&i.Real30,
			&i.Filtered30,
			&i.Real90,
			&i.Filtered90,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
