// Code generated from templates/*.json. DO NOT EDIT.

package showcase

// Preset is one template preset in showcase match form: its customization in
// stored form, without the leaves and the placement the showcase ignores, as
// canonical JSON.
type Preset struct {
	ID    string
	Match string
}

// Presets lists every template preset, ordered by ID.
var Presets = []Preset{
	{ID: "academic-dense", Match: `{"colors":{"background":"#ffffff","primary":"#12293f","text":"#1a1e22"},"font":{"baseSizePx":13,"family":"source-sans-3"},"header":{"align":"left","detailsLayout":"inline","iconStyle":"none"},"heading":{"showRule":true,"style":"uppercase"},"layout":{"columns":1,"surfaceTarget":"none"},"sectionDisplay":{"language":{"style":"text"},"skill":{"style":"text"}},"spacing":{"entryGap":6,"lineHeight":1.3,"pageMargin":{"x":20,"y":12},"sectionGap":20}}`},
	{ID: "ats-plain", Match: `{"colors":{"background":"#ffffff","primary":"#000000","text":"#000000"},"font":{"baseSizePx":14,"family":"source-sans-3"},"header":{"align":"left","detailsLayout":"stacked","iconStyle":"none"},"heading":{"showRule":true,"style":"normal"},"layout":{"columns":1,"surfaceTarget":"none"},"sectionDisplay":{"language":{"style":"text"},"skill":{"style":"text"}},"spacing":{"entryGap":10,"lineHeight":1.45,"pageMargin":{"x":18,"y":16},"sectionGap":20}}`},
	{ID: "classic-serif", Match: `{"colors":{"accent":"#1f3864","background":"#ffffff","primary":"#12151a","text":"#23262c"},"font":{"baseSizePx":13,"family":"roboto-serif"},"header":{"align":"center","detailsLayout":"inline","iconStyle":"none"},"heading":{"showRule":true,"style":"uppercase"},"layout":{"columns":1,"surfaceTarget":"none"},"sectionDisplay":{"language":{"style":"text"},"skill":{"style":"text"}},"spacing":{"entryGap":12,"lineHeight":1.5,"pageMargin":{"x":25,"y":20},"sectionGap":22}}`},
	{ID: "consulting-formal", Match: `{"colors":{"accent":"#1c4e80","background":"#ffffff","primary":"#14304f","text":"#33383d"},"font":{"baseSizePx":13,"family":"inter"},"header":{"align":"left","detailsLayout":"inline","iconStyle":"none"},"heading":{"showRule":true,"style":"titlecase"},"layout":{"columns":1,"surfaceTarget":"none"},"sectionDisplay":{"language":{"style":"text"},"skill":{"style":"text"}},"spacing":{"entryGap":9,"lineHeight":1.45,"pageMargin":{"x":25,"y":15},"sectionGap":15}}`},
	{ID: "creative-accent", Match: `{"colors":{"accent":"#c23a14","background":"#ffffff","primary":"#c23a14","surface":"#fff0eb","text":"#1f1a17"},"font":{"baseSizePx":15,"family":"source-sans-3"},"header":{"align":"left","detailsLayout":"inline","iconStyle":"none"},"heading":{"showRule":true,"style":"uppercase"},"layout":{"columns":1,"surfaceTarget":"header"},"sectionDisplay":{"language":{"style":"text"},"skill":{"style":"tag"}},"spacing":{"entryGap":10,"lineHeight":1.5,"pageMargin":{"x":22,"y":18},"sectionGap":20}}`},
	{ID: "designer-tag", Match: `{"colors":{"accent":"#54692a","background":"#f4f1ea","primary":"#2f3a1e","text":"#242220"},"font":{"baseSizePx":15,"family":"be-vietnam-pro"},"header":{"align":"center","detailsLayout":"inline","iconStyle":"outline"},"heading":{"showRule":false,"style":"uppercase"},"layout":{"columns":1,"surfaceTarget":"none"},"sectionDisplay":{"language":{"style":"tag"},"skill":{"style":"tag"}},"spacing":{"entryGap":12,"lineHeight":1.5,"pageMargin":{"x":26,"y":22},"sectionGap":24}}`},
	{ID: "editorial-wide", Match: `{"colors":{"accent":"#7a4a24","background":"#faf8f3","primary":"#3a2c1e","text":"#24211c"},"font":{"baseSizePx":16,"family":"alegreya"},"header":{"align":"left","detailsLayout":"inline","iconStyle":"none"},"heading":{"showRule":false,"style":"normal"},"layout":{"columns":1,"surfaceTarget":"none"},"sectionDisplay":{"language":{"style":"text"},"skill":{"style":"text"}},"spacing":{"entryGap":16,"lineHeight":1.65,"pageMargin":{"x":35,"y":22},"sectionGap":32}}`},
	{ID: "elegant-serif-two", Match: `{"colors":{"background":"#ffffff","primary":"#6b2737","surface":"#f2ebdf","text":"#2b2622"},"font":{"baseSizePx":14,"family":"alegreya"},"header":{"align":"left","detailsLayout":"inline","iconStyle":"none"},"heading":{"showRule":true,"style":"titlecase"},"layout":{"columns":2,"surfaceTarget":"sidebar"},"sectionDisplay":{"language":{"style":"dots"},"skill":{"style":"text"}},"spacing":{"entryGap":12,"lineHeight":1.55,"pageMargin":{"x":18,"y":16},"sectionGap":24}}`},
	{ID: "engineer-compact", Match: `{"colors":{"accent":"#0d5a73","background":"#ffffff","primary":"#10394d","text":"#1a1f24"},"font":{"baseSizePx":13,"family":"source-sans-3"},"header":{"align":"left","detailsLayout":"inline","iconStyle":"outline"},"heading":{"showRule":true,"style":"uppercase"},"layout":{"columns":2,"surfaceTarget":"none"},"sectionDisplay":{"language":{"style":"dots"},"skill":{"style":"bar"}},"spacing":{"entryGap":6,"lineHeight":1.3,"pageMargin":{"x":11,"y":12},"sectionGap":12}}`},
	{ID: "executive-band", Match: `{"colors":{"accent":"#8a5a1e","background":"#ffffff","primary":"#16273d","surface":"#16273d","text":"#1f2937"},"font":{"baseSizePx":15,"family":"be-vietnam-pro"},"header":{"align":"left","detailsLayout":"inline","iconStyle":"none"},"heading":{"showRule":false,"style":"uppercase"},"layout":{"columns":1,"surfaceTarget":"header"},"sectionDisplay":{"language":{"style":"dots"},"skill":{"style":"text"}},"spacing":{"entryGap":12,"lineHeight":1.45,"pageMargin":{"x":18,"y":14},"sectionGap":24}}`},
	{ID: "government-formal", Match: `{"colors":{"background":"#ffffff","primary":"#000000","text":"#000000"},"font":{"baseSizePx":14,"family":"source-sans-3"},"header":{"align":"left","detailsLayout":"stacked","iconStyle":"none"},"heading":{"showRule":true,"style":"uppercase"},"layout":{"columns":1,"surfaceTarget":"none"},"sectionDisplay":{"language":{"style":"text"},"skill":{"style":"text"}},"spacing":{"entryGap":14,"lineHeight":1.5,"pageMargin":{"x":25,"y":25},"sectionGap":24}}`},
	{ID: "graduate-friendly", Match: `{"colors":{"accent":"#a04f16","background":"#ffffff","primary":"#7a3b1c","surface":"#f7e8d9","text":"#2f2a26"},"font":{"baseSizePx":15,"family":"source-sans-3"},"header":{"align":"left","detailsLayout":"stacked","iconStyle":"outline"},"heading":{"showRule":true,"style":"titlecase"},"layout":{"columns":1,"surfaceTarget":"header"},"sectionDisplay":{"language":{"style":"tag"},"skill":{"style":"tag"}},"spacing":{"entryGap":18,"lineHeight":1.55,"pageMargin":{"x":20,"y":16},"sectionGap":24}}`},
	{ID: "high-contrast", Match: `{"colors":{"accent":"#0b3fd6","background":"#ffffff","primary":"#000000","text":"#141414"},"font":{"baseSizePx":18,"family":"inter"},"header":{"align":"left","detailsLayout":"stacked","iconStyle":"outline"},"heading":{"showRule":true,"style":"uppercase"},"layout":{"columns":1,"surfaceTarget":"none"},"sectionDisplay":{"language":{"style":"text"},"skill":{"style":"text"}},"spacing":{"entryGap":20,"lineHeight":1.6,"pageMargin":{"x":18,"y":16},"sectionGap":36}}`},
	{ID: "international-lang", Match: `{"colors":{"accent":"#5a4a3a","background":"#ffffff","primary":"#191614","surface":"#f0ede7","text":"#2a2724"},"font":{"baseSizePx":13,"family":"be-vietnam-pro"},"header":{"align":"center","detailsLayout":"inline","iconStyle":"none"},"heading":{"showRule":true,"style":"normal"},"layout":{"columns":2,"surfaceTarget":"header"},"sectionDisplay":{"language":{"style":"bar"},"skill":{"style":"text"}},"spacing":{"entryGap":9,"lineHeight":1.55,"pageMargin":{"x":16,"y":14},"sectionGap":18}}`},
	{ID: "minimal-air", Match: `{"colors":{"background":"#ffffff","primary":"#14161a","text":"#24272c"},"font":{"baseSizePx":15,"family":"inter"},"header":{"align":"left","detailsLayout":"inline","iconStyle":"none"},"heading":{"showRule":false,"style":"uppercase"},"layout":{"columns":1,"surfaceTarget":"none"},"sectionDisplay":{"language":{"style":"text"},"skill":{"style":"text"}},"spacing":{"entryGap":16,"lineHeight":1.65,"pageMargin":{"x":30,"y":24},"sectionGap":36}}`},
	{ID: "modern-sidebar", Match: `{"colors":{"accent":"#0f6b7d","background":"#ffffff","primary":"#0e3f52","surface":"#e3ecf0","text":"#1c2b33"},"font":{"baseSizePx":14,"family":"be-vietnam-pro"},"header":{"align":"left","detailsLayout":"inline","iconStyle":"outline"},"heading":{"showRule":true,"style":"uppercase"},"layout":{"columns":2,"surfaceTarget":"sidebar"},"sectionDisplay":{"language":{"style":"dots"},"skill":{"style":"bar"}},"spacing":{"entryGap":10,"lineHeight":1.5,"pageMargin":{"x":14,"y":13},"sectionGap":20}}`},
	{ID: "mono-print", Match: `{"colors":{"background":"#ffffff","primary":"#000000","text":"#000000"},"font":{"baseSizePx":14,"family":"source-sans-3"},"header":{"align":"left","detailsLayout":"stacked","iconStyle":"none"},"heading":{"showRule":false,"style":"uppercase"},"layout":{"columns":1,"surfaceTarget":"none"},"sectionDisplay":{"language":{"style":"text"},"skill":{"style":"text"}},"spacing":{"entryGap":12,"lineHeight":1.5,"pageMargin":{"x":20,"y":18},"sectionGap":26}}`},
	{ID: "nordic-muted", Match: `{"colors":{"accent":"#4a6b80","background":"#ffffff","primary":"#2f4557","surface":"#f1f3f5","text":"#333a42"},"font":{"baseSizePx":13,"family":"source-sans-3"},"header":{"align":"left","detailsLayout":"inline","iconStyle":"outline"},"heading":{"showRule":true,"style":"uppercase"},"layout":{"columns":2,"surfaceTarget":"sidebar"},"sectionDisplay":{"language":{"style":"dots"},"skill":{"style":"text"}},"spacing":{"entryGap":11,"lineHeight":1.55,"pageMargin":{"x":18,"y":16},"sectionGap":22}}`},
	{ID: "one-page-tight", Match: `{"colors":{"accent":"#2f4858","background":"#ffffff","primary":"#22303c","text":"#1c2126"},"font":{"baseSizePx":13,"family":"source-sans-3"},"header":{"align":"left","detailsLayout":"inline","iconStyle":"none"},"heading":{"showRule":true,"style":"uppercase"},"layout":{"columns":2,"surfaceTarget":"none"},"sectionDisplay":{"language":{"style":"text"},"skill":{"style":"text"}},"spacing":{"entryGap":6,"lineHeight":1.25,"pageMargin":{"x":12,"y":11},"sectionGap":10}}`},
	{ID: "startup-bold", Match: `{"colors":{"background":"#ffffff","primary":"#0b0d10","text":"#2b3038"},"font":{"baseSizePx":16,"family":"inter"},"header":{"align":"left","detailsLayout":"inline","iconStyle":"outline"},"heading":{"showRule":false,"style":"uppercase"},"layout":{"columns":1,"surfaceTarget":"none"},"sectionDisplay":{"language":{"style":"dots"},"skill":{"style":"dots"}},"spacing":{"entryGap":10,"lineHeight":1.35,"pageMargin":{"x":26,"y":16},"sectionGap":30}}`},
}
