// Code generated by scripts/generate-public-roots.mjs; DO NOT EDIT.

export type PublicRootDispatch = 'reserved' | 'go' | 'nuxt' | 'deny';

export interface PublicRootRoute {
  readonly root: string;
  readonly dispatch: PublicRootDispatch;
}

export const publicRootRoutes = [
  { root: 'admin', dispatch: 'reserved' },
  { root: 'api', dispatch: 'go' },
  { root: 'app', dispatch: 'nuxt' },
  { root: 'forgot-password', dispatch: 'nuxt' },
  { root: 'healthz', dispatch: 'go' },
  { root: '_nuxt', dispatch: 'nuxt' },
  { root: 'internal-render', dispatch: 'deny' },
  { root: 'llms.txt', dispatch: 'go' },
  { root: 'login', dispatch: 'nuxt' },
  { root: 'people', dispatch: 'reserved' },
  { root: 'print', dispatch: 'deny' },
  { root: 'readyz', dispatch: 'go' },
  { root: 'register', dispatch: 'nuxt' },
  { root: 'reset-password', dispatch: 'nuxt' },
  { root: 'robots.txt', dispatch: 'go' },
  { root: 'sitemap.xml', dispatch: 'go' },
  { root: 'u', dispatch: 'reserved' },
  { root: 'verify-email', dispatch: 'nuxt' },
] as const satisfies readonly PublicRootRoute[];

const reservedPublicRoots: ReadonlySet<string> = new Set(
  publicRootRoutes.map(({ root }) => root),
);

export function isReservedPublicRoot(root: string): boolean {
  return reservedPublicRoots.has(root);
}
