export const FIXED_PHOTO_DATA_URL
  = 'data:image/png;base64,'
    + 'iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAACYUlEQVR42u3TMRGA'
    + 'MBAAwXeBjMzgA9rISEkXb5GBDQw8FtJ9s8U5uI3jvFJ1tTFVWJgQAAAEAAACAAABA'
    + 'IAAAEAAACAAABAAAAgAAAQAAAIAAAEAgAAAQAAAIAAAEAAACAAABAAAAgAAAQCAA'
    + 'ABAAAAgAAAQAAAIAABkQgAAEAAACAAABAAAAgAAAQCAAABAAAAgAAAQAAAIAAAEAA'
    + 'ACAAABAIAAAEAAACAAABAAAAgAAAQAAAIAAAEAgAAAQAAAIAAAEAAAAGBCAAAQAAA'
    + 'IAAAEAAACAAABAIAAAEAAACAAABAAAAgAAAQAAAIAAAEAgAAAQAAAIAAAEAAACAAA'
    + 'BAAAgAAAQCAAABAAAAgAAAAwIQAACAAABAAAAgAAAQAAAIAAAEAgAAAQAAAIAAAEAA'
    + 'ACAAABAAAAgAAAQCAAABAAACgbQDv01N1fetWYQAAAIAAAEAAACAAABAAAAgAAAQAA'
    + 'AIAAAEAgAAAQAAAIAAAEAAACAAABAAAAgAAAQCAAABAAAAgAAAQAAAIAAAEAAACAAA'
    + 'BAIAAAAAAAQCAAABAAAAgAAAQAAAIAAAEAAACAAABAIAAAEAAACAAABAAAAgAAAQAA'
    + 'AIAAAEAgAAAQAAAIAAAEAAACAAABAAAAgAAAQAAACYEAAABAIAAAEAAACAAABAAAAg'
    + 'AAAQAAAIAAAEAgAAAQAAAIAAAEAAACAAABAAAAgAAAQCAAABAAAAgAAAQAAAIAAAEA'
    + 'AACAACZEAAABAAAAgAAAQCAAABAAAAgAAAQAAAIAAAEAAACAAABAIAAAEAAACAAABA'
    + 'AAAgAALTdD+EYK7EAnRwXAAAAAElFTkSuQmCC';

export const FIXED_PHOTO_SHA256
  = 'aa570fab912ce9b49b805b07decf274178b3c0092b983c1a1127bed3b213252e';
