// Code generated by scripts/generate-public-roots.mjs; DO NOT EDIT.

package publicroots

// Dispatch is the edge owner for one immutable public root.
type Dispatch string

const (
	DispatchReserved Dispatch = "reserved"
	DispatchGo       Dispatch = "go"
	DispatchNuxt     Dispatch = "nuxt"
	DispatchDeny     Dispatch = "deny"
)

// Route is one authority-ordered public-root dispatch row.
type Route struct {
	Root     string
	Dispatch Dispatch
}

// Routes is the immutable version-6 public-root registry.
var Routes = [...]Route{
	{Root: ".well-known", Dispatch: DispatchGo},
	{Root: "admin", Dispatch: DispatchReserved},
	{Root: "api", Dispatch: DispatchGo},
	{Root: "app", Dispatch: DispatchNuxt},
	{Root: "authorize", Dispatch: DispatchNuxt},
	{Root: "forgot-password", Dispatch: DispatchNuxt},
	{Root: "healthz", Dispatch: DispatchGo},
	{Root: "_nuxt", Dispatch: DispatchNuxt},
	{Root: "internal-render", Dispatch: DispatchDeny},
	{Root: "llms.txt", Dispatch: DispatchGo},
	{Root: "login", Dispatch: DispatchNuxt},
	{Root: "mcp", Dispatch: DispatchGo},
	{Root: "oauth", Dispatch: DispatchGo},
	{Root: "people", Dispatch: DispatchReserved},
	{Root: "print", Dispatch: DispatchDeny},
	{Root: "readyz", Dispatch: DispatchGo},
	{Root: "register", Dispatch: DispatchNuxt},
	{Root: "reset-password", Dispatch: DispatchNuxt},
	{Root: "robots.txt", Dispatch: DispatchGo},
	{Root: "sitemap.xml", Dispatch: DispatchGo},
	{Root: "u", Dispatch: DispatchReserved},
	{Root: "verify-email", Dispatch: DispatchNuxt},
}

var reserved = map[string]struct{}{
	".well-known":     {},
	"admin":           {},
	"api":             {},
	"app":             {},
	"authorize":       {},
	"forgot-password": {},
	"healthz":         {},
	"_nuxt":           {},
	"internal-render": {},
	"llms.txt":        {},
	"login":           {},
	"mcp":             {},
	"oauth":           {},
	"people":          {},
	"print":           {},
	"readyz":          {},
	"register":        {},
	"reset-password":  {},
	"robots.txt":      {},
	"sitemap.xml":     {},
	"u":               {},
	"verify-email":    {},
}

// Reserved reports whether root is unavailable as a public resume slug.
func Reserved(root string) bool {
	_, ok := reserved[root]
	return ok
}
