// Code generated by scripts/generate-public-roots.mjs; DO NOT EDIT.

import { describe, expect, it } from 'vitest';

import {
  isReservedPublicRoot,
  publicRootRoutes,
} from '../app/public-roots.generated';

describe('generated public-root registry', () => {
  it('matches the immutable v6 source in authority order', () => {
    expect(publicRootRoutes).toEqual([
      { root: '.well-known', dispatch: 'go' },
      { root: 'admin', dispatch: 'reserved' },
      { root: 'api', dispatch: 'go' },
      { root: 'app', dispatch: 'nuxt' },
      { root: 'authorize', dispatch: 'nuxt' },
      { root: 'forgot-password', dispatch: 'nuxt' },
      { root: 'healthz', dispatch: 'go' },
      { root: '_nuxt', dispatch: 'nuxt' },
      { root: 'internal-render', dispatch: 'deny' },
      { root: 'llms.txt', dispatch: 'go' },
      { root: 'login', dispatch: 'nuxt' },
      { root: 'mcp', dispatch: 'go' },
      { root: 'oauth', dispatch: 'go' },
      { root: 'people', dispatch: 'reserved' },
      { root: 'print', dispatch: 'deny' },
      { root: 'readyz', dispatch: 'go' },
      { root: 'register', dispatch: 'nuxt' },
      { root: 'reset-password', dispatch: 'nuxt' },
      { root: 'robots.txt', dispatch: 'go' },
      { root: 'sitemap.xml', dispatch: 'go' },
      { root: 'u', dispatch: 'reserved' },
      { root: 'verify-email', dispatch: 'nuxt' },
    ]);
    expect(publicRootRoutes).toHaveLength(22);
  });

  it('reserves every registered root and no unknown root', () => {
    for (const { root } of publicRootRoutes) {
      expect(isReservedPublicRoot(root)).toBe(true);
    }
    expect(isReservedPublicRoot('unregistered-root')).toBe(false);
  });
});
