//go:build ignore

// extpict_gen writes extpict_table.go, the Extended_Pictographic code point
// ranges the favicon emoji check uses. Regenerate with `go generate` in this
// package after bumping sourceURL to a newer Unicode version.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

const sourceURL = "https://www.unicode.org/Public/17.0.0/ucd/emoji/emoji-data.txt"

type codeRange struct{ lo, hi rune }

func main() {
	client := &http.Client{Timeout: 30 * time.Second}
	response, err := client.Get(sourceURL)
	if err != nil {
		log.Fatalf("fetch %s: %v", sourceURL, err)
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		log.Fatalf("fetch %s: status %d", sourceURL, response.StatusCode)
	}
	body, err := io.ReadAll(io.LimitReader(response.Body, 4<<20))
	if err != nil {
		log.Fatalf("read %s: %v", sourceURL, err)
	}
	ranges, err := parse(body)
	if err != nil {
		log.Fatal(err)
	}
	source, err := render(ranges)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("extpict_table.go", source, 0o644); err != nil {
		log.Fatal(err)
	}
}

func parse(body []byte) ([]codeRange, error) {
	var ranges []codeRange
	scanner := bufio.NewScanner(bytes.NewReader(body))
	for scanner.Scan() {
		line, _, _ := strings.Cut(scanner.Text(), "#")
		fields := strings.Split(line, ";")
		if len(fields) != 2 || strings.TrimSpace(fields[1]) != "Extended_Pictographic" {
			continue
		}
		loText, hiText, found := strings.Cut(strings.TrimSpace(fields[0]), "..")
		if !found {
			hiText = loText
		}
		lo, err := strconv.ParseUint(loText, 16, 32)
		if err != nil {
			return nil, fmt.Errorf("parse %q: %w", line, err)
		}
		hi, err := strconv.ParseUint(hiText, 16, 32)
		if err != nil {
			return nil, fmt.Errorf("parse %q: %w", line, err)
		}
		ranges = append(ranges, codeRange{rune(lo), rune(hi)})
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if len(ranges) == 0 {
		return nil, fmt.Errorf("no Extended_Pictographic ranges in %s", sourceURL)
	}
	sort.Slice(ranges, func(i, j int) bool { return ranges[i].lo < ranges[j].lo })
	merged := []codeRange{ranges[0]}
	for _, next := range ranges[1:] {
		last := &merged[len(merged)-1]
		if next.lo <= last.hi+1 {
			last.hi = max(last.hi, next.hi)
			continue
		}
		merged = append(merged, next)
	}
	return merged, nil
}

func render(ranges []codeRange) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by extpict_gen.go from %s. DO NOT EDIT.\n\n", sourceURL)
	out.WriteString("package publicpage\n\n")
	out.WriteString("// extendedPictographic holds the Extended_Pictographic ranges, sorted and\n")
	out.WriteString("// merged. See https://www.unicode.org/license.txt for the data licence.\n")
	out.WriteString("var extendedPictographic = [][2]rune{\n")
	for _, entry := range ranges {
		fmt.Fprintf(&out, "\t{0x%04X, 0x%04X},\n", entry.lo, entry.hi)
	}
	out.WriteString("}\n")
	return format.Source(out.Bytes())
}
