variable "account_id" {
  type        = string
  description = "AWS account ID"
}

variable "state_kms_key_arn" {
  type        = string
  description = "KMS key that encrypts state and plans, from deploy/aws/bootstrap"
}

variable "media_bucket_name" {
  type        = string
  description = "Private media bucket name"
}

variable "ses_from_address" {
  type    = string
  default = "danny@aboutme.vn"
}

variable "ses_from_name" {
  type    = string
  default = "Danny from aboutme.vn"
}

variable "ses_configuration_set" {
  type    = string
  default = "aboutme-auth"
}

variable "password_registration_enabled" {
  type        = bool
  default     = true
  description = "false turns off email-and-password sign-up, for example while SES is in the sandbox"
}

variable "provider_login_enabled" {
  type        = string
  default     = ""
  description = "\"google\" turns on Google login and \"google,linkedin\" adds LinkedIn, once each provider's SSM parameters exist; \"\" keeps provider login off"
}

# Initial task definition images. deploy.sh registers later revisions.
variable "image_server" {
  type = string
}

variable "image_web" {
  type = string
}

variable "image_caddy" {
  type = string
}

variable "alarm_email" {
  type        = string
  description = "Where alarm mail goes; kept in the ignored prod.tfvars"
}

variable "site_alarm_enabled" {
  type    = bool
  default = false
}

# The canonical same-account IAM ARN behind the owner's `aws login` session:
# an IAM user or role ARN, never an STS assumed-role session ARN. OpenTofu
# trusts only this ARN as aboutme-prod-operator's assume-role principal. Kept
# in the ignored prod.tfvars.
variable "operator_principal_arn" {
  type        = string
  description = "Same-account IAM user or role ARN trusted to assume aboutme-prod-operator"
  validation {
    condition     = can(regex("^arn:aws:iam::${var.account_id}:(role|user)/[A-Za-z0-9+=,.@_/-]+$", var.operator_principal_arn))
    error_message = "operator_principal_arn must be an IAM role or user ARN in this same account, not an assumed-role session ARN."
  }
}

# Off until a healthy v0.4.2 or later release raises the production
# minimum-release fence; see docs/design/passkey-release-fence.md.
variable "passkey_enrollment_enabled" {
  type        = bool
  default     = false
  description = "PASSKEY_ENROLLMENT_ENABLED for the server"
}

# Off until a healthy v0.4.7 or later release raises the production
# minimum-release fence to numeric 4007; see
# docs/design/passkey-release-fence.md, "Authenticator-app key
# re-encryption".
variable "preview_card_enabled" {
  type        = bool
  default     = false
  description = "PREVIEW_CARD_ENABLED for the server"
}

variable "totp_enrollment_enabled" {
  type        = bool
  default     = false
  description = "TOTP_ENROLLMENT_ENABLED for the server"
}

# Chooses which protected totp/key-<slot> SSM parameter is TOTP_ACTIVE_KEY;
# see docs/design/totp-key-management.md, "Key ring" and "Rotation".
variable "totp_active_key_slot" {
  type        = string
  default     = "a"
  description = "Which totp/key-<slot> parameter supplies TOTP_ACTIVE_KEY: \"a\" or \"b\""
}

# Empty until a rotation is in progress; must differ from the active slot.
variable "totp_previous_key_slot" {
  type        = string
  default     = ""
  description = "Which totp/key-<slot> parameter supplies TOTP_PREVIOUS_KEY: \"\", \"a\", or \"b\""
}

# docs/design/cloudfront-edge.md, "DDoS and WAF": rules count for a week
# before the owner switches them to block.
variable "waf_block" {
  type        = bool
  default     = false
  description = "false: the WAF web ACL only counts matches; true after a week of counts: it blocks them"
}

# Generated by Google Workspace; kept out of the public repository like the
# other generated DNS tokens (docs/runbooks/dns.md).
variable "google_workspace" {
  type = object({
    verification_label  = string
    verification_target = string
    dkim_txt            = string
  })
  description = "Google Workspace domain verification CNAME and google._domainkey TXT value"
}

variable "transparency_bucket_name" {
  type        = string
  default     = ""
  description = "Private bucket for the deployment document; \"\" names it aboutme-prod-transparency-<account id>"
}

variable "observer_image_digest" {
  type        = string
  default     = ""
  description = "Digest observer.sh copied into the observer ECR repository; \"\" until the first copy"
}

variable "observer_reserved_concurrency" {
  type        = number
  default     = null
  description = "Reserved concurrency for the observer function; null until the account's Lambda concurrency quota allows it"
}
